#if 0
* hddSM-renconst.h
* RC declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:50
* this file is part of FeynHiggs
#endif

	ComplexType dMWsq1, dMZsq1, dSW1, dZAA1heavy, dZAA1light
	ComplexType dZe1, dZH1, dZZA1, dMf1(4,3), dZfL1(4,3,3)
	ComplexType dZfR1(4,3,3)
	common /hddSM_renconst/ dMWsq1, dMZsq1, dSW1, dZAA1heavy
	common /hddSM_renconst/ dZAA1light, dZe1, dZH1, dZZA1, dMf1
	common /hddSM_renconst/ dZfL1, dZfR1

