#if 0
* hddSM-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:50
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hddSM-renconst.h"

	ComplexType Opt1(3), Sub43, Sub21, Sub56, Sub40, Sub41, Sub25
	ComplexType Sub31, Sub26, Sub17, Sub13, Sub12(3), Sub15(3)
	ComplexType Sub19(3), Sub44, Sub50, Sub39, Sub6(3), Sub7(3)
	ComplexType Sub9(3), Sub49, Sub14(3), Sub18(3), Sub2(3)
	ComplexType Sub3(3), pave1(Ncc,3), pave2, pave3(Ncc), pave4
	ComplexType pave5(Ncc), pave6(Ncc), pave7(3), pave8(Ncc,3)
	ComplexType pave9(Ncc)
	common /hddSM_varXs/ Opt1, Sub43, Sub21, Sub56, Sub40, Sub41
	common /hddSM_varXs/ Sub25, Sub31, Sub26, Sub17, Sub13
	common /hddSM_varXs/ Sub12, Sub15, Sub19, Sub44, Sub50
	common /hddSM_varXs/ Sub39, Sub6, Sub7, Sub9, Sub49, Sub14
	common /hddSM_varXs/ Sub18, Sub2, Sub3, pave1, pave2, pave3
	common /hddSM_varXs/ pave4, pave5, pave6, pave7, pave8, pave9

	ComplexType F1, F2
	ComplexType Sub53, Sub46, Sub35, Sub36, Sub57, Sub42, Sub51
	ComplexType Sub34, Sub27, Sub23, Sub1, Sub29, Sub32, Sub38
	ComplexType Sub37, Sub48, Sub55, Sub59, Sub33, Sub61, Sub60
	ComplexType Sub47, Sub54, Sub58, Sub16(3)
	ComplexType Sub20(3), Sub4(3), Sub5(3)
	ComplexType Sub8(3), Sub11(3), Sub10(3)
	ComplexType Sub45, Sub63, Sub30, Sub28, Sub22, Sub24, Sub52
	ComplexType Sub62
	common /hddSM_varXh/ F1, F2, Sub53, Sub46, Sub35, Sub36
	common /hddSM_varXh/ Sub57, Sub42, Sub51, Sub34, Sub27
	common /hddSM_varXh/ Sub23, Sub1, Sub29, Sub32, Sub38, Sub37
	common /hddSM_varXh/ Sub48, Sub55, Sub59, Sub33, Sub61
	common /hddSM_varXh/ Sub60, Sub47, Sub54, Sub58, Sub16
	common /hddSM_varXh/ Sub20, Sub4, Sub5, Sub8, Sub11, Sub10
	common /hddSM_varXh/ Sub45, Sub63, Sub30, Sub28, Sub22
	common /hddSM_varXh/ Sub24, Sub52, Sub62

	integer seq(2), Hel(3)
	common /hddSM_helind/ seq, Hel

	integer Gen4
	common /hddSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hddSM_formfactors/ Ctree, Cloop, MatSUN

#endif
