#if 0
* hgagaSM-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub9, Sub1(3), Sub3(3), Sub6(3), pave1(Ncc)
	ComplexType pave2, pave3(Ncc,3), pave4(Ncc,3), pave5(Ncc,3)
	ComplexType pave6(3), pave7(3), pave8(3)
	common /hgagaSM_varXs/ Sub9, Sub1, Sub3, Sub6, pave1, pave2
	common /hgagaSM_varXs/ pave3, pave4, pave5, pave6, pave7
	common /hgagaSM_varXs/ pave8

	ComplexType Pair1, Pair2, Pair3, Abb6, Abb2, Abb1, Abb3, Abb5
	ComplexType Sub10, Sub11, Sub12, Sub13, Sub8(3)
	ComplexType Sub4(3), Sub5(3), Sub2(3)
	ComplexType Sub7(3)
	common /hgagaSM_varXh/ Pair1, Pair2, Pair3, Abb6, Abb2, Abb1
	common /hgagaSM_varXh/ Abb3, Abb5, Sub10, Sub11, Sub12
	common /hgagaSM_varXh/ Sub13, Sub8, Sub4, Sub5, Sub2, Sub7

	integer seq(2), Hel(3)
	common /hgagaSM_helind/ seq, Hel

	integer Gen4
	common /hgagaSM_indices/ Gen4

	ComplexType Cloop(1)
	common /hgagaSM_formfactors/ Cloop

#endif
