* gzvars.h
* variable declarations
* generated by FormCalc 12 Apr 2013 17:41

#include "decl.h"

	double precision S, T, U
	common /gzkinvars/ S, T, U

	integer Hel(4)
	common /gzkinvars/ Hel

	double complex F3, F6, F35, F37, F42, F47, F49, F54, F32, F85
	double complex F86, F33, F87, F88, F36, F48, Pair4, Pair8
	double complex Pair11, Pair9, Pair10, Eps12, Eps13, Abb14
	double complex Abb15, Abb116, Abb117, Abb128, Abb129, Abb22
	double complex Abb23, Abb38, Abb50, Abb89, Abb90, Abb39, Abb51
	double complex Abb91, Abb92, Abb16, Abb75, Abb80, Abb24, Abb5
	double complex Abb43, Abb55, Abb7, Abb44, Abb56, Abb93, Abb94
	double complex Abb17, Abb76, Abb81, Abb25, Abb40, Abb52, Abb95
	double complex Abb96, Abb18, Abb77, Abb82, Abb26, Abb19, Abb78
	double complex Abb83, Abb27, AbbSum305, AbbSum429, AbbSum439
	double complex AbbSum504, AbbSum477, AbbSum474, AbbSum495
	double complex AbbSum890, AbbSum870, AbbSum872, AbbSum635
	double complex AbbSum754, AbbSum752, AbbSum760, AbbSum756
	double complex AbbSum468, AbbSum856, AbbSum314, AbbSum983
	double complex AbbSum295, AbbSum287, AbbSum296, AbbSum299
	double complex AbbSum232, AbbSum738, AbbSum888, AbbSum694
	double complex AbbSum622, AbbSum676, AbbSum30, AbbSum20
	double complex AbbSum21, AbbSum971, AbbSum501, AbbSum309
	double complex AbbSum597, AbbSum317, AbbSum639, AbbSum264
	double complex AbbSum598, AbbSum248, AbbSum310, AbbSum313
	double complex AbbSum263, AbbSum307, AbbSum291, AbbSum308
	double complex AbbSum292, AbbSum430, AbbSum440, AbbSum306
	double complex AbbSum746, AbbSum507, AbbSum480, AbbSum476
	double complex AbbSum750, AbbSum1156, AbbSum1009, AbbSum941
	double complex AbbSum744, AbbSum742, AbbSum1160, AbbSum579
	double complex AbbSum301, AbbSum318, AbbSum311, AbbSum640
	double complex AbbSum624, AbbSum498, AbbSum891, AbbSum871
	double complex AbbSum873, AbbSum638, AbbSum755, AbbSum753
	double complex AbbSum761, AbbSum758, AbbSum471, AbbSum857
	double complex AbbSum316, AbbSum984, AbbSum705, AbbSum726
	double complex AbbSum223, AbbSum1032, AbbSum680, AbbSum690
	double complex AbbSum312, AbbSum1010, AbbSum315, AbbSum1157
	double complex AbbSum625, AbbSum942, AbbSum1161, AbbSum716
	double complex AbbSum105, AbbSum751, AbbSum743, AbbSum745
	double complex AbbSum691, AbbSum681, AbbSum725, AbbSum222
	double complex AbbSum302, AbbSum1031, AbbSum580, AbbSum747
	double complex AbbSum704, AbbSum740, AbbSum297, AbbSum289
	double complex AbbSum298, AbbSum300, AbbSum233, AbbSum739
	double complex AbbSum741, AbbSum889, AbbSum703, AbbSum623
	double complex AbbSum678, AbbSum31, AbbSum28, AbbSum29
	double complex AbbSum972, AbbSum503, AbbSum510, AbbSum979
	double complex AbbSum333, AbbSum632, AbbSum375, AbbSum985
	double complex AbbSum193, AbbSum641, AbbSum153, AbbSum858
	double complex AbbSum734, AbbSum58, AbbSum155, AbbSum874
	double complex AbbSum108, AbbSum1297, AbbSum137, AbbSum70
	double complex AbbSum736, AbbSum1170, AbbSum607, AbbSum143
	double complex AbbSum513, AbbSum978, AbbSum968, AbbSum499
	double complex AbbSum670, AbbSum630, AbbSum617, AbbSum606
	double complex AbbSum283, AbbSum402, AbbSum98, AbbSum347
	double complex AbbSum677, AbbSum135, AbbSum647, AbbSum508
	double complex AbbSum892, AbbSum552, AbbSum528, AbbSum151
	double complex AbbSum992, AbbSum908, AbbSum603, AbbSum208
	double complex AbbSum957, AbbSum145, AbbSum976, AbbSum966
	double complex AbbSum141, AbbSum131, AbbSum804, AbbSum619
	double complex AbbSum838, AbbSum472, AbbSum136, AbbSum896
	double complex AbbSum520, AbbSum481, AbbSum59, AbbSum405
	double complex AbbSum1024, AbbSum115, AbbSum441, AbbSum285
	double complex AbbSum133, AbbSum149, AbbSum1206, AbbSum73
	double complex AbbSum146, AbbSum159, AbbSum1107, AbbSum157
	double complex AbbSum590, AbbSum902, AbbSum447, AbbSum449
	double complex AbbSum280, AbbSum1005, AbbSum659, AbbSum1000
	double complex AbbSum654, AbbSum1181, AbbSum1006, AbbSum511
	double complex AbbSum492, AbbSum505, AbbSum982, AbbSum660
	double complex AbbSum334, AbbSum594, AbbSum636, AbbSum634
	double complex AbbSum380, AbbSum463, AbbSum478, AbbSum824
	double complex AbbSum986, AbbSum427, AbbSum1202, AbbSum436
	double complex AbbSum194, AbbSum428, AbbSum1203, AbbSum825
	double complex AbbSum642, AbbSum1083, AbbSum854, AbbSum154
	double complex AbbSum444, AbbSum859, AbbSum450, AbbSum735
	double complex AbbSum60, AbbSum855, AbbSum156, AbbSum913
	double complex AbbSum875, AbbSum869, AbbSum909, AbbSum993
	double complex AbbSum120, AbbSum1300, AbbSum879, AbbSum140
	double complex AbbSum1182, AbbSum457, AbbSum71, AbbSum923
	double complex AbbSum737, AbbSum1171, AbbSum610, AbbSum880
	double complex AbbSum144, AbbSum470, AbbSum977, AbbSum958
	double complex AbbSum631, AbbSum618, AbbSum1277, AbbSum489
	double complex AbbSum605, AbbSum648, AbbSum529, AbbSum1141
	double complex AbbSum558, AbbSum515, AbbSum629, AbbSum1038
	double complex AbbSum493, AbbSum1030, AbbSum981, AbbSum506
	double complex AbbSum970, AbbSum500, AbbSum502, AbbSum674
	double complex AbbSum702, AbbSum486, AbbSum497, AbbSum633
	double complex AbbSum612, AbbSum620, AbbSum609, AbbSum886
	double complex AbbSum534, AbbSum733, AbbSum284, AbbSum595
	double complex AbbSum401, AbbSum967, AbbSum408, AbbSum637
	double complex AbbSum102, AbbSum616, AbbSum460, AbbSum351
	double complex AbbSum679, AbbSum138, AbbSum650, AbbSum509
	double complex AbbSum893, AbbSum555, AbbSum531, AbbSum152
	double complex AbbSum996, AbbSum911, AbbSum608, AbbSum485
	double complex AbbSum209, AbbSum960, AbbSum975, AbbSum147
	double complex AbbSum1278, AbbSum604, AbbSum980, AbbSum969
	double complex AbbSum142, AbbSum496, AbbSum132, AbbSum1039
	double complex AbbSum464, AbbSum1029, AbbSum809, AbbSum621
	double complex AbbSum479, AbbSum841, AbbSum473, AbbSum475
	double complex AbbSum139, AbbSum887, AbbSum649, AbbSum530
	double complex AbbSum897, AbbSum956, AbbSum362, AbbSum965
	double complex AbbSum521, AbbSum792, AbbSum1040, AbbSum256
	double complex AbbSum432, AbbSum655, AbbSum482, AbbSum469
	double complex AbbSum279, AbbSum1021, AbbSum61, AbbSum409
	double complex AbbSum798, AbbSum1026, AbbSum1025, AbbSum127
	double complex AbbSum458, AbbSum697, AbbSum244, AbbSum442
	double complex AbbSum437, AbbSum286, AbbSum134, AbbSum793
	double complex AbbSum150, AbbSum1207, AbbSum74, AbbSum148
	double complex AbbSum160, AbbSum1108, AbbSum158, AbbSum1041
	double complex AbbSum258, AbbSum433, AbbSum592, AbbSum799
	double complex AbbSum1001, AbbSum868, AbbSum910, AbbSum994
	double complex AbbSum363, AbbSum903, AbbSum406, AbbSum455
	double complex AbbSum466, AbbSum451, AbbSum876, AbbSum72
	double complex AbbSum877, AbbSum452, AbbSum467, AbbSum456
	double complex AbbSum483, AbbSum293, AbbSum378, AbbSum259
	double complex AbbSum249, AbbSum407, AbbSum1162, AbbSum757
	double complex AbbSum831, AbbSum1249, AbbSum1013, AbbSum927
	double complex AbbSum303, AbbSum581, AbbSum369, AbbSum288
	double complex AbbSum214, AbbSum229, AbbSum100, AbbSum807
	double complex AbbSum748, AbbSum935, AbbSum1011, AbbSum1033
	double complex AbbSum692, AbbSum224, AbbSum717, AbbSum118
	double complex AbbSum79, AbbSum1158, AbbSum101, AbbSum1152
	double complex AbbSum572, AbbSum294, AbbSum382, AbbSum262
	double complex AbbSum250, AbbSum410, AbbSum1163, AbbSum759
	double complex AbbSum833, AbbSum1252, AbbSum1014, AbbSum928
	double complex AbbSum304, AbbSum582, AbbSum370, AbbSum290
	double complex AbbSum215, AbbSum231, AbbSum103, AbbSum811
	double complex AbbSum749, AbbSum938, AbbSum1012, AbbSum1034
	double complex AbbSum693, AbbSum225, AbbSum718, AbbSum130
	double complex AbbSum84, AbbSum1159, AbbSum104, AbbSum1155
	double complex AbbSum576, AbbSum1049, AbbSum1067, AbbSum446
	double complex AbbSum852, AbbSum1051, AbbSum1068, AbbSum448
	double complex AbbSum853, AbbSum491, AbbSum866, AbbSum657
	double complex AbbSum1003, AbbSum653, AbbSum999, AbbSum1063
	double complex AbbSum435, AbbSum164, AbbSum329, AbbSum419
	double complex AbbSum770, AbbSum818, AbbSum462, AbbSum884
	double complex AbbSum1198, AbbSum1200, AbbSum1065, AbbSum1059
	double complex AbbSum842, AbbSum593, AbbSum949, AbbSum844
	double complex AbbSum422, AbbSum669, AbbSum820, AbbSum425
	double complex AbbSum822, AbbSum1180, AbbSum658, AbbSum1004
	double complex AbbSum1201, AbbSum494, AbbSum867, AbbSum656
	double complex AbbSum1002, AbbSum1064, AbbSum438, AbbSum163
	double complex AbbSum426, AbbSum331, AbbSum420, AbbSum823
	double complex AbbSum771, AbbSum819, AbbSum465, AbbSum885
	double complex AbbSum1199, AbbSum1066, AbbSum1061, AbbSum843
	double complex AbbSum596, AbbSum950, AbbSum845, AbbSum424
	double complex AbbSum673, AbbSum821, AbbSum1183, AbbSum267
	double complex AbbSum255, AbbSum253, AbbSum234, AbbSum278
	double complex AbbSum226, AbbSum360, AbbSum836, AbbSum1057
	double complex AbbSum1073, AbbSum241, AbbSum216, AbbSum1053
	double complex AbbSum251, AbbSum1173, AbbSum1165, AbbSum585
	double complex AbbSum1097, AbbSum431, AbbSum372, AbbSum1037
	double complex AbbSum720, AbbSum682, AbbSum1036, AbbSum1027
	double complex AbbSum1048, AbbSum1046, AbbSum201, AbbSum274
	double complex AbbSum281, AbbSum218, AbbSum1164, AbbSum275
	double complex AbbSum261, AbbSum238, AbbSum1045, AbbSum282
	double complex AbbSum230, AbbSum277, AbbSum1058, AbbSum1074
	double complex AbbSum1174, AbbSum245, AbbSum1028, AbbSum219
	double complex AbbSum1056, AbbSum252, AbbSum260, AbbSum1047
	double complex AbbSum1100, AbbSum1035, AbbSum434, AbbSum371
	double complex AbbSum359, AbbSum562, AbbSum1042, AbbSum724
	double complex AbbSum837, AbbSum686, AbbSum1143, AbbSum1043
	double complex AbbSum272, AbbSum203, AbbSum221, AbbSum107
	double complex AbbSum119, AbbSum561, AbbSum1044, AbbSum586
	double complex AbbSum1079, AbbSum1275, AbbSum882, AbbSum1082
	double complex AbbSum1015, AbbSum1093, AbbSum862, AbbSum1255
	double complex AbbSum1101, AbbSum1089, AbbSum727, AbbSum668
	double complex AbbSum397, AbbSum790, AbbSum399, AbbSum796
	double complex AbbSum488, AbbSum365, AbbSum1313, AbbSum1239
	double complex AbbSum1289, AbbSum577, AbbSum939, AbbSum826
	double complex AbbSum846, AbbSum1184, AbbSum1188, AbbSum706
	double complex AbbSum391, AbbSum394, AbbSum788, AbbSum1019
	double complex AbbSum1241, AbbSum1291, AbbSum850, AbbSum443
	double complex AbbSum344, AbbSum1140, AbbSum557, AbbSum864
	double complex AbbSum663, AbbSum786, AbbSum337, AbbSum356
	double complex AbbSum353, AbbSum774, AbbSum1230, AbbSum645
	double complex AbbSum990, AbbSum1192, AbbSum1069, AbbSum1119
	double complex AbbSum484, AbbSum533, AbbSum611, AbbSum961
	double complex AbbSum878, AbbSum912, AbbSum526, AbbSum906
	double complex AbbSum1111, AbbSum1305, AbbSum323, AbbSum764
	double complex AbbSum413, AbbSum813, AbbSum459, AbbSum1130
	double complex AbbSum548, AbbSum943, AbbSum1095, AbbSum1253
	double complex AbbSum211, AbbSum1077, AbbSum1228, AbbSum973
	double complex AbbSum627, AbbSum1267, AbbSum1214, AbbSum227
	double complex AbbSum1301, AbbSum1260, AbbSum922, AbbSum628
	double complex AbbSum919, AbbSum1233, AbbSum1276, AbbSum553
	double complex AbbSum925, AbbSum1259, AbbSum1294, AbbSum1295
	double complex AbbSum1309, AbbSum954, AbbSum601, AbbSum929
	double complex AbbSum1080, AbbSum1209, AbbSum883, AbbSum1243
	double complex AbbSum1232, AbbSum99, AbbSum930, AbbSum1280
	double complex AbbSum944, AbbSum1084, AbbSum1016, AbbSum1094
	double complex AbbSum863, AbbSum1256, AbbSum847, AbbSum1189
	double complex AbbSum1185, AbbSum1104, AbbSum1092, AbbSum398
	double complex AbbSum791, AbbSum732, AbbSum672, AbbSum324
	double complex AbbSum765, AbbSum414, AbbSum814, AbbSum366
	double complex AbbSum490, AbbSum1017, AbbSum1145, AbbSum780
	double complex AbbSum964, AbbSum614, AbbSum97, AbbSum926
	double complex AbbSum615, AbbSum963, AbbSum565, AbbSum1144
	double complex AbbSum566, AbbSum1314, AbbSum1240, AbbSum1290
	double complex AbbSum827, AbbSum800, AbbSum386, AbbSum779
	double complex AbbSum955, AbbSum602, AbbSum1237, AbbSum345
	double complex AbbSum387, AbbSum578, AbbSum940, AbbSum1310
	double complex AbbSum709, AbbSum392, AbbSum396, AbbSum789
	double complex AbbSum400, AbbSum695, AbbSum918, AbbSum1226
	double complex AbbSum1020, AbbSum1242, AbbSum1292, AbbSum851
	double complex AbbSum445, AbbSum1142, AbbSum560, AbbSum1131
	double complex AbbSum865, AbbSum665, AbbSum787, AbbSum338
	double complex AbbSum358, AbbSum354, AbbSum775, AbbSum1231
	double complex AbbSum797, AbbSum1193, AbbSum1072, AbbSum1121
	double complex AbbSum487, AbbSum536, AbbSum613, AbbSum962
	double complex AbbSum881, AbbSum914, AbbSum1308, AbbSum461
	double complex AbbSum719, AbbSum721, AbbSum675, AbbSum1018
	double complex AbbSum1244, AbbSum801, AbbSum1281, AbbSum1096
	double complex AbbSum1254, AbbSum213, AbbSum1078, AbbSum1229
	double complex AbbSum1112, AbbSum228, AbbSum1270, AbbSum696
	double complex AbbSum1302, AbbSum1221, AbbSum924, AbbSum646
	double complex AbbSum991, AbbSum974, AbbSum527, AbbSum907
	double complex AbbSum1271, AbbSum1303, AbbSum453, AbbSum556
	double complex AbbSum1265, AbbSum860, AbbSum177, AbbSum522
	double complex AbbSum544, AbbSum834, AbbSum516, AbbSum643
	double complex AbbSum355, AbbSum523, AbbSum540, AbbSum651
	double complex AbbSum532, AbbSum421, AbbSum393, AbbSum894
	double complex AbbSum898, AbbSum514, AbbSum995, AbbSum349
	double complex AbbSum904, AbbSum997, AbbSum987, AbbSum784
	double complex AbbSum953, AbbSum998, AbbSum1149, AbbSum817
	double complex AbbSum1129, AbbSum1273, AbbSum1304, AbbSum698
	double complex AbbSum341, AbbSum699, AbbSum454, AbbSum795
	double complex AbbSum1137, AbbSum1128, AbbSum1117, AbbSum895
	double complex AbbSum559, AbbSum599, AbbSum584, AbbSum952
	double complex AbbSum46, AbbSum1126, AbbSum390, AbbSum861
	double complex AbbSum1116, AbbSum1138, AbbSum1135, AbbSum1136
	double complex AbbSum700, AbbSum1178, AbbSum179, AbbSum835
	double complex AbbSum1220, AbbSum626, AbbSum701, AbbSum959
	double complex AbbSum1213, AbbSum644, AbbSum512, AbbSum517
	double complex AbbSum542, AbbSum1150, AbbSum1286, AbbSum357
	double complex AbbSum583, AbbSum525, AbbSum1299, AbbSum541
	double complex AbbSum794, AbbSum535, AbbSum778, AbbSum266
	double complex AbbSum423, AbbSum812, AbbSum543, AbbSum205
	double complex AbbSum403, AbbSum343, AbbSum524, AbbSum395
	double complex AbbSum411, AbbSum383, AbbSum339, AbbSum321
	double complex AbbSum385, AbbSum34, AbbSum1258, AbbSum545
	double complex AbbSum1279, AbbSum546, AbbSum989, AbbSum652
	double complex AbbSum547, AbbSum899, AbbSum951, AbbSum1109
	double complex AbbSum106, AbbSum1208, AbbSum204, AbbSum322
	double complex AbbSum1081, AbbSum1225, AbbSum600, AbbSum1124
	double complex AbbSum537, AbbSum265, AbbSum384, AbbSum1257
	double complex AbbSum1110, AbbSum915, AbbSum1266, AbbSum1172
	double complex AbbSum1293, AbbSum412, AbbSum905, AbbSum404
	double complex AbbSum988, AbbSum1125, AbbSum1105, AbbSum538
	double complex AbbSum934, AbbSum1272, AbbSum1216, AbbSum340
	double complex AbbSum666, AbbSum210, AbbSum1306, AbbSum1268
	double complex AbbSum373, AbbSum1204, AbbSum916, AbbSum1147
	double complex AbbSum66, AbbSum330, AbbSum217, AbbSum1177
	double complex AbbSum67, AbbSum1211, AbbSum1248, AbbSum776
	double complex AbbSum206, AbbSum920, AbbSum254, AbbSum803
	double complex AbbSum235, AbbSum236, AbbSum1007, AbbSum708
	double complex AbbSum62, AbbSum173, AbbSum171, AbbSum161
	double complex AbbSum41, AbbSum169, AbbSum1222, AbbSum1245
	double complex AbbSum174, AbbSum165, AbbSum167, AbbSum111
	double complex AbbSum268, AbbSum197, AbbSum195, AbbSum829
	double complex AbbSum848, AbbSum335, AbbSum661, AbbSum326
	double complex AbbSum1022, AbbSum518, AbbSum712, AbbSum713
	double complex AbbSum109, AbbSum242, AbbSum1122, AbbSum243
	double complex AbbSum319, AbbSum374, AbbSum110, AbbSum199
	double complex AbbSum805, AbbSum802, AbbSum1166, AbbSum587
	double complex AbbSum828, AbbSum1186, AbbSum1190, AbbSum1085
	double complex AbbSum1247, AbbSum1087, AbbSum729, AbbSum1102
	double complex AbbSum563, AbbSum1148, AbbSum945, AbbSum1311
	double complex AbbSum1223, AbbSum685, AbbSum782, AbbSum570
	double complex AbbSum1261, AbbSum571, AbbSum1098, AbbSum946
	double complex AbbSum932, AbbSum1167, AbbSum549, AbbSum1284
	double complex AbbSum1235, AbbSum1234, AbbSum1283, AbbSum568
	double complex AbbSum551, AbbSum931, AbbSum588, AbbSum114
	double complex AbbSum1146, AbbSum684, AbbSum1282, AbbSum112
	double complex AbbSum417, AbbSum45, AbbSum768, AbbSum113
	double complex AbbSum63, AbbSum772, AbbSum1050, AbbSum1060
	double complex AbbSum900, AbbSum189, AbbSum187, AbbSum350
	double complex AbbSum376, AbbSum707, AbbSum683, AbbSum178
	double complex AbbSum762, AbbSum361, AbbSum185, AbbSum190
	double complex AbbSum181, AbbSum183, AbbSum271, AbbSum367
	double complex AbbSum270, AbbSum1133, AbbSum1194, AbbSum1113
	double complex AbbSum722, AbbSum1132, AbbSum567, AbbSum1218
	double complex AbbSum1127, AbbSum947, AbbSum921, AbbSum564
	double complex AbbSum1246, AbbSum1106, AbbSum539, AbbSum1312
	double complex AbbSum1274, AbbSum1217, AbbSum342, AbbSum1269
	double complex AbbSum1307, AbbSum667, AbbSum212, AbbSum806
	double complex AbbSum377, AbbSum1205, AbbSum917, AbbSum1154
	double complex AbbSum68, AbbSum332, AbbSum589, AbbSum1224
	double complex AbbSum220, AbbSum1179, AbbSum69, AbbSum325
	double complex AbbSum346, AbbSum1215, AbbSum1251, AbbSum777
	double complex AbbSum207, AbbSum1120, AbbSum239, AbbSum240
	double complex AbbSum1008, AbbSum711, AbbSum64, AbbSum175
	double complex AbbSum172, AbbSum162, AbbSum53, AbbSum170
	double complex AbbSum1227, AbbSum1250, AbbSum176, AbbSum166
	double complex AbbSum168, AbbSum123, AbbSum276, AbbSum198
	double complex AbbSum196, AbbSum832, AbbSum849, AbbSum550
	double complex AbbSum336, AbbSum662, AbbSum328, AbbSum1023
	double complex AbbSum519, AbbSum714, AbbSum715, AbbSum121
	double complex AbbSum246, AbbSum1123, AbbSum247, AbbSum320
	double complex AbbSum379, AbbSum122, AbbSum202, AbbSum810
	double complex AbbSum808, AbbSum1169, AbbSum1151, AbbSum591
	double complex AbbSum415, AbbSum388, AbbSum1196, AbbSum1115
	double complex AbbSum840, AbbSum767, AbbSum1075, AbbSum1070
	double complex AbbSum1090, AbbSum671, AbbSum1071, AbbSum664
	double complex AbbSum839, AbbSum766, AbbSum1175, AbbSum1195
	double complex AbbSum1114, AbbSum815, AbbSum781, AbbSum689
	double complex AbbSum785, AbbSum574, AbbSum1264, AbbSum575
	double complex AbbSum368, AbbSum1176, AbbSum816, AbbSum783
	double complex AbbSum1187, AbbSum948, AbbSum937, AbbSum1168
	double complex AbbSum1191, AbbSum1238, AbbSum1288, AbbSum1262
	double complex AbbSum830, AbbSum1285, AbbSum573, AbbSum554
	double complex AbbSum936, AbbSum1296, AbbSum1086, AbbSum126
	double complex AbbSum269, AbbSum1099, AbbSum1088, AbbSum1103
	double complex AbbSum1153, AbbSum688, AbbSum1287, AbbSum1236
	double complex AbbSum124, AbbSum418, AbbSum57, AbbSum769
	double complex AbbSum125, AbbSum273, AbbSum731, AbbSum728
	double complex AbbSum730, AbbSum1212, AbbSum65, AbbSum773
	double complex AbbSum1052, AbbSum1062, AbbSum901, AbbSum191
	double complex AbbSum188, AbbSum352, AbbSum381, AbbSum710
	double complex AbbSum687, AbbSum180, AbbSum763, AbbSum364
	double complex AbbSum186, AbbSum192, AbbSum182, AbbSum184
	double complex AbbSum1210, AbbSum1076, AbbSum200, AbbSum1054
	double complex AbbSum1091, AbbSum237, AbbSum1055, AbbSum723
	double complex AbbSum257, AbbSum1197, AbbSum1118, AbbSum389
	double complex AbbSum416, AbbSum348, AbbSum327, AbbSum933
	double complex AbbSum569, AbbSum1139, AbbSum1298, AbbSum1134
	double complex AbbSum1219, AbbSum1263
	common /gzabbrev/ F3, F6, F35, F37, F42, F47, F49, F54, F32
	common /gzabbrev/ F85, F86, F33, F87, F88, F36, F48, Pair4
	common /gzabbrev/ Pair8, Pair11, Pair9, Pair10, Eps12, Eps13
	common /gzabbrev/ Abb14, Abb15, Abb116, Abb117, Abb128, Abb129
	common /gzabbrev/ Abb22, Abb23, Abb38, Abb50, Abb89, Abb90
	common /gzabbrev/ Abb39, Abb51, Abb91, Abb92, Abb16, Abb75
	common /gzabbrev/ Abb80, Abb24, Abb5, Abb43, Abb55, Abb7
	common /gzabbrev/ Abb44, Abb56, Abb93, Abb94, Abb17, Abb76
	common /gzabbrev/ Abb81, Abb25, Abb40, Abb52, Abb95, Abb96
	common /gzabbrev/ Abb18, Abb77, Abb82, Abb26, Abb19, Abb78
	common /gzabbrev/ Abb83, Abb27, AbbSum305, AbbSum429
	common /gzabbrev/ AbbSum439, AbbSum504, AbbSum477, AbbSum474
	common /gzabbrev/ AbbSum495, AbbSum890, AbbSum870, AbbSum872
	common /gzabbrev/ AbbSum635, AbbSum754, AbbSum752, AbbSum760
	common /gzabbrev/ AbbSum756, AbbSum468, AbbSum856, AbbSum314
	common /gzabbrev/ AbbSum983, AbbSum295, AbbSum287, AbbSum296
	common /gzabbrev/ AbbSum299, AbbSum232, AbbSum738, AbbSum888
	common /gzabbrev/ AbbSum694, AbbSum622, AbbSum676, AbbSum30
	common /gzabbrev/ AbbSum20, AbbSum21, AbbSum971, AbbSum501
	common /gzabbrev/ AbbSum309, AbbSum597, AbbSum317, AbbSum639
	common /gzabbrev/ AbbSum264, AbbSum598, AbbSum248, AbbSum310
	common /gzabbrev/ AbbSum313, AbbSum263, AbbSum307, AbbSum291
	common /gzabbrev/ AbbSum308, AbbSum292, AbbSum430, AbbSum440
	common /gzabbrev/ AbbSum306, AbbSum746, AbbSum507, AbbSum480
	common /gzabbrev/ AbbSum476, AbbSum750, AbbSum1156, AbbSum1009
	common /gzabbrev/ AbbSum941, AbbSum744, AbbSum742, AbbSum1160
	common /gzabbrev/ AbbSum579, AbbSum301, AbbSum318, AbbSum311
	common /gzabbrev/ AbbSum640, AbbSum624, AbbSum498, AbbSum891
	common /gzabbrev/ AbbSum871, AbbSum873, AbbSum638, AbbSum755
	common /gzabbrev/ AbbSum753, AbbSum761, AbbSum758, AbbSum471
	common /gzabbrev/ AbbSum857, AbbSum316, AbbSum984, AbbSum705
	common /gzabbrev/ AbbSum726, AbbSum223, AbbSum1032, AbbSum680
	common /gzabbrev/ AbbSum690, AbbSum312, AbbSum1010, AbbSum315
	common /gzabbrev/ AbbSum1157, AbbSum625, AbbSum942, AbbSum1161
	common /gzabbrev/ AbbSum716, AbbSum105, AbbSum751, AbbSum743
	common /gzabbrev/ AbbSum745, AbbSum691, AbbSum681, AbbSum725
	common /gzabbrev/ AbbSum222, AbbSum302, AbbSum1031, AbbSum580
	common /gzabbrev/ AbbSum747, AbbSum704, AbbSum740, AbbSum297
	common /gzabbrev/ AbbSum289, AbbSum298, AbbSum300, AbbSum233
	common /gzabbrev/ AbbSum739, AbbSum741, AbbSum889, AbbSum703
	common /gzabbrev/ AbbSum623, AbbSum678, AbbSum31, AbbSum28
	common /gzabbrev/ AbbSum29, AbbSum972, AbbSum503, AbbSum510
	common /gzabbrev/ AbbSum979, AbbSum333, AbbSum632, AbbSum375
	common /gzabbrev/ AbbSum985, AbbSum193, AbbSum641, AbbSum153
	common /gzabbrev/ AbbSum858, AbbSum734, AbbSum58, AbbSum155
	common /gzabbrev/ AbbSum874, AbbSum108, AbbSum1297, AbbSum137
	common /gzabbrev/ AbbSum70, AbbSum736, AbbSum1170, AbbSum607
	common /gzabbrev/ AbbSum143, AbbSum513, AbbSum978, AbbSum968
	common /gzabbrev/ AbbSum499, AbbSum670, AbbSum630, AbbSum617
	common /gzabbrev/ AbbSum606, AbbSum283, AbbSum402, AbbSum98
	common /gzabbrev/ AbbSum347, AbbSum677, AbbSum135, AbbSum647
	common /gzabbrev/ AbbSum508, AbbSum892, AbbSum552, AbbSum528
	common /gzabbrev/ AbbSum151, AbbSum992, AbbSum908, AbbSum603
	common /gzabbrev/ AbbSum208, AbbSum957, AbbSum145, AbbSum976
	common /gzabbrev/ AbbSum966, AbbSum141, AbbSum131, AbbSum804
	common /gzabbrev/ AbbSum619, AbbSum838, AbbSum472, AbbSum136
	common /gzabbrev/ AbbSum896, AbbSum520, AbbSum481, AbbSum59
	common /gzabbrev/ AbbSum405, AbbSum1024, AbbSum115, AbbSum441
	common /gzabbrev/ AbbSum285, AbbSum133, AbbSum149, AbbSum1206
	common /gzabbrev/ AbbSum73, AbbSum146, AbbSum159, AbbSum1107
	common /gzabbrev/ AbbSum157, AbbSum590, AbbSum902, AbbSum447
	common /gzabbrev/ AbbSum449, AbbSum280, AbbSum1005, AbbSum659
	common /gzabbrev/ AbbSum1000, AbbSum654, AbbSum1181
	common /gzabbrev/ AbbSum1006, AbbSum511, AbbSum492, AbbSum505
	common /gzabbrev/ AbbSum982, AbbSum660, AbbSum334, AbbSum594
	common /gzabbrev/ AbbSum636, AbbSum634, AbbSum380, AbbSum463
	common /gzabbrev/ AbbSum478, AbbSum824, AbbSum986, AbbSum427
	common /gzabbrev/ AbbSum1202, AbbSum436, AbbSum194, AbbSum428
	common /gzabbrev/ AbbSum1203, AbbSum825, AbbSum642, AbbSum1083
	common /gzabbrev/ AbbSum854, AbbSum154, AbbSum444, AbbSum859
	common /gzabbrev/ AbbSum450, AbbSum735, AbbSum60, AbbSum855
	common /gzabbrev/ AbbSum156, AbbSum913, AbbSum875, AbbSum869
	common /gzabbrev/ AbbSum909, AbbSum993, AbbSum120, AbbSum1300
	common /gzabbrev/ AbbSum879, AbbSum140, AbbSum1182, AbbSum457
	common /gzabbrev/ AbbSum71, AbbSum923, AbbSum737, AbbSum1171
	common /gzabbrev/ AbbSum610, AbbSum880, AbbSum144, AbbSum470
	common /gzabbrev/ AbbSum977, AbbSum958, AbbSum631, AbbSum618
	common /gzabbrev/ AbbSum1277, AbbSum489, AbbSum605, AbbSum648
	common /gzabbrev/ AbbSum529, AbbSum1141, AbbSum558, AbbSum515
	common /gzabbrev/ AbbSum629, AbbSum1038, AbbSum493, AbbSum1030
	common /gzabbrev/ AbbSum981, AbbSum506, AbbSum970, AbbSum500
	common /gzabbrev/ AbbSum502, AbbSum674, AbbSum702, AbbSum486
	common /gzabbrev/ AbbSum497, AbbSum633, AbbSum612, AbbSum620
	common /gzabbrev/ AbbSum609, AbbSum886, AbbSum534, AbbSum733
	common /gzabbrev/ AbbSum284, AbbSum595, AbbSum401, AbbSum967
	common /gzabbrev/ AbbSum408, AbbSum637, AbbSum102, AbbSum616
	common /gzabbrev/ AbbSum460, AbbSum351, AbbSum679, AbbSum138
	common /gzabbrev/ AbbSum650, AbbSum509, AbbSum893, AbbSum555
	common /gzabbrev/ AbbSum531, AbbSum152, AbbSum996, AbbSum911
	common /gzabbrev/ AbbSum608, AbbSum485, AbbSum209, AbbSum960
	common /gzabbrev/ AbbSum975, AbbSum147, AbbSum1278, AbbSum604
	common /gzabbrev/ AbbSum980, AbbSum969, AbbSum142, AbbSum496
	common /gzabbrev/ AbbSum132, AbbSum1039, AbbSum464, AbbSum1029
	common /gzabbrev/ AbbSum809, AbbSum621, AbbSum479, AbbSum841
	common /gzabbrev/ AbbSum473, AbbSum475, AbbSum139, AbbSum887
	common /gzabbrev/ AbbSum649, AbbSum530, AbbSum897, AbbSum956
	common /gzabbrev/ AbbSum362, AbbSum965, AbbSum521, AbbSum792
	common /gzabbrev/ AbbSum1040, AbbSum256, AbbSum432, AbbSum655
	common /gzabbrev/ AbbSum482, AbbSum469, AbbSum279, AbbSum1021
	common /gzabbrev/ AbbSum61, AbbSum409, AbbSum798, AbbSum1026
	common /gzabbrev/ AbbSum1025, AbbSum127, AbbSum458, AbbSum697
	common /gzabbrev/ AbbSum244, AbbSum442, AbbSum437, AbbSum286
	common /gzabbrev/ AbbSum134, AbbSum793, AbbSum150, AbbSum1207
	common /gzabbrev/ AbbSum74, AbbSum148, AbbSum160, AbbSum1108
	common /gzabbrev/ AbbSum158, AbbSum1041, AbbSum258, AbbSum433
	common /gzabbrev/ AbbSum592, AbbSum799, AbbSum1001, AbbSum868
	common /gzabbrev/ AbbSum910, AbbSum994, AbbSum363, AbbSum903
	common /gzabbrev/ AbbSum406, AbbSum455, AbbSum466, AbbSum451
	common /gzabbrev/ AbbSum876, AbbSum72, AbbSum877, AbbSum452
	common /gzabbrev/ AbbSum467, AbbSum456, AbbSum483, AbbSum293
	common /gzabbrev/ AbbSum378, AbbSum259, AbbSum249, AbbSum407
	common /gzabbrev/ AbbSum1162, AbbSum757, AbbSum831, AbbSum1249
	common /gzabbrev/ AbbSum1013, AbbSum927, AbbSum303, AbbSum581
	common /gzabbrev/ AbbSum369, AbbSum288, AbbSum214, AbbSum229
	common /gzabbrev/ AbbSum100, AbbSum807, AbbSum748, AbbSum935
	common /gzabbrev/ AbbSum1011, AbbSum1033, AbbSum692, AbbSum224
	common /gzabbrev/ AbbSum717, AbbSum118, AbbSum79, AbbSum1158
	common /gzabbrev/ AbbSum101, AbbSum1152, AbbSum572, AbbSum294
	common /gzabbrev/ AbbSum382, AbbSum262, AbbSum250, AbbSum410
	common /gzabbrev/ AbbSum1163, AbbSum759, AbbSum833, AbbSum1252
	common /gzabbrev/ AbbSum1014, AbbSum928, AbbSum304, AbbSum582
	common /gzabbrev/ AbbSum370, AbbSum290, AbbSum215, AbbSum231
	common /gzabbrev/ AbbSum103, AbbSum811, AbbSum749, AbbSum938
	common /gzabbrev/ AbbSum1012, AbbSum1034, AbbSum693, AbbSum225
	common /gzabbrev/ AbbSum718, AbbSum130, AbbSum84, AbbSum1159
	common /gzabbrev/ AbbSum104, AbbSum1155, AbbSum576, AbbSum1049
	common /gzabbrev/ AbbSum1067, AbbSum446, AbbSum852, AbbSum1051
	common /gzabbrev/ AbbSum1068, AbbSum448, AbbSum853, AbbSum491
	common /gzabbrev/ AbbSum866, AbbSum657, AbbSum1003, AbbSum653
	common /gzabbrev/ AbbSum999, AbbSum1063, AbbSum435, AbbSum164
	common /gzabbrev/ AbbSum329, AbbSum419, AbbSum770, AbbSum818
	common /gzabbrev/ AbbSum462, AbbSum884, AbbSum1198, AbbSum1200
	common /gzabbrev/ AbbSum1065, AbbSum1059, AbbSum842, AbbSum593
	common /gzabbrev/ AbbSum949, AbbSum844, AbbSum422, AbbSum669
	common /gzabbrev/ AbbSum820, AbbSum425, AbbSum822, AbbSum1180
	common /gzabbrev/ AbbSum658, AbbSum1004, AbbSum1201, AbbSum494
	common /gzabbrev/ AbbSum867, AbbSum656, AbbSum1002, AbbSum1064
	common /gzabbrev/ AbbSum438, AbbSum163, AbbSum426, AbbSum331
	common /gzabbrev/ AbbSum420, AbbSum823, AbbSum771, AbbSum819
	common /gzabbrev/ AbbSum465, AbbSum885, AbbSum1199, AbbSum1066
	common /gzabbrev/ AbbSum1061, AbbSum843, AbbSum596, AbbSum950
	common /gzabbrev/ AbbSum845, AbbSum424, AbbSum673, AbbSum821
	common /gzabbrev/ AbbSum1183, AbbSum267, AbbSum255, AbbSum253
	common /gzabbrev/ AbbSum234, AbbSum278, AbbSum226, AbbSum360
	common /gzabbrev/ AbbSum836, AbbSum1057, AbbSum1073, AbbSum241
	common /gzabbrev/ AbbSum216, AbbSum1053, AbbSum251, AbbSum1173
	common /gzabbrev/ AbbSum1165, AbbSum585, AbbSum1097, AbbSum431
	common /gzabbrev/ AbbSum372, AbbSum1037, AbbSum720, AbbSum682
	common /gzabbrev/ AbbSum1036, AbbSum1027, AbbSum1048
	common /gzabbrev/ AbbSum1046, AbbSum201, AbbSum274, AbbSum281
	common /gzabbrev/ AbbSum218, AbbSum1164, AbbSum275, AbbSum261
	common /gzabbrev/ AbbSum238, AbbSum1045, AbbSum282, AbbSum230
	common /gzabbrev/ AbbSum277, AbbSum1058, AbbSum1074
	common /gzabbrev/ AbbSum1174, AbbSum245, AbbSum1028, AbbSum219
	common /gzabbrev/ AbbSum1056, AbbSum252, AbbSum260, AbbSum1047
	common /gzabbrev/ AbbSum1100, AbbSum1035, AbbSum434, AbbSum371
	common /gzabbrev/ AbbSum359, AbbSum562, AbbSum1042, AbbSum724
	common /gzabbrev/ AbbSum837, AbbSum686, AbbSum1143, AbbSum1043
	common /gzabbrev/ AbbSum272, AbbSum203, AbbSum221, AbbSum107
	common /gzabbrev/ AbbSum119, AbbSum561, AbbSum1044, AbbSum586
	common /gzabbrev/ AbbSum1079, AbbSum1275, AbbSum882
	common /gzabbrev/ AbbSum1082, AbbSum1015, AbbSum1093
	common /gzabbrev/ AbbSum862, AbbSum1255, AbbSum1101
	common /gzabbrev/ AbbSum1089, AbbSum727, AbbSum668, AbbSum397
	common /gzabbrev/ AbbSum790, AbbSum399, AbbSum796, AbbSum488
	common /gzabbrev/ AbbSum365, AbbSum1313, AbbSum1239
	common /gzabbrev/ AbbSum1289, AbbSum577, AbbSum939, AbbSum826
	common /gzabbrev/ AbbSum846, AbbSum1184, AbbSum1188, AbbSum706
	common /gzabbrev/ AbbSum391, AbbSum394, AbbSum788, AbbSum1019
	common /gzabbrev/ AbbSum1241, AbbSum1291, AbbSum850, AbbSum443
	common /gzabbrev/ AbbSum344, AbbSum1140, AbbSum557, AbbSum864
	common /gzabbrev/ AbbSum663, AbbSum786, AbbSum337, AbbSum356
	common /gzabbrev/ AbbSum353, AbbSum774, AbbSum1230, AbbSum645
	common /gzabbrev/ AbbSum990, AbbSum1192, AbbSum1069
	common /gzabbrev/ AbbSum1119, AbbSum484, AbbSum533, AbbSum611
	common /gzabbrev/ AbbSum961, AbbSum878, AbbSum912, AbbSum526
	common /gzabbrev/ AbbSum906, AbbSum1111, AbbSum1305, AbbSum323
	common /gzabbrev/ AbbSum764, AbbSum413, AbbSum813, AbbSum459
	common /gzabbrev/ AbbSum1130, AbbSum548, AbbSum943, AbbSum1095
	common /gzabbrev/ AbbSum1253, AbbSum211, AbbSum1077
	common /gzabbrev/ AbbSum1228, AbbSum973, AbbSum627, AbbSum1267
	common /gzabbrev/ AbbSum1214, AbbSum227, AbbSum1301
	common /gzabbrev/ AbbSum1260, AbbSum922, AbbSum628, AbbSum919
	common /gzabbrev/ AbbSum1233, AbbSum1276, AbbSum553, AbbSum925
	common /gzabbrev/ AbbSum1259, AbbSum1294, AbbSum1295
	common /gzabbrev/ AbbSum1309, AbbSum954, AbbSum601, AbbSum929
	common /gzabbrev/ AbbSum1080, AbbSum1209, AbbSum883
	common /gzabbrev/ AbbSum1243, AbbSum1232, AbbSum99, AbbSum930
	common /gzabbrev/ AbbSum1280, AbbSum944, AbbSum1084
	common /gzabbrev/ AbbSum1016, AbbSum1094, AbbSum863
	common /gzabbrev/ AbbSum1256, AbbSum847, AbbSum1189
	common /gzabbrev/ AbbSum1185, AbbSum1104, AbbSum1092
	common /gzabbrev/ AbbSum398, AbbSum791, AbbSum732, AbbSum672
	common /gzabbrev/ AbbSum324, AbbSum765, AbbSum414, AbbSum814
	common /gzabbrev/ AbbSum366, AbbSum490, AbbSum1017, AbbSum1145
	common /gzabbrev/ AbbSum780, AbbSum964, AbbSum614, AbbSum97
	common /gzabbrev/ AbbSum926, AbbSum615, AbbSum963, AbbSum565
	common /gzabbrev/ AbbSum1144, AbbSum566, AbbSum1314
	common /gzabbrev/ AbbSum1240, AbbSum1290, AbbSum827, AbbSum800
	common /gzabbrev/ AbbSum386, AbbSum779, AbbSum955, AbbSum602
	common /gzabbrev/ AbbSum1237, AbbSum345, AbbSum387, AbbSum578
	common /gzabbrev/ AbbSum940, AbbSum1310, AbbSum709, AbbSum392
	common /gzabbrev/ AbbSum396, AbbSum789, AbbSum400, AbbSum695
	common /gzabbrev/ AbbSum918, AbbSum1226, AbbSum1020
	common /gzabbrev/ AbbSum1242, AbbSum1292, AbbSum851, AbbSum445
	common /gzabbrev/ AbbSum1142, AbbSum560, AbbSum1131, AbbSum865
	common /gzabbrev/ AbbSum665, AbbSum787, AbbSum338, AbbSum358
	common /gzabbrev/ AbbSum354, AbbSum775, AbbSum1231, AbbSum797
	common /gzabbrev/ AbbSum1193, AbbSum1072, AbbSum1121
	common /gzabbrev/ AbbSum487, AbbSum536, AbbSum613, AbbSum962
	common /gzabbrev/ AbbSum881, AbbSum914, AbbSum1308, AbbSum461
	common /gzabbrev/ AbbSum719, AbbSum721, AbbSum675, AbbSum1018
	common /gzabbrev/ AbbSum1244, AbbSum801, AbbSum1281
	common /gzabbrev/ AbbSum1096, AbbSum1254, AbbSum213
	common /gzabbrev/ AbbSum1078, AbbSum1229, AbbSum1112
	common /gzabbrev/ AbbSum228, AbbSum1270, AbbSum696, AbbSum1302
	common /gzabbrev/ AbbSum1221, AbbSum924, AbbSum646, AbbSum991
	common /gzabbrev/ AbbSum974, AbbSum527, AbbSum907, AbbSum1271
	common /gzabbrev/ AbbSum1303, AbbSum453, AbbSum556, AbbSum1265
	common /gzabbrev/ AbbSum860, AbbSum177, AbbSum522, AbbSum544
	common /gzabbrev/ AbbSum834, AbbSum516, AbbSum643, AbbSum355
	common /gzabbrev/ AbbSum523, AbbSum540, AbbSum651, AbbSum532
	common /gzabbrev/ AbbSum421, AbbSum393, AbbSum894, AbbSum898
	common /gzabbrev/ AbbSum514, AbbSum995, AbbSum349, AbbSum904
	common /gzabbrev/ AbbSum997, AbbSum987, AbbSum784, AbbSum953
	common /gzabbrev/ AbbSum998, AbbSum1149, AbbSum817, AbbSum1129
	common /gzabbrev/ AbbSum1273, AbbSum1304, AbbSum698, AbbSum341
	common /gzabbrev/ AbbSum699, AbbSum454, AbbSum795, AbbSum1137
	common /gzabbrev/ AbbSum1128, AbbSum1117, AbbSum895, AbbSum559
	common /gzabbrev/ AbbSum599, AbbSum584, AbbSum952, AbbSum46
	common /gzabbrev/ AbbSum1126, AbbSum390, AbbSum861, AbbSum1116
	common /gzabbrev/ AbbSum1138, AbbSum1135, AbbSum1136
	common /gzabbrev/ AbbSum700, AbbSum1178, AbbSum179, AbbSum835
	common /gzabbrev/ AbbSum1220, AbbSum626, AbbSum701, AbbSum959
	common /gzabbrev/ AbbSum1213, AbbSum644, AbbSum512, AbbSum517
	common /gzabbrev/ AbbSum542, AbbSum1150, AbbSum1286, AbbSum357
	common /gzabbrev/ AbbSum583, AbbSum525, AbbSum1299, AbbSum541
	common /gzabbrev/ AbbSum794, AbbSum535, AbbSum778, AbbSum266
	common /gzabbrev/ AbbSum423, AbbSum812, AbbSum543, AbbSum205
	common /gzabbrev/ AbbSum403, AbbSum343, AbbSum524, AbbSum395
	common /gzabbrev/ AbbSum411, AbbSum383, AbbSum339, AbbSum321
	common /gzabbrev/ AbbSum385, AbbSum34, AbbSum1258, AbbSum545
	common /gzabbrev/ AbbSum1279, AbbSum546, AbbSum989, AbbSum652
	common /gzabbrev/ AbbSum547, AbbSum899, AbbSum951, AbbSum1109
	common /gzabbrev/ AbbSum106, AbbSum1208, AbbSum204, AbbSum322
	common /gzabbrev/ AbbSum1081, AbbSum1225, AbbSum600
	common /gzabbrev/ AbbSum1124, AbbSum537, AbbSum265, AbbSum384
	common /gzabbrev/ AbbSum1257, AbbSum1110, AbbSum915
	common /gzabbrev/ AbbSum1266, AbbSum1172, AbbSum1293
	common /gzabbrev/ AbbSum412, AbbSum905, AbbSum404, AbbSum988
	common /gzabbrev/ AbbSum1125, AbbSum1105, AbbSum538, AbbSum934
	common /gzabbrev/ AbbSum1272, AbbSum1216, AbbSum340, AbbSum666
	common /gzabbrev/ AbbSum210, AbbSum1306, AbbSum1268, AbbSum373
	common /gzabbrev/ AbbSum1204, AbbSum916, AbbSum1147, AbbSum66
	common /gzabbrev/ AbbSum330, AbbSum217, AbbSum1177, AbbSum67
	common /gzabbrev/ AbbSum1211, AbbSum1248, AbbSum776, AbbSum206
	common /gzabbrev/ AbbSum920, AbbSum254, AbbSum803, AbbSum235
	common /gzabbrev/ AbbSum236, AbbSum1007, AbbSum708, AbbSum62
	common /gzabbrev/ AbbSum173, AbbSum171, AbbSum161, AbbSum41
	common /gzabbrev/ AbbSum169, AbbSum1222, AbbSum1245, AbbSum174
	common /gzabbrev/ AbbSum165, AbbSum167, AbbSum111, AbbSum268
	common /gzabbrev/ AbbSum197, AbbSum195, AbbSum829, AbbSum848
	common /gzabbrev/ AbbSum335, AbbSum661, AbbSum326, AbbSum1022
	common /gzabbrev/ AbbSum518, AbbSum712, AbbSum713, AbbSum109
	common /gzabbrev/ AbbSum242, AbbSum1122, AbbSum243, AbbSum319
	common /gzabbrev/ AbbSum374, AbbSum110, AbbSum199, AbbSum805
	common /gzabbrev/ AbbSum802, AbbSum1166, AbbSum587, AbbSum828
	common /gzabbrev/ AbbSum1186, AbbSum1190, AbbSum1085
	common /gzabbrev/ AbbSum1247, AbbSum1087, AbbSum729
	common /gzabbrev/ AbbSum1102, AbbSum563, AbbSum1148, AbbSum945
	common /gzabbrev/ AbbSum1311, AbbSum1223, AbbSum685, AbbSum782
	common /gzabbrev/ AbbSum570, AbbSum1261, AbbSum571, AbbSum1098
	common /gzabbrev/ AbbSum946, AbbSum932, AbbSum1167, AbbSum549
	common /gzabbrev/ AbbSum1284, AbbSum1235, AbbSum1234
	common /gzabbrev/ AbbSum1283, AbbSum568, AbbSum551, AbbSum931
	common /gzabbrev/ AbbSum588, AbbSum114, AbbSum1146, AbbSum684
	common /gzabbrev/ AbbSum1282, AbbSum112, AbbSum417, AbbSum45
	common /gzabbrev/ AbbSum768, AbbSum113, AbbSum63, AbbSum772
	common /gzabbrev/ AbbSum1050, AbbSum1060, AbbSum900, AbbSum189
	common /gzabbrev/ AbbSum187, AbbSum350, AbbSum376, AbbSum707
	common /gzabbrev/ AbbSum683, AbbSum178, AbbSum762, AbbSum361
	common /gzabbrev/ AbbSum185, AbbSum190, AbbSum181, AbbSum183
	common /gzabbrev/ AbbSum271, AbbSum367, AbbSum270, AbbSum1133
	common /gzabbrev/ AbbSum1194, AbbSum1113, AbbSum722
	common /gzabbrev/ AbbSum1132, AbbSum567, AbbSum1218
	common /gzabbrev/ AbbSum1127, AbbSum947, AbbSum921, AbbSum564
	common /gzabbrev/ AbbSum1246, AbbSum1106, AbbSum539
	common /gzabbrev/ AbbSum1312, AbbSum1274, AbbSum1217
	common /gzabbrev/ AbbSum342, AbbSum1269, AbbSum1307, AbbSum667
	common /gzabbrev/ AbbSum212, AbbSum806, AbbSum377, AbbSum1205
	common /gzabbrev/ AbbSum917, AbbSum1154, AbbSum68, AbbSum332
	common /gzabbrev/ AbbSum589, AbbSum1224, AbbSum220, AbbSum1179
	common /gzabbrev/ AbbSum69, AbbSum325, AbbSum346, AbbSum1215
	common /gzabbrev/ AbbSum1251, AbbSum777, AbbSum207, AbbSum1120
	common /gzabbrev/ AbbSum239, AbbSum240, AbbSum1008, AbbSum711
	common /gzabbrev/ AbbSum64, AbbSum175, AbbSum172, AbbSum162
	common /gzabbrev/ AbbSum53, AbbSum170, AbbSum1227, AbbSum1250
	common /gzabbrev/ AbbSum176, AbbSum166, AbbSum168, AbbSum123
	common /gzabbrev/ AbbSum276, AbbSum198, AbbSum196, AbbSum832
	common /gzabbrev/ AbbSum849, AbbSum550, AbbSum336, AbbSum662
	common /gzabbrev/ AbbSum328, AbbSum1023, AbbSum519, AbbSum714
	common /gzabbrev/ AbbSum715, AbbSum121, AbbSum246, AbbSum1123
	common /gzabbrev/ AbbSum247, AbbSum320, AbbSum379, AbbSum122
	common /gzabbrev/ AbbSum202, AbbSum810, AbbSum808, AbbSum1169
	common /gzabbrev/ AbbSum1151, AbbSum591, AbbSum415, AbbSum388
	common /gzabbrev/ AbbSum1196, AbbSum1115, AbbSum840, AbbSum767
	common /gzabbrev/ AbbSum1075, AbbSum1070, AbbSum1090
	common /gzabbrev/ AbbSum671, AbbSum1071, AbbSum664, AbbSum839
	common /gzabbrev/ AbbSum766, AbbSum1175, AbbSum1195
	common /gzabbrev/ AbbSum1114, AbbSum815, AbbSum781, AbbSum689
	common /gzabbrev/ AbbSum785, AbbSum574, AbbSum1264, AbbSum575
	common /gzabbrev/ AbbSum368, AbbSum1176, AbbSum816, AbbSum783
	common /gzabbrev/ AbbSum1187, AbbSum948, AbbSum937, AbbSum1168
	common /gzabbrev/ AbbSum1191, AbbSum1238, AbbSum1288
	common /gzabbrev/ AbbSum1262, AbbSum830, AbbSum1285, AbbSum573
	common /gzabbrev/ AbbSum554, AbbSum936, AbbSum1296, AbbSum1086
	common /gzabbrev/ AbbSum126, AbbSum269, AbbSum1099, AbbSum1088
	common /gzabbrev/ AbbSum1103, AbbSum1153, AbbSum688
	common /gzabbrev/ AbbSum1287, AbbSum1236, AbbSum124, AbbSum418
	common /gzabbrev/ AbbSum57, AbbSum769, AbbSum125, AbbSum273
	common /gzabbrev/ AbbSum731, AbbSum728, AbbSum730, AbbSum1212
	common /gzabbrev/ AbbSum65, AbbSum773, AbbSum1052, AbbSum1062
	common /gzabbrev/ AbbSum901, AbbSum191, AbbSum188, AbbSum352
	common /gzabbrev/ AbbSum381, AbbSum710, AbbSum687, AbbSum180
	common /gzabbrev/ AbbSum763, AbbSum364, AbbSum186, AbbSum192
	common /gzabbrev/ AbbSum182, AbbSum184, AbbSum1210, AbbSum1076
	common /gzabbrev/ AbbSum200, AbbSum1054, AbbSum1091, AbbSum237
	common /gzabbrev/ AbbSum1055, AbbSum723, AbbSum257, AbbSum1197
	common /gzabbrev/ AbbSum1118, AbbSum389, AbbSum416, AbbSum348
	common /gzabbrev/ AbbSum327, AbbSum933, AbbSum569, AbbSum1139
	common /gzabbrev/ AbbSum1298, AbbSum1134, AbbSum1219
	common /gzabbrev/ AbbSum1263

	integer*8 iint1(3), iint2(3), iint3(3), iint4(3), iint5(3)
	integer*8 iint6(3), iint7(3), iint8(3), iint9(3), iint10(3)
	integer*8 iint11(3), iint12(3), iint13(3), iint14(3), iint15(3)
	integer*8 iint16(3), iint17(3), iint18(3), iint19(3), iint20(3)
	integer*8 iint21(3), iint22(3), iint23(3), iint24(3), iint25(3)
	integer*8 iint26(3), iint27(3), iint28(3), iint29(3), iint30(3)
	integer*8 iint31(3), iint32(3), iint33(3), iint34(3), iint35(3)
	integer*8 iint36(3), iint37(2), iint38(2), iint39(2), iint40(2)
	integer*8 iint41(2), iint42(2), iint43(2), iint44(2), iint45(2)
	integer*8 iint46(2), iint47(2), iint48(2), iint49(2), iint50(2)
	integer*8 iint51(2), iint52(2), iint53, iint54, iint55, iint56
	integer*8 iint57(3), iint58(3), iint59(3), iint60(3), iint61(3)
	integer*8 iint62(3), iint63(3), iint64(3), iint65(3), iint66(3)
	integer*8 iint67(3), iint68(3), iint69(3), iint70(3), iint71(3)
	integer*8 iint72(3), iint73(3), iint74(3), iint75(3), iint76(3)
	integer*8 iint77(3), iint78(3), iint79(3), iint80(3), iint81(3)
	integer*8 iint82(3), iint83(3), iint84(2,2), iint85(2,2), iint86
	integer*8 iint87, iint88(3), iint89(3), iint90(3), iint91(3)
	integer*8 iint92(3), iint93(3), iint94(3), iint95(3), iint96(3)
	integer*8 iint97(3), iint98(3), iint99(3), iint100(3)
	integer*8 iint101(3), iint102(3), iint103(3), iint104(3)
	integer*8 iint105(3), iint106(3), iint107(3), iint108(3)
	integer*8 iint109(3), iint110(3), iint111(3), iint112(3)
	integer*8 iint113(3), iint114(3), iint115(3), iint116(3)
	integer*8 iint117(3), iint118(3), iint119(3), iint120(3)
	integer*8 iint121(3), iint122(3), iint123(3), iint124(3)
	integer*8 iint125(3), iint126(3), iint127(3), iint128(3)
	integer*8 iint129(3), iint130(3), iint131(3), iint132(3)
	integer*8 iint133(3), iint134(3), iint135(3), iint136(3)
	integer*8 iint137(3), iint138(3), iint139(3), iint140(3)
	integer*8 iint141(3), iint142(3), iint143(3), iint144(3)
	integer*8 iint145(3), iint146(3), iint147(3), iint148(3)
	integer*8 iint149(3), iint150(3), iint151(3), iint152(3)
	integer*8 iint153(3), iint154(3), iint155(3), iint156(3)
	integer*8 iint157(3), iint158(3), iint159(3), iint160(3)
	integer*8 iint161(3), iint162(3), iint163(3), iint164(3)
	integer*8 iint165(3), iint166(3), iint167(3), iint168(3)
	integer*8 iint169(3), iint170(3), iint171(3), iint172(3)
	integer*8 iint173(3), iint174(3), iint175(2), iint176(2)
	integer*8 iint177(2), iint178(2), iint179(2), iint180(2)
	integer*8 iint181(2), iint182(2), iint183(2), iint184(2)
	integer*8 iint185, iint186, iint187(2), iint188(2), iint189(2)
	integer*8 iint190(2), iint191(2), iint192(2,2), iint193(2,2)
	integer*8 iint194(2,2), iint195(2,2), iint196(2,2), iint197(2,2)
	integer*8 iint198(2,2), iint199(2,2), iint200(2,2), iint201(2,2)
	integer*8 iint202(2,2), iint203(2,2), iint204(2,2)
	common /gzloopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /gzloopint/ iint7, iint8, iint9, iint10, iint11, iint12
	common /gzloopint/ iint13, iint14, iint15, iint16, iint17
	common /gzloopint/ iint18, iint19, iint20, iint21, iint22
	common /gzloopint/ iint23, iint24, iint25, iint26, iint27
	common /gzloopint/ iint28, iint29, iint30, iint31, iint32
	common /gzloopint/ iint33, iint34, iint35, iint36, iint37
	common /gzloopint/ iint38, iint39, iint40, iint41, iint42
	common /gzloopint/ iint43, iint44, iint45, iint46, iint47
	common /gzloopint/ iint48, iint49, iint50, iint51, iint52
	common /gzloopint/ iint53, iint54, iint55, iint56, iint57
	common /gzloopint/ iint58, iint59, iint60, iint61, iint62
	common /gzloopint/ iint63, iint64, iint65, iint66, iint67
	common /gzloopint/ iint68, iint69, iint70, iint71, iint72
	common /gzloopint/ iint73, iint74, iint75, iint76, iint77
	common /gzloopint/ iint78, iint79, iint80, iint81, iint82
	common /gzloopint/ iint83, iint84, iint85, iint86, iint87
	common /gzloopint/ iint88, iint89, iint90, iint91, iint92
	common /gzloopint/ iint93, iint94, iint95, iint96, iint97
	common /gzloopint/ iint98, iint99, iint100, iint101, iint102
	common /gzloopint/ iint103, iint104, iint105, iint106, iint107
	common /gzloopint/ iint108, iint109, iint110, iint111, iint112
	common /gzloopint/ iint113, iint114, iint115, iint116, iint117
	common /gzloopint/ iint118, iint119, iint120, iint121, iint122
	common /gzloopint/ iint123, iint124, iint125, iint126, iint127
	common /gzloopint/ iint128, iint129, iint130, iint131, iint132
	common /gzloopint/ iint133, iint134, iint135, iint136, iint137
	common /gzloopint/ iint138, iint139, iint140, iint141, iint142
	common /gzloopint/ iint143, iint144, iint145, iint146, iint147
	common /gzloopint/ iint148, iint149, iint150, iint151, iint152
	common /gzloopint/ iint153, iint154, iint155, iint156, iint157
	common /gzloopint/ iint158, iint159, iint160, iint161, iint162
	common /gzloopint/ iint163, iint164, iint165, iint166, iint167
	common /gzloopint/ iint168, iint169, iint170, iint171, iint172
	common /gzloopint/ iint173, iint174, iint175, iint176, iint177
	common /gzloopint/ iint178, iint179, iint180, iint181, iint182
	common /gzloopint/ iint183, iint184, iint185, iint186, iint187
	common /gzloopint/ iint188, iint189, iint190, iint191, iint192
	common /gzloopint/ iint193, iint194, iint195, iint196, iint197
	common /gzloopint/ iint198, iint199, iint200, iint201, iint202
	common /gzloopint/ iint203, iint204

	integer cha5, cha6, his5, ij, lpd5, neu5, qud5, quu5, sld5
	integer sle5, sqd5, sqe5, squ5, sqv5
	common /gzindices/ cha5, cha6, his5, ij, lpd5, neu5, qud5
	common /gzindices/ quu5, sld5, sle5, sqd5, sqe5, squ5, sqv5

	double complex Cloop(1)
	common /gzformfactors/ Cloop

