#if 0
* heeSM-renconst.h
* RC declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

	ComplexType dMWsq1, dMZsq1, dSW1, dZAA1heavy, dZAA1light
	ComplexType dZe1, dZH1, dZZA1, dMf1(2,3), dZfL1(2,3,3)
	ComplexType dZfR1(2,3,3)
	common /heeSM_renconst/ dMWsq1, dMZsq1, dSW1, dZAA1heavy
	common /heeSM_renconst/ dZAA1light, dZe1, dZH1, dZZA1, dMf1
	common /heeSM_renconst/ dZfL1, dZfR1

