#if 0
* heeSM-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "heeSM-renconst.h"

	ComplexType Sub38, Sub3, Sub44, Sub1, Sub25, Sub26, Sub9
	ComplexType Sub7, Sub15, Sub22, Sub12, Sub8, Sub23, Sub39
	ComplexType Sub21, Sub27, Sub31, Sub32, Sub20, Sub24, pave1
	ComplexType pave2, pave3(Ncc), pave4(Ncc), pave5, pave6(Ncc)
	ComplexType pave7(Ncc), pave8(Ncc)
	common /heeSM_varXs/ Sub38, Sub3, Sub44, Sub1, Sub25, Sub26
	common /heeSM_varXs/ Sub9, Sub7, Sub15, Sub22, Sub12, Sub8
	common /heeSM_varXs/ Sub23, Sub39, Sub21, Sub27, Sub31
	common /heeSM_varXs/ Sub32, Sub20, Sub24, pave1, pave2
	common /heeSM_varXs/ pave3, pave4, pave5, pave6, pave7, pave8

	ComplexType F1, F2
	ComplexType Sub17, Sub5, Sub45, Sub2, Sub4, Sub10, Sub6, Sub18
	ComplexType Sub13, Sub30, Sub36, Sub42, Sub47, Sub16, Sub43
	ComplexType Sub48, Sub29, Sub46, Sub35, Sub41, Sub19, Sub40
	ComplexType Sub14, Sub11, Sub34, Sub37, Sub51, Sub49, Sub28
	ComplexType Sub33, Sub50
	common /heeSM_varXh/ F1, F2, Sub17, Sub5, Sub45, Sub2, Sub4
	common /heeSM_varXh/ Sub10, Sub6, Sub18, Sub13, Sub30, Sub36
	common /heeSM_varXh/ Sub42, Sub47, Sub16, Sub43, Sub48
	common /heeSM_varXh/ Sub29, Sub46, Sub35, Sub41, Sub19
	common /heeSM_varXh/ Sub40, Sub14, Sub11, Sub34, Sub37
	common /heeSM_varXh/ Sub51, Sub49, Sub28, Sub33, Sub50

	integer seq(2), Hel(3)
	common /heeSM_helind/ seq, Hel

	ComplexType Ctree(1), Cloop(1)
	common /heeSM_formfactors/ Ctree, Cloop

#endif
