#if 0
* hgg-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:50
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub1(6), Sub23(6), Sub49(3), Sub54(3), Sub50(3)
	ComplexType Sub55(3), Sub46(3), Sub47(3), Sub48(3), Sub45(3)
	ComplexType Sub57(3), Sub11(3), Sub14(3), Sub4(3), Sub7(3)
	ComplexType Sub26(3), Sub29(3), Sub36(3), Sub33(3)
	ComplexType Sub15(6,3), Sub8(6,3), Sub30(6,3), Sub37(6,3)
	ComplexType Sub20(3,3), Sub19(3,3), Sub5(3,3), Sub12(3,3)
	ComplexType Sub34(3,3), Sub27(3,3), Sub42(3,3), Sub41(3,3)
	ComplexType Sub16(6,3,3), Sub9(6,3,3), Sub31(6,3,3)
	ComplexType Sub38(6,3,3), Sub13(6,3,3), Sub6(6,3,3)
	ComplexType Sub28(6,3,3), Sub35(6,3,3), Sub17(6,3,3)
	ComplexType Sub10(6,3,3), Sub21(6,3,3), Sub32(6,3,3)
	ComplexType Sub39(6,3,3), Sub43(6,3,3), Sub18(6,3,3)
	ComplexType Sub40(6,3,3), Sub22(6,3,3), Sub44(6,3,3)
	ComplexType Sub2(6), Sub24(6), pave1(Ncc,3), pave2(6)
	ComplexType pave3(Ncc,6), pave4(6), pave5(Ncc,6), pave6(3)
	ComplexType pave7(3), pave8(Ncc,3)
	common /hgg_varXs/ Sub1, Sub23, Sub49, Sub54, Sub50, Sub55
	common /hgg_varXs/ Sub46, Sub47, Sub48, Sub45, Sub57, Sub11
	common /hgg_varXs/ Sub14, Sub4, Sub7, Sub26, Sub29, Sub36
	common /hgg_varXs/ Sub33, Sub15, Sub8, Sub30, Sub37, Sub20
	common /hgg_varXs/ Sub19, Sub5, Sub12, Sub34, Sub27, Sub42
	common /hgg_varXs/ Sub41, Sub16, Sub9, Sub31, Sub38, Sub13
	common /hgg_varXs/ Sub6, Sub28, Sub35, Sub17, Sub10, Sub21
	common /hgg_varXs/ Sub32, Sub39, Sub43, Sub18, Sub40, Sub22
	common /hgg_varXs/ Sub44, Sub2, Sub24, pave1, pave2, pave3
	common /hgg_varXs/ pave4, pave5, pave6, pave7, pave8

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb2, Abb3, Abb1
	ComplexType Sub3(6), Sub25(6), Sub60(3)
	ComplexType Sub59(3), Sub61(3), Sub52(3)
	ComplexType Sub53(3), Sub58(3), Sub51(3)
	ComplexType Sub56(3)
	common /hgg_varXh/ Pair1, Pair2, Pair3, Eps1, Abb2, Abb3
	common /hgg_varXh/ Abb1, Sub3, Sub25, Sub60, Sub59, Sub61
	common /hgg_varXh/ Sub52, Sub53, Sub58, Sub51, Sub56

	integer seq(2), Hel(3)
	common /hgg_helind/ seq, Hel

	integer All4, Gen4, Ind1, Ind2
	common /hgg_indices/ All4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hgg_formfactors/ Cloop, MatSUN

#endif
