#if 0
* huu-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:57
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "huu-renconst.h"

	ComplexType Sub1, Sub2, Sub3
	ComplexType Opt1, Sub365, Sub388, Sub335, Sub337, Sub157
	ComplexType Sub334, Sub429, Sub393, Sub223, Sub221, Sub473
	ComplexType Sub422, Sub340, Sub332, Sub333, Sub478, Sub381
	ComplexType Sub395, Sub438, Sub475, Sub477, Sub391, Sub425
	ComplexType Sub385, Sub382, Sub392, Sub427, Sub428, Sub433
	ComplexType Sub457, Sub430, Sub386, Sub383, Sub389, Sub394
	ComplexType Sub432, Sub435, Sub321, Sub324, Sub327, Sub322
	ComplexType Sub329, Sub407, Sub467, Sub469, Sub242, Sub474
	ComplexType Sub186, Sub185, Sub8, Sub147, Sub390, Sub175
	ComplexType Sub189, Sub181, Sub364, Sub384, Sub387, Sub380
	ComplexType Sub187, Sub336, Sub325, Sub330, Sub127, Sub554
	ComplexType Sub464, Sub156, Sub152, Sub256, Sub141, Sub143
	ComplexType Sub243, Sub328, Sub331, Sub146(3), Sub249(3)
	ComplexType Sub258(3), Sub248(3), Sub257(3), Sub253(3)
	ComplexType Sub148(3), Sub153(3), Sub222(3), Sub224(3)
	ComplexType Sub191(3), Sub190(3), Sub195(3), Sub194(3)
	ComplexType Sub264(3), Sub214(3), Sub144(3), Sub228(3)
	ComplexType Sub229(3), Sub262(3), Sub204(3), Sub142(3)
	ComplexType Sub268(3), Sub149(3), Sub150(3), Sub155(3)
	ComplexType Sub275(3), Sub184(3), Sub192(3), Sub196(3)
	ComplexType Sub240(3), Sub245(3), Sub154(3), Sub236(3)
	ComplexType Sub114(3), Sub113(3), Sub501(3), Sub505(3)
	ComplexType Sub117(3), Sub116(3), Sub500(3), Sub504(3)
	ComplexType Sub534(3), Sub530(3), Sub120(3), Sub119(3)
	ComplexType Sub531(3), Sub535(3), Sub502(3), Sub506(3)
	ComplexType Sub532(3), Sub536(3), Sub65(3), Sub69(3)
	ComplexType Sub68(3), Sub64(3), Sub82(3), Sub86(3)
	ComplexType Sub491(3), Sub85(3), Sub81(3), Sub98(3)
	ComplexType Sub102(3), Sub99(3), Sub103(3), Sub104(3)
	ComplexType Sub66(3), Sub70(3), Sub492(3), Sub83(3)
	ComplexType Sub87(3), Sub100(3), Sub10(3), Sub14(3)
	ComplexType Sub13(3), Sub9(3), Sub28(3), Sub32(3), Sub512(3)
	ComplexType Sub31(3), Sub27(3), Sub45(3), Sub49(3), Sub46(3)
	ComplexType Sub50(3), Sub11(3), Sub15(3), Sub513(3)
	ComplexType Sub29(3), Sub33(3), Sub47(3), Sub51(3)
	ComplexType Sub283(4), Sub541(4), Sub281(4), Sub286(4)
	ComplexType Sub289(4), Sub298(4), Sub295(4), Sub543(4)
	ComplexType Sub301(4), Sub304(4), Sub307(4), Sub293(4)
	ComplexType Sub282(4), Sub284(4), Sub287(4), Sub290(4)
	ComplexType Sub299(4), Sub294(4), Sub579(4), Sub302(4)
	ComplexType Sub305(4), Sub308(4), Sub296(4), Sub115(6,3)
	ComplexType Sub118(6,3), Sub121(6,3), Sub67(6,3), Sub71(6,3)
	ComplexType Sub84(6,3), Sub88(6,3), Sub105(6,3), Sub101(6,3)
	ComplexType Sub12(6,3), Sub16(6,3), Sub30(6,3), Sub34(6,3)
	ComplexType Sub52(6,3), Sub48(6,3), Sub542(6,4), Sub546(6,4)
	ComplexType Sub581(6,4), Sub580(6,4), Sub503(6,3)
	ComplexType Sub507(6,3), Sub537(6,3), Sub533(6,3)
	ComplexType Sub493(6,3), Sub494(6,3), Sub514(6,3)
	ComplexType Sub515(6,3), Sub545(6,4), Sub544(6,4)
	ComplexType Sub134(2,2), Sub130(2,2), Sub137(2,2)
	ComplexType Sub133(2,2), Sub135(2,2), Sub136(2,2)
	ComplexType Sub138(2,2), Sub139(2,2), Sub129(2,2)
	ComplexType Sub560(2,2), Sub122(2,2), Sub126(2,2)
	ComplexType Sub125(2,2), Sub555(2,2), Sub5(3,3), Sub4(3,3)
	ComplexType Sub521(3,3), Sub520(3,3), Sub24(3,3), Sub23(3,3)
	ComplexType Sub42(3,3), Sub41(3,3), Sub56(3,3), Sub55(3,3)
	ComplexType Sub75(3,3), Sub74(3,3), Sub92(3,3), Sub91(3,3)
	ComplexType Sub109(3,3), Sub108(3,3), Sub20(3,3), Sub19(3,3)
	ComplexType Sub38(3,3), Sub37(3,3), Sub59(3,3), Sub58(3,3)
	ComplexType Sub285(4,4), Sub288(4,4), Sub291(4,4)
	ComplexType Sub297(4,4), Sub300(4,4), Sub303(4,4)
	ComplexType Sub306(4,4), Sub309(4,4), Sub317(4,4)
	ComplexType Sub311(4,4), Sub315(4,4), Sub314(4,4)
	ComplexType Sub318(4,4), Sub319(4,4), Sub313(4,4)
	ComplexType Sub312(4,4), Sub508(6,6,3), Sub538(6,6,3)
	ComplexType Sub62(6,6,3), Sub77(6,6,3), Sub79(6,6,3)
	ComplexType Sub94(6,6,3), Sub96(6,6,3), Sub111(6,6,3)
	ComplexType Sub495(6,6,3), Sub72(6,6,3), Sub89(6,6,3)
	ComplexType Sub106(6,6,3), Sub516(6,6,3), Sub17(6,6,3)
	ComplexType Sub35(6,6,3), Sub53(6,6,3), Sub487(6,2,3)
	ComplexType Sub557(6,2,3), Sub568(6,2,3), Sub510(6,2,3)
	ComplexType Sub558(6,2,3), Sub553(6,2,3), Sub488(6,2,3)
	ComplexType Sub509(6,6,3,3), Sub539(6,6,3,3), Sub57(6,6,3,3)
	ComplexType Sub6(6,6,3,3), Sub499(6,6,3,3), Sub25(6,6,3,3)
	ComplexType Sub522(6,6,3,3), Sub529(6,6,3,3), Sub43(6,6,3,3)
	ComplexType Sub540(6,6,3,3), Sub496(6,6,3,3), Sub73(6,6,3,3)
	ComplexType Sub90(6,6,3,3), Sub107(6,6,3,3), Sub63(6,6,3,3)
	ComplexType Sub76(6,6,3,3), Sub80(6,6,3,3), Sub93(6,6,3,3)
	ComplexType Sub97(6,6,3,3), Sub110(6,6,3,3), Sub490(6,6,3,3)
	ComplexType Sub497(6,6,3,3), Sub498(6,6,3,3), Sub36(6,6,3,3)
	ComplexType Sub517(6,6,3,3), Sub54(6,6,3,3), Sub18(6,6,3,3)
	ComplexType Sub7(6,6,3,3), Sub21(6,6,3,3), Sub26(6,6,3,3)
	ComplexType Sub39(6,6,3,3), Sub44(6,6,3,3), Sub511(6,6,3,3)
	ComplexType Sub519(6,6,3,3), Sub60(6,6,3,3), Sub22(6,6,3,3)
	ComplexType Sub40(6,6,3,3), Sub112(6,6,3,3,3)
	ComplexType Sub78(6,6,3,3,3), Sub95(6,6,3,3,3)
	ComplexType Sub562(6,2,2,3,3), Sub561(6,2,2,3,3)
	ComplexType Sub569(6,2,2,3,3), Sub564(6,2,2,3,3)
	ComplexType Sub572(6,2,2,3,3), Sub571(6,2,2,3,3)
	ComplexType Sub61(6,6,3,3,3,3), Sub396, Sub338, Sub476
	ComplexType Sub423, Sub424, Sub426, Sub431, Sub239, Sub208
	ComplexType Sub217, Sub123, Sub559, Sub213, Sub218, Sub220
	ComplexType Sub140, Sub124, Sub151, Sub128, Sub266
	ComplexType Sub252(3), Sub251(3), Sub233(3), Sub274(3)
	ComplexType Sub183(3), Sub182(3), Sub235(3), Sub272(3)
	ComplexType Sub234(3), Sub267(3), Sub250(3), Sub259(3)
	ComplexType Sub230(3), Sub226(3), Sub254(3), Sub132(2,2)
	ComplexType Sub131(2,2), Sub316(4,4), Sub292(4,4)
	ComplexType Sub310(4,4), Sub339, Sub371, Sub215, Sub168(3)
	ComplexType Sub200(3), Sub225(3), Sub244(3), Sub567
	ComplexType Sub172(3), Sub202(3), Sub238(3), Sub323, Sub320
	ComplexType Sub326, Sub273(3), pave1(6,6), pave2(6,6)
	ComplexType pave3(6,6), pave4(6,6), pave5(6,6), pave6(6,6)
	ComplexType pave7(6), pave8(6), pave9(6), pave10(2)
	ComplexType pave11(2,2), pave12(2,2), pave13(Ncc,3)
	ComplexType pave14(4), pave15(4,4), pave16(4,4)
	ComplexType pave17(Ncc,6,6,2), pave18(Ncc,6,6,4)
	ComplexType pave19(Ncc,6,6), pave20(6,2), pave21(Ncc,6,2,2)
	ComplexType pave22(6,4), pave23(Ncc,6,4,4), pave24, pave25
	ComplexType pave26, pave27, pave28, pave29, pave30, pave31
	ComplexType pave32, pave33, pave34, pave35, pave36(Ncc)
	ComplexType pave37(Ncc), pave38(Ncc), pave39(Ncc)
	ComplexType pave40(Ncc), pave41(Ncc), pave42(Ncc)
	ComplexType pave43(Ncc), pave44(Ncc), pave45(Ncc)
	ComplexType pave46(Ncc), pave47(Ncc), pave48(Ncc)
	ComplexType pave49(Ncc), pave50(Ncc), pave51(Ncc)
	ComplexType pave52(Ncc), pave53, pave54(Ncc), pave55(Ncc)
	ComplexType pave56, pave57(Ncc), pave58(3), pave59(3)
	ComplexType pave60(3), pave61(3), pave62(3), pave63(3)
	ComplexType pave64(3), pave65(3), pave66(3), pave67(3)
	ComplexType pave68(3), pave69(3), pave70(Ncc,3)
	ComplexType pave71(Ncc,3), pave72(Ncc,3), pave73(Ncc,3)
	ComplexType pave74(Ncc,3), pave75(3), pave76(3)
	ComplexType pave77(Ncc,3), pave78, pave79, pave80, pave81
	ComplexType pave82, pave83(Ncc), pave84(Ncc), pave85(Ncc)
	ComplexType pave86(Ncc), pave87(Ncc,3), pave88, pave89
	ComplexType pave90
	common /huu_varXs/ Sub1, Sub2, Sub3, Opt1, Sub365, Sub388
	common /huu_varXs/ Sub335, Sub337, Sub157, Sub334, Sub429
	common /huu_varXs/ Sub393, Sub223, Sub221, Sub473, Sub422
	common /huu_varXs/ Sub340, Sub332, Sub333, Sub478, Sub381
	common /huu_varXs/ Sub395, Sub438, Sub475, Sub477, Sub391
	common /huu_varXs/ Sub425, Sub385, Sub382, Sub392, Sub427
	common /huu_varXs/ Sub428, Sub433, Sub457, Sub430, Sub386
	common /huu_varXs/ Sub383, Sub389, Sub394, Sub432, Sub435
	common /huu_varXs/ Sub321, Sub324, Sub327, Sub322, Sub329
	common /huu_varXs/ Sub407, Sub467, Sub469, Sub242, Sub474
	common /huu_varXs/ Sub186, Sub185, Sub8, Sub147, Sub390
	common /huu_varXs/ Sub175, Sub189, Sub181, Sub364, Sub384
	common /huu_varXs/ Sub387, Sub380, Sub187, Sub336, Sub325
	common /huu_varXs/ Sub330, Sub127, Sub554, Sub464, Sub156
	common /huu_varXs/ Sub152, Sub256, Sub141, Sub143, Sub243
	common /huu_varXs/ Sub328, Sub331, Sub146, Sub249, Sub258
	common /huu_varXs/ Sub248, Sub257, Sub253, Sub148, Sub153
	common /huu_varXs/ Sub222, Sub224, Sub191, Sub190, Sub195
	common /huu_varXs/ Sub194, Sub264, Sub214, Sub144, Sub228
	common /huu_varXs/ Sub229, Sub262, Sub204, Sub142, Sub268
	common /huu_varXs/ Sub149, Sub150, Sub155, Sub275, Sub184
	common /huu_varXs/ Sub192, Sub196, Sub240, Sub245, Sub154
	common /huu_varXs/ Sub236, Sub114, Sub113, Sub501, Sub505
	common /huu_varXs/ Sub117, Sub116, Sub500, Sub504, Sub534
	common /huu_varXs/ Sub530, Sub120, Sub119, Sub531, Sub535
	common /huu_varXs/ Sub502, Sub506, Sub532, Sub536, Sub65
	common /huu_varXs/ Sub69, Sub68, Sub64, Sub82, Sub86, Sub491
	common /huu_varXs/ Sub85, Sub81, Sub98, Sub102, Sub99
	common /huu_varXs/ Sub103, Sub104, Sub66, Sub70, Sub492
	common /huu_varXs/ Sub83, Sub87, Sub100, Sub10, Sub14, Sub13
	common /huu_varXs/ Sub9, Sub28, Sub32, Sub512, Sub31, Sub27
	common /huu_varXs/ Sub45, Sub49, Sub46, Sub50, Sub11, Sub15
	common /huu_varXs/ Sub513, Sub29, Sub33, Sub47, Sub51
	common /huu_varXs/ Sub283, Sub541, Sub281, Sub286, Sub289
	common /huu_varXs/ Sub298, Sub295, Sub543, Sub301, Sub304
	common /huu_varXs/ Sub307, Sub293, Sub282, Sub284, Sub287
	common /huu_varXs/ Sub290, Sub299, Sub294, Sub579, Sub302
	common /huu_varXs/ Sub305, Sub308, Sub296, Sub115, Sub118
	common /huu_varXs/ Sub121, Sub67, Sub71, Sub84, Sub88
	common /huu_varXs/ Sub105, Sub101, Sub12, Sub16, Sub30
	common /huu_varXs/ Sub34, Sub52, Sub48, Sub542, Sub546
	common /huu_varXs/ Sub581, Sub580, Sub503, Sub507, Sub537
	common /huu_varXs/ Sub533, Sub493, Sub494, Sub514, Sub515
	common /huu_varXs/ Sub545, Sub544, Sub134, Sub130, Sub137
	common /huu_varXs/ Sub133, Sub135, Sub136, Sub138, Sub139
	common /huu_varXs/ Sub129, Sub560, Sub122, Sub126, Sub125
	common /huu_varXs/ Sub555, Sub5, Sub4, Sub521, Sub520, Sub24
	common /huu_varXs/ Sub23, Sub42, Sub41, Sub56, Sub55, Sub75
	common /huu_varXs/ Sub74, Sub92, Sub91, Sub109, Sub108
	common /huu_varXs/ Sub20, Sub19, Sub38, Sub37, Sub59, Sub58
	common /huu_varXs/ Sub285, Sub288, Sub291, Sub297, Sub300
	common /huu_varXs/ Sub303, Sub306, Sub309, Sub317, Sub311
	common /huu_varXs/ Sub315, Sub314, Sub318, Sub319, Sub313
	common /huu_varXs/ Sub312, Sub508, Sub538, Sub62, Sub77
	common /huu_varXs/ Sub79, Sub94, Sub96, Sub111, Sub495
	common /huu_varXs/ Sub72, Sub89, Sub106, Sub516, Sub17
	common /huu_varXs/ Sub35, Sub53, Sub487, Sub557, Sub568
	common /huu_varXs/ Sub510, Sub558, Sub553, Sub488, Sub509
	common /huu_varXs/ Sub539, Sub57, Sub6, Sub499, Sub25
	common /huu_varXs/ Sub522, Sub529, Sub43, Sub540, Sub496
	common /huu_varXs/ Sub73, Sub90, Sub107, Sub63, Sub76, Sub80
	common /huu_varXs/ Sub93, Sub97, Sub110, Sub490, Sub497
	common /huu_varXs/ Sub498, Sub36, Sub517, Sub54, Sub18, Sub7
	common /huu_varXs/ Sub21, Sub26, Sub39, Sub44, Sub511
	common /huu_varXs/ Sub519, Sub60, Sub22, Sub40, Sub112
	common /huu_varXs/ Sub78, Sub95, Sub562, Sub561, Sub569
	common /huu_varXs/ Sub564, Sub572, Sub571, Sub61, Sub396
	common /huu_varXs/ Sub338, Sub476, Sub423, Sub424, Sub426
	common /huu_varXs/ Sub431, Sub239, Sub208, Sub217, Sub123
	common /huu_varXs/ Sub559, Sub213, Sub218, Sub220, Sub140
	common /huu_varXs/ Sub124, Sub151, Sub128, Sub266, Sub252
	common /huu_varXs/ Sub251, Sub233, Sub274, Sub183, Sub182
	common /huu_varXs/ Sub235, Sub272, Sub234, Sub267, Sub250
	common /huu_varXs/ Sub259, Sub230, Sub226, Sub254, Sub132
	common /huu_varXs/ Sub131, Sub316, Sub292, Sub310, Sub339
	common /huu_varXs/ Sub371, Sub215, Sub168, Sub200, Sub225
	common /huu_varXs/ Sub244, Sub567, Sub172, Sub202, Sub238
	common /huu_varXs/ Sub323, Sub320, Sub326, Sub273, pave1
	common /huu_varXs/ pave2, pave3, pave4, pave5, pave6, pave7
	common /huu_varXs/ pave8, pave9, pave10, pave11, pave12
	common /huu_varXs/ pave13, pave14, pave15, pave16, pave17
	common /huu_varXs/ pave18, pave19, pave20, pave21, pave22
	common /huu_varXs/ pave23, pave24, pave25, pave26, pave27
	common /huu_varXs/ pave28, pave29, pave30, pave31, pave32
	common /huu_varXs/ pave33, pave34, pave35, pave36, pave37
	common /huu_varXs/ pave38, pave39, pave40, pave41, pave42
	common /huu_varXs/ pave43, pave44, pave45, pave46, pave47
	common /huu_varXs/ pave48, pave49, pave50, pave51, pave52
	common /huu_varXs/ pave53, pave54, pave55, pave56, pave57
	common /huu_varXs/ pave58, pave59, pave60, pave61, pave62
	common /huu_varXs/ pave63, pave64, pave65, pave66, pave67
	common /huu_varXs/ pave68, pave69, pave70, pave71, pave72
	common /huu_varXs/ pave73, pave74, pave75, pave76, pave77
	common /huu_varXs/ pave78, pave79, pave80, pave81, pave82
	common /huu_varXs/ pave83, pave84, pave85, pave86, pave87
	common /huu_varXs/ pave88, pave89, pave90

	ComplexType F2, F1
	ComplexType Sub348, Sub352, Sub361, Sub362, Sub411, Sub412
	ComplexType Sub465, Sub400, Sub421, Sub370, Sub373, Sub406
	ComplexType Sub369, Sub419, Sub463, Sub470, Sub409, Sub468
	ComplexType Sub482, Sub375, Sub357, Sub355, Sub347, Sub356
	ComplexType Sub358, Sub349, Sub353, Sub161, Sub163, Sub366
	ComplexType Sub351, Sub159, Sub485, Sub486, Sub345, Sub359
	ComplexType Sub416, Sub451, Sub454, Sub378, Sub420, Sub271
	ComplexType Sub209, Sub176, Sub403, Sub399, Sub404, Sub401
	ComplexType Sub417, Sub448, Sub453, Sub452, Sub376, Sub418
	ComplexType Sub414, Sub415, Sub440, Sub443, Sub446, Sub450
	ComplexType Sub471, Sub460, Sub466, Sub479, Sub483, Sub436
	ComplexType Sub481, Sub374, Sub372, Sub437, Sub441, Sub444
	ComplexType Sub447, Sub397, Sub472, Sub413, Sub461, Sub458
	ComplexType Sub459, Sub480, Sub160, Sub158, Sub162, Sub363
	ComplexType Sub367, Sub368, Sub462, Sub456, Sub164(3)
	ComplexType Sub210(3), Sub177(3)
	ComplexType Sub170(3), Sub211(3)
	ComplexType Sub178(3), Sub145(3)
	ComplexType Sub165(3), Sub166(3)
	ComplexType Sub167(3), Sub169(3)
	ComplexType Sub171(3), Sub173(3)
	ComplexType Sub174(3), Sub179(3)
	ComplexType Sub180(3), Sub188(3)
	ComplexType Sub193(3), Sub197(3)
	ComplexType Sub198(3), Sub199(3)
	ComplexType Sub201(3), Sub203(3)
	ComplexType Sub205(3), Sub206(3)
	ComplexType Sub207(3), Sub216(3)
	ComplexType Sub219(3), Sub227(3)
	ComplexType Sub231(3), Sub232(3)
	ComplexType Sub237(3), Sub241(3)
	ComplexType Sub246(3), Sub255(3)
	ComplexType Sub260(3), Sub261(3)
	ComplexType Sub263(3), Sub265(3)
	ComplexType Sub269(3), Sub277(3)
	ComplexType Sub278(3), Sub550(6,6)
	ComplexType Sub551(6,6), Sub552(6,6)
	ComplexType Sub570(2,2), Sub549(6,6,4)
	ComplexType Sub547(6,6,4), Sub548(6,6,4)
	ComplexType Sub594(6,4,4), Sub583(6,4,4)
	ComplexType Sub582(6,4,4), Sub591(6,4,4)
	ComplexType Sub585(6,4,4), Sub589(6,4,4)
	ComplexType Sub584(6,4,4), Sub586(6,4,4)
	ComplexType Sub587(6,4,4), Sub588(6,4,4)
	ComplexType Sub590(6,4,4), Sub592(6,4,4)
	ComplexType Sub595(6,4,4), Sub596(6,4,4)
	ComplexType Sub597(6,4,4), Sub563(6,2,3,3)
	ComplexType Sub489(6,6,2,3,3), Sub578(6,2,2,3,3)
	ComplexType Sub574(6,2,2,3,3), Sub565(6,2,2,3,3)
	ComplexType Sub556(6,2,2,3,3), Sub576(6,2,2,3,3)
	ComplexType Sub575(6,2,2,3,3), Sub577(6,2,2,3,3)
	ComplexType Sub528(6,6,2,3,3,3,3)
	ComplexType Sub518(6,6,2,3,3,3,3)
	ComplexType Sub525(6,6,2,3,3,3,3)
	ComplexType Sub523(6,6,2,3,3,3,3)
	ComplexType Sub526(6,6,2,3,3,3,3)
	ComplexType Sub524(6,6,2,3,3,3,3)
	ComplexType Sub527(6,6,2,3,3,3,3), Sub439, Sub402
	ComplexType Sub398, Sub442, Sub341, Sub342, Sub449, Sub346
	ComplexType Sub350, Sub354, Sub445, Sub343, Sub344, Sub405
	ComplexType Sub360, Sub410, Sub408, Sub434, Sub379, Sub377
	ComplexType Sub212(3), Sub247(3)
	ComplexType Sub270(3), Sub276(3)
	ComplexType Sub279(3), Sub593(6,4,4)
	ComplexType Sub566(6,2,2,3,3), Sub573(6,2,2,3,3)
	ComplexType Sub484, Sub280(3), Sub455
	common /huu_varXh/ F2, F1, Sub348, Sub352, Sub361, Sub362
	common /huu_varXh/ Sub411, Sub412, Sub465, Sub400, Sub421
	common /huu_varXh/ Sub370, Sub373, Sub406, Sub369, Sub419
	common /huu_varXh/ Sub463, Sub470, Sub409, Sub468, Sub482
	common /huu_varXh/ Sub375, Sub357, Sub355, Sub347, Sub356
	common /huu_varXh/ Sub358, Sub349, Sub353, Sub161, Sub163
	common /huu_varXh/ Sub366, Sub351, Sub159, Sub485, Sub486
	common /huu_varXh/ Sub345, Sub359, Sub416, Sub451, Sub454
	common /huu_varXh/ Sub378, Sub420, Sub271, Sub209, Sub176
	common /huu_varXh/ Sub403, Sub399, Sub404, Sub401, Sub417
	common /huu_varXh/ Sub448, Sub453, Sub452, Sub376, Sub418
	common /huu_varXh/ Sub414, Sub415, Sub440, Sub443, Sub446
	common /huu_varXh/ Sub450, Sub471, Sub460, Sub466, Sub479
	common /huu_varXh/ Sub483, Sub436, Sub481, Sub374, Sub372
	common /huu_varXh/ Sub437, Sub441, Sub444, Sub447, Sub397
	common /huu_varXh/ Sub472, Sub413, Sub461, Sub458, Sub459
	common /huu_varXh/ Sub480, Sub160, Sub158, Sub162, Sub363
	common /huu_varXh/ Sub367, Sub368, Sub462, Sub456, Sub164
	common /huu_varXh/ Sub210, Sub177, Sub170, Sub211, Sub178
	common /huu_varXh/ Sub145, Sub165, Sub166, Sub167, Sub169
	common /huu_varXh/ Sub171, Sub173, Sub174, Sub179, Sub180
	common /huu_varXh/ Sub188, Sub193, Sub197, Sub198, Sub199
	common /huu_varXh/ Sub201, Sub203, Sub205, Sub206, Sub207
	common /huu_varXh/ Sub216, Sub219, Sub227, Sub231, Sub232
	common /huu_varXh/ Sub237, Sub241, Sub246, Sub255, Sub260
	common /huu_varXh/ Sub261, Sub263, Sub265, Sub269, Sub277
	common /huu_varXh/ Sub278, Sub550, Sub551, Sub552, Sub570
	common /huu_varXh/ Sub549, Sub547, Sub548, Sub594, Sub583
	common /huu_varXh/ Sub582, Sub591, Sub585, Sub589, Sub584
	common /huu_varXh/ Sub586, Sub587, Sub588, Sub590, Sub592
	common /huu_varXh/ Sub595, Sub596, Sub597, Sub563, Sub489
	common /huu_varXh/ Sub578, Sub574, Sub565, Sub556, Sub576
	common /huu_varXh/ Sub575, Sub577, Sub528, Sub518, Sub525
	common /huu_varXh/ Sub523, Sub526, Sub524, Sub527, Sub439
	common /huu_varXh/ Sub402, Sub398, Sub442, Sub341, Sub342
	common /huu_varXh/ Sub449, Sub346, Sub350, Sub354, Sub445
	common /huu_varXh/ Sub343, Sub344, Sub405, Sub360, Sub410
	common /huu_varXh/ Sub408, Sub434, Sub379, Sub377, Sub212
	common /huu_varXh/ Sub247, Sub270, Sub276, Sub279, Sub593
	common /huu_varXh/ Sub566, Sub573, Sub484, Sub280, Sub455

	integer seq(2), Hel(3)
	common /huu_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /huu_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /huu_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huu_formfactors/ Ctree, Cloop, MatSUN

#endif
