#if 0
* hdd-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 17:01
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hdd-renconst.h"

	ComplexType Sub364, Sub314, Sub318, Sub395, Sub332, Sub334
	ComplexType Sub331, Sub149, Sub457, Sub237, Sub239, Sub481
	ComplexType Sub424, Sub337, Sub329, Sub330, Sub486, Sub388
	ComplexType Sub460, Sub483, Sub485, Sub381, Sub392, Sub450
	ComplexType Sub389, Sub385, Sub382, Sub451, Sub452, Sub458
	ComplexType Sub439, Sub454, Sub393, Sub455, Sub390, Sub386
	ComplexType Sub383, Sub456, Sub464, Sub316, Sub320, Sub323
	ComplexType Sub317, Sub325, Sub411, Sub407, Sub604, Sub432
	ComplexType Sub433, Sub482, Sub262, Sub175, Sub174, Sub265
	ComplexType Sub5, Sub138, Sub387, Sub171, Sub181, Sub163
	ComplexType Sub363, Sub6, Sub391, Sub394, Sub380, Sub176
	ComplexType Sub333, Sub321, Sub326, Sub125, Sub562, Sub231
	ComplexType Sub246, Sub244, Sub147, Sub143, Sub148, Sub324
	ComplexType Sub327, Sub137(3), Sub139(3), Sub144(3)
	ComplexType Sub191(3), Sub264(3), Sub164(3), Sub267(3)
	ComplexType Sub263(3), Sub183(3), Sub187(3), Sub212(3)
	ComplexType Sub211(3), Sub182(3), Sub186(3), Sub238(3)
	ComplexType Sub240(3), Sub245(3), Sub247(3), Sub232(3)
	ComplexType Sub225(3), Sub233(3), Sub226(3), Sub241(3)
	ComplexType Sub140(3), Sub141(3), Sub146(3), Sub268(3)
	ComplexType Sub228(3), Sub179(3), Sub184(3), Sub188(3)
	ComplexType Sub217(3), Sub229(3), Sub145(3), Sub223(3)
	ComplexType Sub112(3), Sub111(3), Sub535(3), Sub539(3)
	ComplexType Sub115(3), Sub114(3), Sub534(3), Sub538(3)
	ComplexType Sub508(3), Sub504(3), Sub118(3), Sub117(3)
	ComplexType Sub505(3), Sub509(3), Sub506(3), Sub510(3)
	ComplexType Sub536(3), Sub540(3), Sub63(3), Sub67(3)
	ComplexType Sub66(3), Sub62(3), Sub80(3), Sub84(3), Sub83(3)
	ComplexType Sub79(3), Sub496(3), Sub96(3), Sub100(3)
	ComplexType Sub97(3), Sub101(3), Sub497(3), Sub102(3)
	ComplexType Sub64(3), Sub68(3), Sub81(3), Sub85(3), Sub98(3)
	ComplexType Sub8(3), Sub12(3), Sub11(3), Sub7(3), Sub26(3)
	ComplexType Sub30(3), Sub29(3), Sub25(3), Sub517(3)
	ComplexType Sub43(3), Sub47(3), Sub44(3), Sub48(3), Sub13(3)
	ComplexType Sub27(3), Sub31(3), Sub45(3), Sub518(3)
	ComplexType Sub49(3), Sub9(3), Sub548(4), Sub277(4)
	ComplexType Sub275(4), Sub280(4), Sub283(4), Sub292(4)
	ComplexType Sub550(4), Sub289(4), Sub295(4), Sub298(4)
	ComplexType Sub301(4), Sub287(4), Sub276(4), Sub278(4)
	ComplexType Sub281(4), Sub284(4), Sub293(4), Sub593(4)
	ComplexType Sub288(4), Sub296(4), Sub299(4), Sub302(4)
	ComplexType Sub290(4), Sub113(6,3), Sub116(6,3), Sub119(6,3)
	ComplexType Sub65(6,3), Sub69(6,3), Sub82(6,3), Sub86(6,3)
	ComplexType Sub103(6,3), Sub99(6,3), Sub10(6,3), Sub14(6,3)
	ComplexType Sub28(6,3), Sub32(6,3), Sub50(6,3), Sub46(6,3)
	ComplexType Sub549(6,4), Sub552(6,4), Sub595(6,4)
	ComplexType Sub594(6,4), Sub537(6,3), Sub541(6,3)
	ComplexType Sub511(6,3), Sub507(6,3), Sub498(6,3)
	ComplexType Sub495(6,3), Sub519(6,3), Sub516(6,3)
	ComplexType Sub547(6,4), Sub551(6,4), Sub132(2,2)
	ComplexType Sub128(2,2), Sub135(2,2), Sub131(2,2)
	ComplexType Sub133(2,2), Sub134(2,2), Sub127(2,2)
	ComplexType Sub120(2,2), Sub561(2,2), Sub569(2,2)
	ComplexType Sub124(2,2), Sub566(2,2), Sub563(2,2)
	ComplexType Sub123(2,2), Sub2(3,3), Sub1(3,3), Sub545(3,3)
	ComplexType Sub544(3,3), Sub22(3,3), Sub21(3,3), Sub40(3,3)
	ComplexType Sub39(3,3), Sub54(3,3), Sub53(3,3), Sub73(3,3)
	ComplexType Sub72(3,3), Sub90(3,3), Sub89(3,3), Sub107(3,3)
	ComplexType Sub106(3,3), Sub18(3,3), Sub17(3,3), Sub36(3,3)
	ComplexType Sub35(3,3), Sub57(3,3), Sub56(3,3), Sub525(3,3)
	ComplexType Sub524(3,3), Sub279(4,4), Sub282(4,4)
	ComplexType Sub285(4,4), Sub291(4,4), Sub294(4,4)
	ComplexType Sub297(4,4), Sub300(4,4), Sub303(4,4)
	ComplexType Sub311(4,4), Sub305(4,4), Sub309(4,4)
	ComplexType Sub308(4,4), Sub312(4,4), Sub313(4,4)
	ComplexType Sub307(4,4), Sub306(4,4), Sub542(6,6,3)
	ComplexType Sub512(6,6,3), Sub60(6,6,3), Sub75(6,6,3)
	ComplexType Sub77(6,6,3), Sub92(6,6,3), Sub94(6,6,3)
	ComplexType Sub109(6,6,3), Sub499(6,6,3), Sub70(6,6,3)
	ComplexType Sub87(6,6,3), Sub104(6,6,3), Sub520(6,6,3)
	ComplexType Sub15(6,6,3), Sub33(6,6,3), Sub51(6,6,3)
	ComplexType Sub491(6,2,3), Sub567(6,2,3), Sub576(6,2,3)
	ComplexType Sub514(6,2,3), Sub560(6,2,3), Sub492(6,2,3)
	ComplexType Sub513(6,6,3,3), Sub543(6,6,3,3), Sub55(6,6,3,3)
	ComplexType Sub3(6,6,3,3), Sub533(6,6,3,3), Sub23(6,6,3,3)
	ComplexType Sub546(6,6,3,3), Sub503(6,6,3,3), Sub41(6,6,3,3)
	ComplexType Sub523(6,6,3,3), Sub500(6,6,3,3), Sub71(6,6,3,3)
	ComplexType Sub88(6,6,3,3), Sub105(6,6,3,3), Sub61(6,6,3,3)
	ComplexType Sub74(6,6,3,3), Sub78(6,6,3,3), Sub91(6,6,3,3)
	ComplexType Sub95(6,6,3,3), Sub108(6,6,3,3), Sub494(6,6,3,3)
	ComplexType Sub501(6,6,3,3), Sub502(6,6,3,3), Sub34(6,6,3,3)
	ComplexType Sub16(6,6,3,3), Sub52(6,6,3,3), Sub521(6,6,3,3)
	ComplexType Sub4(6,6,3,3), Sub19(6,6,3,3), Sub24(6,6,3,3)
	ComplexType Sub37(6,6,3,3), Sub42(6,6,3,3), Sub515(6,6,3,3)
	ComplexType Sub526(6,6,3,3), Sub58(6,6,3,3), Sub20(6,6,3,3)
	ComplexType Sub38(6,6,3,3), Sub581(6,2,2,3), Sub565(6,2,3,3)
	ComplexType Sub584(6,2,3,3), Sub110(6,6,3,3,3)
	ComplexType Sub76(6,6,3,3,3), Sub93(6,6,3,3,3)
	ComplexType Sub579(6,2,2,3,3), Sub570(6,2,2,3,3)
	ComplexType Sub571(6,2,2,3,3), Sub578(6,2,2,3,3)
	ComplexType Sub59(6,6,3,3,3,3), Sub396, Sub412, Sub453
	ComplexType Sub384, Sub335, Sub484, Sub425, Sub426, Sub216
	ComplexType Sub193, Sub207, Sub121, Sub568, Sub208, Sub204
	ComplexType Sub210, Sub430, Sub122, Sub142, Sub126, Sub434
	ComplexType Sub220(3), Sub251(3), Sub222(3), Sub258(3)
	ComplexType Sub255(3), Sub221(3), Sub178(3), Sub177(3)
	ComplexType Sub215(3), Sub213(3), Sub227(3), Sub234(3)
	ComplexType Sub242(3), Sub136(2,2), Sub130(2,2), Sub129(2,2)
	ComplexType Sub310(4,4), Sub286(4,4), Sub304(4,4), Sub315
	ComplexType Sub319, Sub336, Sub372, Sub195, Sub205
	ComplexType Sub168(3), Sub583, Sub166(3), Sub322, Sub259(3)
	ComplexType pave1(6,6), pave2(6,6), pave3(6,6), pave4(6,6)
	ComplexType pave5(6,6), pave6(6,6), pave7(6), pave8(6)
	ComplexType pave9(6), pave10(2), pave11(2,2), pave12(2,2)
	ComplexType pave13(4), pave14(4,4), pave15(4,4)
	ComplexType pave16(Ncc,6,6,2), pave17(Ncc,6,6,4)
	ComplexType pave18(Ncc,6,6), pave19(6,2), pave20(Ncc,6,2,2)
	ComplexType pave21(6,4), pave22(Ncc,6,4,4), pave23, pave24
	ComplexType pave25, pave26, pave27, pave28, pave29, pave30
	ComplexType pave31, pave32, pave33, pave34, pave35(Ncc)
	ComplexType pave36(Ncc), pave37(Ncc), pave38(Ncc)
	ComplexType pave39(Ncc), pave40(Ncc), pave41(Ncc)
	ComplexType pave42(Ncc), pave43(Ncc), pave44(Ncc)
	ComplexType pave45(Ncc), pave46(Ncc), pave47(Ncc)
	ComplexType pave48(Ncc), pave49(Ncc), pave50(Ncc)
	ComplexType pave51(Ncc), pave52(Ncc), pave53(Ncc), pave54
	ComplexType pave55(Ncc), pave56(Ncc), pave57(3), pave58(3)
	ComplexType pave59(3), pave60(3), pave61(3), pave62(3)
	ComplexType pave63(3), pave64(3), pave65(3), pave66(3)
	ComplexType pave67(3), pave68(3), pave69(Ncc,3)
	ComplexType pave70(Ncc,3), pave71(Ncc,3), pave72(Ncc,3)
	ComplexType pave73(Ncc,3), pave74(Ncc,3), pave75, pave76
	ComplexType pave77, pave78, pave79, pave80, pave81(Ncc)
	ComplexType pave82(Ncc), pave83(Ncc,3), pave84(Ncc,3)
	ComplexType pave85(3), pave86(3), pave87, pave88, pave89
	ComplexType pave90(Ncc)
	common /hdd_varXs/ Sub364, Sub314, Sub318, Sub395, Sub332
	common /hdd_varXs/ Sub334, Sub331, Sub149, Sub457, Sub237
	common /hdd_varXs/ Sub239, Sub481, Sub424, Sub337, Sub329
	common /hdd_varXs/ Sub330, Sub486, Sub388, Sub460, Sub483
	common /hdd_varXs/ Sub485, Sub381, Sub392, Sub450, Sub389
	common /hdd_varXs/ Sub385, Sub382, Sub451, Sub452, Sub458
	common /hdd_varXs/ Sub439, Sub454, Sub393, Sub455, Sub390
	common /hdd_varXs/ Sub386, Sub383, Sub456, Sub464, Sub316
	common /hdd_varXs/ Sub320, Sub323, Sub317, Sub325, Sub411
	common /hdd_varXs/ Sub407, Sub604, Sub432, Sub433, Sub482
	common /hdd_varXs/ Sub262, Sub175, Sub174, Sub265, Sub5
	common /hdd_varXs/ Sub138, Sub387, Sub171, Sub181, Sub163
	common /hdd_varXs/ Sub363, Sub6, Sub391, Sub394, Sub380
	common /hdd_varXs/ Sub176, Sub333, Sub321, Sub326, Sub125
	common /hdd_varXs/ Sub562, Sub231, Sub246, Sub244, Sub147
	common /hdd_varXs/ Sub143, Sub148, Sub324, Sub327, Sub137
	common /hdd_varXs/ Sub139, Sub144, Sub191, Sub264, Sub164
	common /hdd_varXs/ Sub267, Sub263, Sub183, Sub187, Sub212
	common /hdd_varXs/ Sub211, Sub182, Sub186, Sub238, Sub240
	common /hdd_varXs/ Sub245, Sub247, Sub232, Sub225, Sub233
	common /hdd_varXs/ Sub226, Sub241, Sub140, Sub141, Sub146
	common /hdd_varXs/ Sub268, Sub228, Sub179, Sub184, Sub188
	common /hdd_varXs/ Sub217, Sub229, Sub145, Sub223, Sub112
	common /hdd_varXs/ Sub111, Sub535, Sub539, Sub115, Sub114
	common /hdd_varXs/ Sub534, Sub538, Sub508, Sub504, Sub118
	common /hdd_varXs/ Sub117, Sub505, Sub509, Sub506, Sub510
	common /hdd_varXs/ Sub536, Sub540, Sub63, Sub67, Sub66
	common /hdd_varXs/ Sub62, Sub80, Sub84, Sub83, Sub79, Sub496
	common /hdd_varXs/ Sub96, Sub100, Sub97, Sub101, Sub497
	common /hdd_varXs/ Sub102, Sub64, Sub68, Sub81, Sub85, Sub98
	common /hdd_varXs/ Sub8, Sub12, Sub11, Sub7, Sub26, Sub30
	common /hdd_varXs/ Sub29, Sub25, Sub517, Sub43, Sub47, Sub44
	common /hdd_varXs/ Sub48, Sub13, Sub27, Sub31, Sub45, Sub518
	common /hdd_varXs/ Sub49, Sub9, Sub548, Sub277, Sub275
	common /hdd_varXs/ Sub280, Sub283, Sub292, Sub550, Sub289
	common /hdd_varXs/ Sub295, Sub298, Sub301, Sub287, Sub276
	common /hdd_varXs/ Sub278, Sub281, Sub284, Sub293, Sub593
	common /hdd_varXs/ Sub288, Sub296, Sub299, Sub302, Sub290
	common /hdd_varXs/ Sub113, Sub116, Sub119, Sub65, Sub69
	common /hdd_varXs/ Sub82, Sub86, Sub103, Sub99, Sub10, Sub14
	common /hdd_varXs/ Sub28, Sub32, Sub50, Sub46, Sub549
	common /hdd_varXs/ Sub552, Sub595, Sub594, Sub537, Sub541
	common /hdd_varXs/ Sub511, Sub507, Sub498, Sub495, Sub519
	common /hdd_varXs/ Sub516, Sub547, Sub551, Sub132, Sub128
	common /hdd_varXs/ Sub135, Sub131, Sub133, Sub134, Sub127
	common /hdd_varXs/ Sub120, Sub561, Sub569, Sub124, Sub566
	common /hdd_varXs/ Sub563, Sub123, Sub2, Sub1, Sub545
	common /hdd_varXs/ Sub544, Sub22, Sub21, Sub40, Sub39, Sub54
	common /hdd_varXs/ Sub53, Sub73, Sub72, Sub90, Sub89, Sub107
	common /hdd_varXs/ Sub106, Sub18, Sub17, Sub36, Sub35, Sub57
	common /hdd_varXs/ Sub56, Sub525, Sub524, Sub279, Sub282
	common /hdd_varXs/ Sub285, Sub291, Sub294, Sub297, Sub300
	common /hdd_varXs/ Sub303, Sub311, Sub305, Sub309, Sub308
	common /hdd_varXs/ Sub312, Sub313, Sub307, Sub306, Sub542
	common /hdd_varXs/ Sub512, Sub60, Sub75, Sub77, Sub92, Sub94
	common /hdd_varXs/ Sub109, Sub499, Sub70, Sub87, Sub104
	common /hdd_varXs/ Sub520, Sub15, Sub33, Sub51, Sub491
	common /hdd_varXs/ Sub567, Sub576, Sub514, Sub560, Sub492
	common /hdd_varXs/ Sub513, Sub543, Sub55, Sub3, Sub533
	common /hdd_varXs/ Sub23, Sub546, Sub503, Sub41, Sub523
	common /hdd_varXs/ Sub500, Sub71, Sub88, Sub105, Sub61
	common /hdd_varXs/ Sub74, Sub78, Sub91, Sub95, Sub108
	common /hdd_varXs/ Sub494, Sub501, Sub502, Sub34, Sub16
	common /hdd_varXs/ Sub52, Sub521, Sub4, Sub19, Sub24, Sub37
	common /hdd_varXs/ Sub42, Sub515, Sub526, Sub58, Sub20
	common /hdd_varXs/ Sub38, Sub581, Sub565, Sub584, Sub110
	common /hdd_varXs/ Sub76, Sub93, Sub579, Sub570, Sub571
	common /hdd_varXs/ Sub578, Sub59, Sub396, Sub412, Sub453
	common /hdd_varXs/ Sub384, Sub335, Sub484, Sub425, Sub426
	common /hdd_varXs/ Sub216, Sub193, Sub207, Sub121, Sub568
	common /hdd_varXs/ Sub208, Sub204, Sub210, Sub430, Sub122
	common /hdd_varXs/ Sub142, Sub126, Sub434, Sub220, Sub251
	common /hdd_varXs/ Sub222, Sub258, Sub255, Sub221, Sub178
	common /hdd_varXs/ Sub177, Sub215, Sub213, Sub227, Sub234
	common /hdd_varXs/ Sub242, Sub136, Sub130, Sub129, Sub310
	common /hdd_varXs/ Sub286, Sub304, Sub315, Sub319, Sub336
	common /hdd_varXs/ Sub372, Sub195, Sub205, Sub168, Sub583
	common /hdd_varXs/ Sub166, Sub322, Sub259, pave1, pave2
	common /hdd_varXs/ pave3, pave4, pave5, pave6, pave7, pave8
	common /hdd_varXs/ pave9, pave10, pave11, pave12, pave13
	common /hdd_varXs/ pave14, pave15, pave16, pave17, pave18
	common /hdd_varXs/ pave19, pave20, pave21, pave22, pave23
	common /hdd_varXs/ pave24, pave25, pave26, pave27, pave28
	common /hdd_varXs/ pave29, pave30, pave31, pave32, pave33
	common /hdd_varXs/ pave34, pave35, pave36, pave37, pave38
	common /hdd_varXs/ pave39, pave40, pave41, pave42, pave43
	common /hdd_varXs/ pave44, pave45, pave46, pave47, pave48
	common /hdd_varXs/ pave49, pave50, pave51, pave52, pave53
	common /hdd_varXs/ pave54, pave55, pave56, pave57, pave58
	common /hdd_varXs/ pave59, pave60, pave61, pave62, pave63
	common /hdd_varXs/ pave64, pave65, pave66, pave67, pave68
	common /hdd_varXs/ pave69, pave70, pave71, pave72, pave73
	common /hdd_varXs/ pave74, pave75, pave76, pave77, pave78
	common /hdd_varXs/ pave79, pave80, pave81, pave82, pave83
	common /hdd_varXs/ pave84, pave85, pave86, pave87, pave88
	common /hdd_varXs/ pave89, pave90

	ComplexType F1, F2
	ComplexType Sub338, Sub341, Sub328, Sub348, Sub352, Sub361
	ComplexType Sub415, Sub416, Sub490, Sub400, Sub423, Sub369
	ComplexType Sub370, Sub339, Sub406, Sub342, Sub443, Sub368
	ComplexType Sub421, Sub442, Sub444, Sub409, Sub448, Sub374
	ComplexType Sub365, Sub357, Sub355, Sub351, Sub347, Sub356
	ComplexType Sub358, Sub349, Sub353, Sub153, Sub155, Sub431
	ComplexType Sub151, Sub344, Sub359, Sub476, Sub479, Sub585
	ComplexType Sub172, Sub199, Sub403, Sub399, Sub404, Sub401
	ComplexType Sub419, Sub414, Sub474, Sub475, Sub477, Sub478
	ComplexType Sub375, Sub420, Sub397, Sub418, Sub438, Sub440
	ComplexType Sub441, Sub445, Sub449, Sub462, Sub468, Sub471
	ComplexType Sub487, Sub371, Sub373, Sub465, Sub447, Sub463
	ComplexType Sub466, Sub469, Sub472, Sub427, Sub379, Sub377
	ComplexType Sub376, Sub417, Sub436, Sub437, Sub446, Sub152
	ComplexType Sub154, Sub150, Sub362, Sub366, Sub428, Sub488
	ComplexType Sub367, Sub156(3), Sub200(3)
	ComplexType Sub160(3), Sub201(3)
	ComplexType Sub161(3), Sub196(3)
	ComplexType Sub206(3), Sub252(3)
	ComplexType Sub197(3), Sub157(3)
	ComplexType Sub158(3), Sub159(3)
	ComplexType Sub162(3), Sub165(3)
	ComplexType Sub167(3), Sub169(3)
	ComplexType Sub173(3), Sub180(3)
	ComplexType Sub185(3), Sub189(3)
	ComplexType Sub192(3), Sub194(3)
	ComplexType Sub198(3), Sub202(3)
	ComplexType Sub203(3), Sub209(3)
	ComplexType Sub214(3), Sub218(3)
	ComplexType Sub219(3), Sub224(3)
	ComplexType Sub230(3), Sub235(3)
	ComplexType Sub243(3), Sub248(3)
	ComplexType Sub249(3), Sub250(3)
	ComplexType Sub253(3), Sub254(3)
	ComplexType Sub256(3), Sub257(3)
	ComplexType Sub260(3), Sub261(3)
	ComplexType Sub266(3), Sub270(3)
	ComplexType Sub271(3), Sub272(3)
	ComplexType Sub274(3), Sub557(6,6)
	ComplexType Sub558(6,6), Sub559(6,6)
	ComplexType Sub588(2,2), Sub589(2,2)
	ComplexType Sub554(6,6,4), Sub555(6,6,4)
	ComplexType Sub553(6,6,4), Sub556(6,6,4)
	ComplexType Sub587(6,2,3), Sub608(6,4,4)
	ComplexType Sub596(6,4,4), Sub605(6,4,4)
	ComplexType Sub601(6,4,4), Sub600(6,4,4)
	ComplexType Sub597(6,4,4), Sub598(6,4,4)
	ComplexType Sub599(6,4,4), Sub602(6,4,4)
	ComplexType Sub607(6,4,4), Sub609(6,4,4)
	ComplexType Sub610(6,4,4), Sub611(6,4,4)
	ComplexType Sub612(6,4,4), Sub493(6,6,2,3,3)
	ComplexType Sub582(6,2,2,3,3), Sub591(6,2,2,3,3)
	ComplexType Sub592(6,2,2,3,3), Sub574(6,2,2,3,3)
	ComplexType Sub580(6,2,2,3,3), Sub586(6,2,2,3,3)
	ComplexType Sub564(6,2,2,3,3), Sub573(6,2,2,3,3)
	ComplexType Sub577(6,2,2,3,3), Sub572(6,2,2,3,3)
	ComplexType Sub590(6,2,2,3,3)
	ComplexType Sub532(6,6,2,3,3,3,3)
	ComplexType Sub522(6,6,2,3,3,3,3)
	ComplexType Sub529(6,6,2,3,3,3,3)
	ComplexType Sub527(6,6,2,3,3,3,3)
	ComplexType Sub530(6,6,2,3,3,3,3)
	ComplexType Sub528(6,6,2,3,3,3,3)
	ComplexType Sub531(6,6,2,3,3,3,3), Sub345, Sub461
	ComplexType Sub398, Sub402, Sub340, Sub467, Sub346, Sub350
	ComplexType Sub354, Sub470, Sub343, Sub405, Sub435, Sub360
	ComplexType Sub422, Sub473, Sub410, Sub408, Sub413, Sub459
	ComplexType Sub378, Sub429, Sub170(3), Sub190(3)
	ComplexType Sub236(3), Sub269(3)
	ComplexType Sub603(6,4,4), Sub606(6,4,4)
	ComplexType Sub575(6,2,2,3,3), Sub480, Sub489
	ComplexType Sub273(3)
	common /hdd_varXh/ F1, F2, Sub338, Sub341, Sub328, Sub348
	common /hdd_varXh/ Sub352, Sub361, Sub415, Sub416, Sub490
	common /hdd_varXh/ Sub400, Sub423, Sub369, Sub370, Sub339
	common /hdd_varXh/ Sub406, Sub342, Sub443, Sub368, Sub421
	common /hdd_varXh/ Sub442, Sub444, Sub409, Sub448, Sub374
	common /hdd_varXh/ Sub365, Sub357, Sub355, Sub351, Sub347
	common /hdd_varXh/ Sub356, Sub358, Sub349, Sub353, Sub153
	common /hdd_varXh/ Sub155, Sub431, Sub151, Sub344, Sub359
	common /hdd_varXh/ Sub476, Sub479, Sub585, Sub172, Sub199
	common /hdd_varXh/ Sub403, Sub399, Sub404, Sub401, Sub419
	common /hdd_varXh/ Sub414, Sub474, Sub475, Sub477, Sub478
	common /hdd_varXh/ Sub375, Sub420, Sub397, Sub418, Sub438
	common /hdd_varXh/ Sub440, Sub441, Sub445, Sub449, Sub462
	common /hdd_varXh/ Sub468, Sub471, Sub487, Sub371, Sub373
	common /hdd_varXh/ Sub465, Sub447, Sub463, Sub466, Sub469
	common /hdd_varXh/ Sub472, Sub427, Sub379, Sub377, Sub376
	common /hdd_varXh/ Sub417, Sub436, Sub437, Sub446, Sub152
	common /hdd_varXh/ Sub154, Sub150, Sub362, Sub366, Sub428
	common /hdd_varXh/ Sub488, Sub367, Sub156, Sub200, Sub160
	common /hdd_varXh/ Sub201, Sub161, Sub196, Sub206, Sub252
	common /hdd_varXh/ Sub197, Sub157, Sub158, Sub159, Sub162
	common /hdd_varXh/ Sub165, Sub167, Sub169, Sub173, Sub180
	common /hdd_varXh/ Sub185, Sub189, Sub192, Sub194, Sub198
	common /hdd_varXh/ Sub202, Sub203, Sub209, Sub214, Sub218
	common /hdd_varXh/ Sub219, Sub224, Sub230, Sub235, Sub243
	common /hdd_varXh/ Sub248, Sub249, Sub250, Sub253, Sub254
	common /hdd_varXh/ Sub256, Sub257, Sub260, Sub261, Sub266
	common /hdd_varXh/ Sub270, Sub271, Sub272, Sub274, Sub557
	common /hdd_varXh/ Sub558, Sub559, Sub588, Sub589, Sub554
	common /hdd_varXh/ Sub555, Sub553, Sub556, Sub587, Sub608
	common /hdd_varXh/ Sub596, Sub605, Sub601, Sub600, Sub597
	common /hdd_varXh/ Sub598, Sub599, Sub602, Sub607, Sub609
	common /hdd_varXh/ Sub610, Sub611, Sub612, Sub493, Sub582
	common /hdd_varXh/ Sub591, Sub592, Sub574, Sub580, Sub586
	common /hdd_varXh/ Sub564, Sub573, Sub577, Sub572, Sub590
	common /hdd_varXh/ Sub532, Sub522, Sub529, Sub527, Sub530
	common /hdd_varXh/ Sub528, Sub531, Sub345, Sub461, Sub398
	common /hdd_varXh/ Sub402, Sub340, Sub467, Sub346, Sub350
	common /hdd_varXh/ Sub354, Sub470, Sub343, Sub405, Sub435
	common /hdd_varXh/ Sub360, Sub422, Sub473, Sub410, Sub408
	common /hdd_varXh/ Sub413, Sub459, Sub378, Sub429, Sub170
	common /hdd_varXh/ Sub190, Sub236, Sub269, Sub603, Sub606
	common /hdd_varXh/ Sub575, Sub480, Sub489, Sub273

	integer seq(2), Hel(3)
	common /hdd_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hdd_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hdd_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hdd_formfactors/ Ctree, Cloop, MatSUN

#endif
