#if 0
* huuSM-renconst.h
* RC declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

	ComplexType dMWsq1, dMZsq1, dSW1, dZAA1heavy, dZAA1light
	ComplexType dZe1, dZH1, dZZA1, dMf1(3,3), dZfL1(3,3,3)
	ComplexType dZfR1(3,3,3)
	common /huuSM_renconst/ dMWsq1, dMZsq1, dSW1, dZAA1heavy
	common /huuSM_renconst/ dZAA1light, dZe1, dZH1, dZZA1, dMf1
	common /huuSM_renconst/ dZfL1, dZfR1

