.TH FHCONSTRAINTS 1 "24-Sep-2012"
.SH NAME
.PP
FHConstraints \- evaluate electroweak precision observables
.SH SYNOPSIS (Fortran version)
.PP
integer error, ccb
.br
double precision gm2
.br
double precision Deltarho, MWMSSM, MWSM, SW2MSSM, SW2SM
.br
double precision edmeTh, edmn, edmHg
.sp
subroutine FHConstraints(error, gm2,
.br
  Deltarho, MWMSSM, MWSM, SW2MSSM, SW2SM,
.br
  edmeTh, edmn, edmHg,
.br
  ccb)
.SH SYNOPSIS (Mathematica version)
.PP
FHConstraints[]
.SH DESCRIPTION
FHConstraints evaluates electroweak precision observables which are 
used as further constraints on the MSSM parameter space.
.SH ARGUMENTS
.TP
.B error (output)
zero if successful, otherwise the line number in Constraints.F from
which the error message was emitted.
.TP
.B gm2 (output)
the anomalous magnetic moment of the muon, (g_mu - 2),
.TP
.B Deltarho (output)
Delta rho,
.TP
.B MWMSSM, MWSM, SW2MSSM, SW2SM (output)
the W mass and effective weak mixing angle in the MSSM and SM,
.TP
.B edmeTh, edmn, edmHg (output)
the electric dipole moments of the electron (derived from Thorium, 
edmeTh), the neutron (edmn), and mercury (edmHg).
.TP
.B ccb (output)
whether the parameter point corresponds to a colour-breaking minimum.
.SH SEE ALSO
.PP
libFH(1)
