.TH FHRETRIEVEFLAGSSTRING 1 "2-May-2011"
.SH NAME
.PP
FHRetrieveFlagsString \- retrieve the FeynHiggs flags as a string
.SH SYNOPSIS (Fortran version)
.PP
integer error
.br
character*9 flags
.sp
subroutine FHRetrieveFlagsString(error, flags)
.SH SYNOPSIS (Mathematica version)
.PP
FHRetrieveFlagsString[]
.SH DESCRIPTION
FHRetrieveFlagsString works just like FHRetrieveFlags except that the 
flags are given as a 9-digit character string rather than as 9 integers.
.SH SEE ALSO
.PP
libFH(1)
