#if 0
* hee-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:54
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hee-renconst.h"

	ComplexType Sub1, Sub2, Sub3
	ComplexType Sub227, Sub232, Sub236, Sub298, Sub197, Sub199
	ComplexType Sub196, Sub146, Sub147, Sub361, Sub327, Sub364
	ComplexType Sub202, Sub193, Sub195, Sub369, Sub366, Sub291
	ComplexType Sub354, Sub362, Sub363, Sub280, Sub295, Sub340
	ComplexType Sub292, Sub284, Sub281, Sub341, Sub342, Sub352
	ComplexType Sub376, Sub365, Sub344, Sub296, Sub350, Sub293
	ComplexType Sub285, Sub282, Sub351, Sub331, Sub234, Sub238
	ComplexType Sub241, Sub235, Sub243, Sub321, Sub433, Sub307
	ComplexType Sub248, Sub306, Sub249, Sub370, Sub139, Sub286
	ComplexType Sub256, Sub304, Sub194, Sub226, Sub8, Sub294
	ComplexType Sub297, Sub289, Sub381, Sub198, Sub308, Sub239
	ComplexType Sub244, Sub127, Sub456, Sub140, Sub141, Sub144
	ComplexType Sub145, Sub242, Sub245, Sub444(2), Sub443(2)
	ComplexType Sub455(2), Sub451(2), Sub464(2), Sub396(3)
	ComplexType Sub400(3), Sub114(3), Sub113(3), Sub395(3)
	ComplexType Sub399(3), Sub117(3), Sub116(3), Sub120(3)
	ComplexType Sub119(3), Sub397(3), Sub401(3), Sub65(3)
	ComplexType Sub69(3), Sub68(3), Sub64(3), Sub82(3), Sub86(3)
	ComplexType Sub85(3), Sub81(3), Sub98(3), Sub102(3)
	ComplexType Sub99(3), Sub103(3), Sub104(3), Sub66(3)
	ComplexType Sub70(3), Sub83(3), Sub87(3), Sub100(3)
	ComplexType Sub10(3), Sub14(3), Sub13(3), Sub9(3), Sub28(3)
	ComplexType Sub32(3), Sub31(3), Sub27(3), Sub45(3), Sub49(3)
	ComplexType Sub46(3), Sub50(3), Sub11(3), Sub15(3), Sub29(3)
	ComplexType Sub33(3), Sub47(3), Sub51(3), Sub156(4)
	ComplexType Sub408(4), Sub154(4), Sub159(4), Sub162(4)
	ComplexType Sub171(4), Sub168(4), Sub410(4), Sub174(4)
	ComplexType Sub177(4), Sub180(4), Sub166(4), Sub155(4)
	ComplexType Sub157(4), Sub160(4), Sub163(4), Sub172(4)
	ComplexType Sub167(4), Sub417(4), Sub175(4), Sub178(4)
	ComplexType Sub181(4), Sub169(4), Sub115(6,3), Sub118(6,3)
	ComplexType Sub121(6,3), Sub67(6,3), Sub71(6,3), Sub84(6,3)
	ComplexType Sub88(6,3), Sub105(6,3), Sub101(6,3), Sub12(6,3)
	ComplexType Sub16(6,3), Sub30(6,3), Sub34(6,3), Sub52(6,3)
	ComplexType Sub48(6,3), Sub409(6,4), Sub413(6,4)
	ComplexType Sub419(6,4), Sub418(6,4), Sub398(6,3)
	ComplexType Sub402(6,3), Sub412(6,4), Sub411(6,4)
	ComplexType Sub134(2,2), Sub130(2,2), Sub137(2,2)
	ComplexType Sub133(2,2), Sub135(2,2), Sub136(2,2)
	ComplexType Sub448(2,2), Sub466(2,2), Sub129(2,2)
	ComplexType Sub122(2,2), Sub453(2,2), Sub440(2,2)
	ComplexType Sub126(2,2), Sub441(2,2), Sub458(2,2)
	ComplexType Sub454(2,2), Sub449(2,2), Sub459(2,2)
	ComplexType Sub445(2,2), Sub446(2,2), Sub465(2,2)
	ComplexType Sub467(2,2), Sub125(2,2), Sub406(3,3)
	ComplexType Sub405(3,3), Sub5(3,3), Sub4(3,3), Sub24(3,3)
	ComplexType Sub23(3,3), Sub42(3,3), Sub41(3,3), Sub56(3,3)
	ComplexType Sub55(3,3), Sub75(3,3), Sub74(3,3), Sub92(3,3)
	ComplexType Sub91(3,3), Sub109(3,3), Sub108(3,3), Sub20(3,3)
	ComplexType Sub19(3,3), Sub38(3,3), Sub37(3,3), Sub59(3,3)
	ComplexType Sub58(3,3), Sub158(4,4), Sub161(4,4)
	ComplexType Sub164(4,4), Sub170(4,4), Sub173(4,4)
	ComplexType Sub176(4,4), Sub179(4,4), Sub182(4,4)
	ComplexType Sub190(4,4), Sub184(4,4), Sub188(4,4)
	ComplexType Sub187(4,4), Sub191(4,4), Sub192(4,4)
	ComplexType Sub186(4,4), Sub185(4,4), Sub403(6,6,3)
	ComplexType Sub62(6,6,3), Sub77(6,6,3), Sub79(6,6,3)
	ComplexType Sub94(6,6,3), Sub96(6,6,3), Sub111(6,6,3)
	ComplexType Sub72(6,6,3), Sub89(6,6,3), Sub106(6,6,3)
	ComplexType Sub17(6,6,3), Sub35(6,6,3), Sub53(6,6,3)
	ComplexType Sub404(6,6,3,3), Sub57(6,6,3,3), Sub394(6,6,3,3)
	ComplexType Sub407(6,6,3,3), Sub6(6,6,3,3), Sub25(6,6,3,3)
	ComplexType Sub43(6,6,3,3), Sub73(6,6,3,3), Sub90(6,6,3,3)
	ComplexType Sub107(6,6,3,3), Sub63(6,6,3,3), Sub76(6,6,3,3)
	ComplexType Sub80(6,6,3,3), Sub93(6,6,3,3), Sub97(6,6,3,3)
	ComplexType Sub110(6,6,3,3), Sub36(6,6,3,3), Sub54(6,6,3,3)
	ComplexType Sub18(6,6,3,3), Sub7(6,6,3,3), Sub21(6,6,3,3)
	ComplexType Sub26(6,6,3,3), Sub39(6,6,3,3), Sub44(6,6,3,3)
	ComplexType Sub60(6,6,3,3), Sub22(6,6,3,3), Sub40(6,6,3,3)
	ComplexType Sub112(6,6,3,3,3), Sub78(6,6,3,3,3)
	ComplexType Sub95(6,6,3,3,3), Sub61(6,6,3,3,3,3), Sub343
	ComplexType Sub283, Sub200, Sub328, Sub329, Sub264, Sub247
	ComplexType Sub323, Sub123, Sub439, Sub303, Sub374, Sub384
	ComplexType Sub142, Sub143, Sub128, Sub457, Sub251, Sub373
	ComplexType Sub138(2,2), Sub132(2,2), Sub131(2,2)
	ComplexType Sub189(4,4), Sub165(4,4), Sub183(4,4), Sub233
	ComplexType Sub237, Sub201, Sub270, Sub250, Sub421, Sub240
	ComplexType Sub367, pave1(6,6), pave2(6,6), pave3(6,6)
	ComplexType pave4(6,6), pave5(6,6), pave6(6,6), pave7(6)
	ComplexType pave8(6), pave9(6), pave10(2), pave11(2,2)
	ComplexType pave12(2,2), pave13(3), pave14(3), pave15(3)
	ComplexType pave16(3), pave17(3), pave18(3), pave19(3)
	ComplexType pave20(3), pave21(3), pave22(3), pave23(3)
	ComplexType pave24(3), pave25(4), pave26(4,4), pave27(4,4)
	ComplexType pave28(Ncc,6,6,4), pave29(6,4), pave30(2,3)
	ComplexType pave31(Ncc,2,2,3), pave32(Ncc,2,3), pave33
	ComplexType pave34, pave35, pave36, pave37, pave38, pave39
	ComplexType pave40, pave41, pave42, pave43, pave44
	ComplexType pave45(Ncc), pave46(Ncc), pave47(Ncc)
	ComplexType pave48(Ncc), pave49(Ncc), pave50(Ncc)
	ComplexType pave51(Ncc), pave52(Ncc), pave53(Ncc)
	ComplexType pave54(Ncc), pave55(Ncc), pave56(Ncc)
	ComplexType pave57(Ncc), pave58(Ncc), pave59(Ncc)
	ComplexType pave60(Ncc), pave61(Ncc), pave62(Ncc)
	ComplexType pave63(Ncc), pave64, pave65(Ncc), pave66(Ncc)
	ComplexType pave67(Ncc), pave68(Ncc), pave69(Ncc)
	ComplexType pave70(Ncc), pave71(Ncc), pave72(Ncc), pave73
	ComplexType pave74, pave75, pave76, pave77, pave78, pave79
	ComplexType pave80, pave81(Ncc), pave82(Ncc)
	ComplexType pave83(Ncc,6,4,4), pave84, pave85, pave86
	ComplexType pave87(Ncc), pave88(Ncc)
	common /hee_varXs/ Sub1, Sub2, Sub3, Sub227, Sub232, Sub236
	common /hee_varXs/ Sub298, Sub197, Sub199, Sub196, Sub146
	common /hee_varXs/ Sub147, Sub361, Sub327, Sub364, Sub202
	common /hee_varXs/ Sub193, Sub195, Sub369, Sub366, Sub291
	common /hee_varXs/ Sub354, Sub362, Sub363, Sub280, Sub295
	common /hee_varXs/ Sub340, Sub292, Sub284, Sub281, Sub341
	common /hee_varXs/ Sub342, Sub352, Sub376, Sub365, Sub344
	common /hee_varXs/ Sub296, Sub350, Sub293, Sub285, Sub282
	common /hee_varXs/ Sub351, Sub331, Sub234, Sub238, Sub241
	common /hee_varXs/ Sub235, Sub243, Sub321, Sub433, Sub307
	common /hee_varXs/ Sub248, Sub306, Sub249, Sub370, Sub139
	common /hee_varXs/ Sub286, Sub256, Sub304, Sub194, Sub226
	common /hee_varXs/ Sub8, Sub294, Sub297, Sub289, Sub381
	common /hee_varXs/ Sub198, Sub308, Sub239, Sub244, Sub127
	common /hee_varXs/ Sub456, Sub140, Sub141, Sub144, Sub145
	common /hee_varXs/ Sub242, Sub245, Sub444, Sub443, Sub455
	common /hee_varXs/ Sub451, Sub464, Sub396, Sub400, Sub114
	common /hee_varXs/ Sub113, Sub395, Sub399, Sub117, Sub116
	common /hee_varXs/ Sub120, Sub119, Sub397, Sub401, Sub65
	common /hee_varXs/ Sub69, Sub68, Sub64, Sub82, Sub86, Sub85
	common /hee_varXs/ Sub81, Sub98, Sub102, Sub99, Sub103
	common /hee_varXs/ Sub104, Sub66, Sub70, Sub83, Sub87
	common /hee_varXs/ Sub100, Sub10, Sub14, Sub13, Sub9, Sub28
	common /hee_varXs/ Sub32, Sub31, Sub27, Sub45, Sub49, Sub46
	common /hee_varXs/ Sub50, Sub11, Sub15, Sub29, Sub33, Sub47
	common /hee_varXs/ Sub51, Sub156, Sub408, Sub154, Sub159
	common /hee_varXs/ Sub162, Sub171, Sub168, Sub410, Sub174
	common /hee_varXs/ Sub177, Sub180, Sub166, Sub155, Sub157
	common /hee_varXs/ Sub160, Sub163, Sub172, Sub167, Sub417
	common /hee_varXs/ Sub175, Sub178, Sub181, Sub169, Sub115
	common /hee_varXs/ Sub118, Sub121, Sub67, Sub71, Sub84
	common /hee_varXs/ Sub88, Sub105, Sub101, Sub12, Sub16
	common /hee_varXs/ Sub30, Sub34, Sub52, Sub48, Sub409
	common /hee_varXs/ Sub413, Sub419, Sub418, Sub398, Sub402
	common /hee_varXs/ Sub412, Sub411, Sub134, Sub130, Sub137
	common /hee_varXs/ Sub133, Sub135, Sub136, Sub448, Sub466
	common /hee_varXs/ Sub129, Sub122, Sub453, Sub440, Sub126
	common /hee_varXs/ Sub441, Sub458, Sub454, Sub449, Sub459
	common /hee_varXs/ Sub445, Sub446, Sub465, Sub467, Sub125
	common /hee_varXs/ Sub406, Sub405, Sub5, Sub4, Sub24, Sub23
	common /hee_varXs/ Sub42, Sub41, Sub56, Sub55, Sub75, Sub74
	common /hee_varXs/ Sub92, Sub91, Sub109, Sub108, Sub20
	common /hee_varXs/ Sub19, Sub38, Sub37, Sub59, Sub58, Sub158
	common /hee_varXs/ Sub161, Sub164, Sub170, Sub173, Sub176
	common /hee_varXs/ Sub179, Sub182, Sub190, Sub184, Sub188
	common /hee_varXs/ Sub187, Sub191, Sub192, Sub186, Sub185
	common /hee_varXs/ Sub403, Sub62, Sub77, Sub79, Sub94, Sub96
	common /hee_varXs/ Sub111, Sub72, Sub89, Sub106, Sub17
	common /hee_varXs/ Sub35, Sub53, Sub404, Sub57, Sub394
	common /hee_varXs/ Sub407, Sub6, Sub25, Sub43, Sub73, Sub90
	common /hee_varXs/ Sub107, Sub63, Sub76, Sub80, Sub93, Sub97
	common /hee_varXs/ Sub110, Sub36, Sub54, Sub18, Sub7, Sub21
	common /hee_varXs/ Sub26, Sub39, Sub44, Sub60, Sub22, Sub40
	common /hee_varXs/ Sub112, Sub78, Sub95, Sub61, Sub343
	common /hee_varXs/ Sub283, Sub200, Sub328, Sub329, Sub264
	common /hee_varXs/ Sub247, Sub323, Sub123, Sub439, Sub303
	common /hee_varXs/ Sub374, Sub384, Sub142, Sub143, Sub128
	common /hee_varXs/ Sub457, Sub251, Sub373, Sub138, Sub132
	common /hee_varXs/ Sub131, Sub189, Sub165, Sub183, Sub233
	common /hee_varXs/ Sub237, Sub201, Sub270, Sub250, Sub421
	common /hee_varXs/ Sub240, Sub367, pave1, pave2, pave3
	common /hee_varXs/ pave4, pave5, pave6, pave7, pave8, pave9
	common /hee_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hee_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hee_varXs/ pave20, pave21, pave22, pave23, pave24
	common /hee_varXs/ pave25, pave26, pave27, pave28, pave29
	common /hee_varXs/ pave30, pave31, pave32, pave33, pave34
	common /hee_varXs/ pave35, pave36, pave37, pave38, pave39
	common /hee_varXs/ pave40, pave41, pave42, pave43, pave44
	common /hee_varXs/ pave45, pave46, pave47, pave48, pave49
	common /hee_varXs/ pave50, pave51, pave52, pave53, pave54
	common /hee_varXs/ pave55, pave56, pave57, pave58, pave59
	common /hee_varXs/ pave60, pave61, pave62, pave63, pave64
	common /hee_varXs/ pave65, pave66, pave67, pave68, pave69
	common /hee_varXs/ pave70, pave71, pave72, pave73, pave74
	common /hee_varXs/ pave75, pave76, pave77, pave78, pave79
	common /hee_varXs/ pave80, pave81, pave82, pave83, pave84
	common /hee_varXs/ pave85, pave86, pave87, pave88

	ComplexType F1, F2
	ComplexType Sub203, Sub216, Sub220, Sub224, Sub246, Sub299
	ComplexType Sub257, Sub326, Sub231, Sub263, Sub204, Sub386
	ComplexType Sub318, Sub385, Sub379, Sub266, Sub310, Sub311
	ComplexType Sub383, Sub206, Sub228, Sub212, Sub208, Sub207
	ComplexType Sub213, Sub209, Sub219, Sub215, Sub217, Sub221
	ComplexType Sub153, Sub149, Sub151, Sub210, Sub391, Sub269
	ComplexType Sub315, Sub287, Sub290, Sub302, Sub389, Sub319
	ComplexType Sub325, Sub253, Sub324, Sub260, Sub255, Sub268
	ComplexType Sub261, Sub258, Sub316, Sub346, Sub345, Sub347
	ComplexType Sub348, Sub252, Sub276, Sub317, Sub300, Sub305
	ComplexType Sub313, Sub314, Sub335, Sub338, Sub356, Sub372
	ComplexType Sub377, Sub375, Sub378, Sub380, Sub388, Sub387
	ComplexType Sub273, Sub272, Sub332, Sub353, Sub274, Sub277
	ComplexType Sub357, Sub339, Sub333, Sub336, Sub330, Sub322
	ComplexType Sub271, Sub312, Sub368, Sub371, Sub148, Sub150
	ComplexType Sub152, Sub225, Sub229, Sub230, Sub382
	ComplexType Sub462(2), Sub469(2)
	ComplexType Sub470(2), Sub471(2)
	ComplexType Sub452(2,2), Sub442(2,2)
	ComplexType Sub461(2,2), Sub463(2,2)
	ComplexType Sub447(2,2), Sub472(2,3)
	ComplexType Sub416(6,6,4), Sub414(6,6,4)
	ComplexType Sub415(6,6,4), Sub430(6,4,4)
	ComplexType Sub420(6,4,4), Sub434(6,4,4)
	ComplexType Sub426(6,4,4), Sub425(6,4,4)
	ComplexType Sub422(6,4,4), Sub423(6,4,4)
	ComplexType Sub429(6,4,4), Sub424(6,4,4)
	ComplexType Sub427(6,4,4), Sub435(6,4,4)
	ComplexType Sub431(6,4,4), Sub432(6,4,4)
	ComplexType Sub436(6,4,4), Sub437(6,4,4), Sub392
	ComplexType Sub275, Sub355, Sub254, Sub259, Sub334, Sub211
	ComplexType Sub214, Sub218, Sub337, Sub262, Sub205, Sub223
	ComplexType Sub222, Sub390, Sub320, Sub267, Sub279, Sub288
	ComplexType Sub278, Sub265, Sub309, Sub301, Sub358, Sub360
	ComplexType Sub450(2,2), Sub460(2,2)
	ComplexType Sub428(6,4,4), Sub438(6,4,4), Sub393
	ComplexType Sub468(2,2), Sub359, Sub349
	common /hee_varXh/ F1, F2, Sub203, Sub216, Sub220, Sub224
	common /hee_varXh/ Sub246, Sub299, Sub257, Sub326, Sub231
	common /hee_varXh/ Sub263, Sub204, Sub386, Sub318, Sub385
	common /hee_varXh/ Sub379, Sub266, Sub310, Sub311, Sub383
	common /hee_varXh/ Sub206, Sub228, Sub212, Sub208, Sub207
	common /hee_varXh/ Sub213, Sub209, Sub219, Sub215, Sub217
	common /hee_varXh/ Sub221, Sub153, Sub149, Sub151, Sub210
	common /hee_varXh/ Sub391, Sub269, Sub315, Sub287, Sub290
	common /hee_varXh/ Sub302, Sub389, Sub319, Sub325, Sub253
	common /hee_varXh/ Sub324, Sub260, Sub255, Sub268, Sub261
	common /hee_varXh/ Sub258, Sub316, Sub346, Sub345, Sub347
	common /hee_varXh/ Sub348, Sub252, Sub276, Sub317, Sub300
	common /hee_varXh/ Sub305, Sub313, Sub314, Sub335, Sub338
	common /hee_varXh/ Sub356, Sub372, Sub377, Sub375, Sub378
	common /hee_varXh/ Sub380, Sub388, Sub387, Sub273, Sub272
	common /hee_varXh/ Sub332, Sub353, Sub274, Sub277, Sub357
	common /hee_varXh/ Sub339, Sub333, Sub336, Sub330, Sub322
	common /hee_varXh/ Sub271, Sub312, Sub368, Sub371, Sub148
	common /hee_varXh/ Sub150, Sub152, Sub225, Sub229, Sub230
	common /hee_varXh/ Sub382, Sub462, Sub469, Sub470, Sub471
	common /hee_varXh/ Sub452, Sub442, Sub461, Sub463, Sub447
	common /hee_varXh/ Sub472, Sub416, Sub414, Sub415, Sub430
	common /hee_varXh/ Sub420, Sub434, Sub426, Sub425, Sub422
	common /hee_varXh/ Sub423, Sub429, Sub424, Sub427, Sub435
	common /hee_varXh/ Sub431, Sub432, Sub436, Sub437, Sub392
	common /hee_varXh/ Sub275, Sub355, Sub254, Sub259, Sub334
	common /hee_varXh/ Sub211, Sub214, Sub218, Sub337, Sub262
	common /hee_varXh/ Sub205, Sub223, Sub222, Sub390, Sub320
	common /hee_varXh/ Sub267, Sub279, Sub288, Sub278, Sub265
	common /hee_varXh/ Sub309, Sub301, Sub358, Sub360, Sub450
	common /hee_varXh/ Sub460, Sub428, Sub438, Sub393, Sub468
	common /hee_varXh/ Sub359, Sub349

	integer seq(2), Hel(3)
	common /hee_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hee_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hee_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	common /hee_formfactors/ Ctree, Cloop

#endif
