#if 0
* hee-renconst.h
* RC declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:54
* this file is part of FeynHiggs
#endif

	ComplexType dMA0G0sq1, dMh0A0sq1, dMh0G0sq1, dMHHA0sq1
	ComplexType dMHHG0sq1, dMWsq1, dMZsq1, dSW1, dTA01, dTB1
	ComplexType dTh01, dTHH1, dZA0A01, dZA0G01, dZAA1heavy
	ComplexType dZAA1light, dZe1, dZh0h01, dZh0HH1, dZHHHH1
	ComplexType dZZA1, dMf1(2,3), dZfL1(2,3,3), dZfR1(2,3,3)
	common /hee_renconst/ dMA0G0sq1, dMh0A0sq1, dMh0G0sq1
	common /hee_renconst/ dMHHA0sq1, dMHHG0sq1, dMWsq1, dMZsq1
	common /hee_renconst/ dSW1, dTA01, dTB1, dTh01, dTHH1
	common /hee_renconst/ dZA0A01, dZA0G01, dZAA1heavy
	common /hee_renconst/ dZAA1light, dZe1, dZh0h01, dZh0HH1
	common /hee_renconst/ dZHHHH1, dZZA1, dMf1, dZfL1, dZfR1

