#if 0
* hgaga-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:50
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub84, Sub85, Sub5, Sub97, Sub96, Sub6, Sub86
	ComplexType Sub1(6), Sub21(6), Sub57(2), Sub58(2), Sub66(2)
	ComplexType Sub60(2), Sub62(2), Sub61(2), Sub69(2), Sub70(3)
	ComplexType Sub73(3), Sub76(3), Sub71(3), Sub74(3), Sub77(3)
	ComplexType Sub83(3), Sub8(3), Sub12(3), Sub7(3), Sub11(3)
	ComplexType Sub24(3), Sub28(3), Sub23(3), Sub27(3), Sub44(3)
	ComplexType Sub40(3), Sub41(3), Sub45(3), Sub13(3), Sub25(3)
	ComplexType Sub29(3), Sub42(3), Sub46(3), Sub9(3)
	ComplexType Sub15(6,3), Sub31(6,3), Sub48(6,3), Sub10(6,3)
	ComplexType Sub14(6,3), Sub26(6,3), Sub30(6,3), Sub47(6,3)
	ComplexType Sub43(6,3), Sub18(3,3), Sub17(3,3), Sub34(3,3)
	ComplexType Sub33(3,3), Sub51(3,3), Sub50(3,3), Sub32(6,3,3)
	ComplexType Sub16(6,3,3), Sub49(6,3,3), Sub4(6,3,3)
	ComplexType Sub19(6,3,3), Sub22(6,3,3), Sub35(6,3,3)
	ComplexType Sub39(6,3,3), Sub52(6,3,3), Sub20(6,3,3)
	ComplexType Sub36(6,3,3), Sub53(6,3,3), Sub94, Sub67, Sub63
	ComplexType Sub64, Sub68, Sub2(6), Sub54(6), Sub37(6)
	ComplexType Sub65(2), pave1(Ncc,2), pave2(Ncc), pave3
	ComplexType pave4(Ncc), pave5, pave6(6), pave7(Ncc,6)
	ComplexType pave8(6), pave9(Ncc,6), pave10(Ncc,6), pave11(2)
	ComplexType pave12(3), pave13(Ncc,3), pave14(3)
	ComplexType pave15(Ncc,3), pave16(3), pave17(Ncc,3)
	ComplexType pave18(6)
	common /hgaga_varXs/ Sub84, Sub85, Sub5, Sub97, Sub96, Sub6
	common /hgaga_varXs/ Sub86, Sub1, Sub21, Sub57, Sub58, Sub66
	common /hgaga_varXs/ Sub60, Sub62, Sub61, Sub69, Sub70
	common /hgaga_varXs/ Sub73, Sub76, Sub71, Sub74, Sub77
	common /hgaga_varXs/ Sub83, Sub8, Sub12, Sub7, Sub11, Sub24
	common /hgaga_varXs/ Sub28, Sub23, Sub27, Sub44, Sub40
	common /hgaga_varXs/ Sub41, Sub45, Sub13, Sub25, Sub29
	common /hgaga_varXs/ Sub42, Sub46, Sub9, Sub15, Sub31, Sub48
	common /hgaga_varXs/ Sub10, Sub14, Sub26, Sub30, Sub47
	common /hgaga_varXs/ Sub43, Sub18, Sub17, Sub34, Sub33
	common /hgaga_varXs/ Sub51, Sub50, Sub32, Sub16, Sub49, Sub4
	common /hgaga_varXs/ Sub19, Sub22, Sub35, Sub39, Sub52
	common /hgaga_varXs/ Sub20, Sub36, Sub53, Sub94, Sub67
	common /hgaga_varXs/ Sub63, Sub64, Sub68, Sub2, Sub54, Sub37
	common /hgaga_varXs/ Sub65, pave1, pave2, pave3, pave4
	common /hgaga_varXs/ pave5, pave6, pave7, pave8, pave9
	common /hgaga_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hgaga_varXs/ pave15, pave16, pave17, pave18

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb7, Abb3, Abb4, Abb5
	ComplexType Abb2, Abb1, Sub99, Sub95, Sub98, Sub87, Sub88, Sub89
	ComplexType Sub92, Sub79, Sub82, Sub3(6)
	ComplexType Sub38(6), Sub80(3), Sub81(3)
	ComplexType Sub55(6,3,3), Sub90, Sub91, Sub59(2)
	ComplexType Sub72(3), Sub75(3), Sub78(3)
	ComplexType Sub56(6,3,3), Sub93
	common /hgaga_varXh/ Pair1, Pair2, Pair3, Eps1, Abb7, Abb3
	common /hgaga_varXh/ Abb4, Abb5, Abb2, Abb1, Sub99, Sub95
	common /hgaga_varXh/ Sub98, Sub87, Sub88, Sub89, Sub92
	common /hgaga_varXh/ Sub79, Sub82, Sub3, Sub38, Sub80, Sub81
	common /hgaga_varXh/ Sub55, Sub90, Sub91, Sub59, Sub72
	common /hgaga_varXh/ Sub75, Sub78, Sub56, Sub93

	integer seq(2), Hel(3)
	common /hgaga_helind/ seq, Hel

	integer All4, Cha4, Gen4, Ind1, Ind2
	common /hgaga_indices/ All4, Cha4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	common /hgaga_formfactors/ Cloop

#endif
