* vars.h
* variable declarations
* generated by FormCalc 12 Apr 2013 15:13

#include "decl.h"

	double precision S, T, U
	common /kinvars/ S, T, U

	integer Hel(4)
	common /kinvars/ Hel

	double complex F3, F6, F35, F37, F42, F47, F49, F54, F32, F81
	double complex F82, F33, F83, F84, F36, F48, Pair4, Pair8
	double complex Pair11, Pair9, Pair10, Eps12, Eps13, Abb14
	double complex Abb15, Abb111, Abb112, Abb122, Abb123, Abb22
	double complex Abb23, Abb38, Abb50, Abb85, Abb86, Abb39, Abb51
	double complex Abb87, Abb88, Abb16, Abb71, Abb76, Abb24, Abb5
	double complex Abb43, Abb55, Abb7, Abb44, Abb56, Abb89, Abb90
	double complex Abb17, Abb72, Abb77, Abb25, Abb40, Abb52, Abb91
	double complex Abb92, Abb18, Abb73, Abb78, Abb26, Abb19, Abb74
	double complex Abb79, Abb27, AbbSum243, AbbSum201, AbbSum368
	double complex AbbSum437, AbbSum410, AbbSum407, AbbSum428
	double complex AbbSum768, AbbSum748, AbbSum750, AbbSum564
	double complex AbbSum624, AbbSum622, AbbSum630, AbbSum626
	double complex AbbSum401, AbbSum728, AbbSum260, AbbSum224
	double complex AbbSum863, AbbSum269, AbbSum265, AbbSum270
	double complex AbbSum273, AbbSum378, AbbSum640, AbbSum766
	double complex AbbSum553, AbbSum736, AbbSum30, AbbSum20
	double complex AbbSum21, AbbSum849, AbbSum434, AbbSum245
	double complex AbbSum207, AbbSum247, AbbSum229, AbbSum208
	double complex AbbSum185, AbbSum246, AbbSum259, AbbSum250
	double complex AbbSum253, AbbSum244, AbbSum254, AbbSum206
	double complex AbbSum369, AbbSum249, AbbSum641, AbbSum440
	double complex AbbSum413, AbbSum409, AbbSum636, AbbSum916
	double complex AbbSum893, AbbSum601, AbbSum632, AbbSum634
	double complex AbbSum918, AbbSum195, AbbSum255, AbbSum248
	double complex AbbSum263, AbbSum230, AbbSum219, AbbSum431
	double complex AbbSum769, AbbSum749, AbbSum751, AbbSum567
	double complex AbbSum625, AbbSum623, AbbSum631, AbbSum628
	double complex AbbSum404, AbbSum729, AbbSum262, AbbSum228
	double complex AbbSum864, AbbSum264, AbbSum894, AbbSum261
	double complex AbbSum917, AbbSum220, AbbSum602, AbbSum919
	double complex AbbSum907, AbbSum101, AbbSum637, AbbSum635
	double complex AbbSum633, AbbSum256, AbbSum196, AbbSum642
	double complex AbbSum644, AbbSum271, AbbSum267, AbbSum272
	double complex AbbSum274, AbbSum379, AbbSum643, AbbSum645
	double complex AbbSum767, AbbSum554, AbbSum737, AbbSum31
	double complex AbbSum28, AbbSum29, AbbSum850, AbbSum436
	double complex AbbSum443, AbbSum857, AbbSum175, AbbSum561
	double complex AbbSum312, AbbSum865, AbbSum157, AbbSum568
	double complex AbbSum149, AbbSum730, AbbSum618, AbbSum595
	double complex AbbSum58, AbbSum151, AbbSum752, AbbSum104
	double complex AbbSum1137, AbbSum133, AbbSum66, AbbSum620
	double complex AbbSum1048, AbbSum538, AbbSum139, AbbSum446
	double complex AbbSum856, AbbSum846, AbbSum432, AbbSum559
	double complex AbbSum548, AbbSum537, AbbSum237, AbbSum211
	double complex AbbSum94, AbbSum332, AbbSum217, AbbSum131
	double complex AbbSum574, AbbSum441, AbbSum770, AbbSum485
	double complex AbbSum461, AbbSum147, AbbSum872, AbbSum788
	double complex AbbSum534, AbbSum239, AbbSum835, AbbSum141
	double complex AbbSum854, AbbSum844, AbbSum137, AbbSum127
	double complex AbbSum702, AbbSum550, AbbSum690, AbbSum405
	double complex AbbSum210, AbbSum132, AbbSum776, AbbSum453
	double complex AbbSum414, AbbSum59, AbbSum325, AbbSum125
	double complex AbbSum370, AbbSum241, AbbSum129, AbbSum145
	double complex AbbSum1084, AbbSum69, AbbSum142, AbbSum155
	double complex AbbSum991, AbbSum153, AbbSum523, AbbSum782
	double complex AbbSum376, AbbSum380, AbbSum885, AbbSum586
	double complex AbbSum880, AbbSum581, AbbSum1059, AbbSum886
	double complex AbbSum444, AbbSum425, AbbSum438, AbbSum862
	double complex AbbSum587, AbbSum236, AbbSum180, AbbSum527
	double complex AbbSum565, AbbSum563, AbbSum616, AbbSum317
	double complex AbbSum396, AbbSum411, AbbSum670, AbbSum866
	double complex AbbSum306, AbbSum1080, AbbSum234, AbbSum912
	double complex AbbSum365, AbbSum617, AbbSum158, AbbSum307
	double complex AbbSum1081, AbbSum671, AbbSum569, AbbSum966
	double complex AbbSum611, AbbSum726, AbbSum150, AbbSum373
	double complex AbbSum731, AbbSum381, AbbSum619, AbbSum597
	double complex AbbSum60, AbbSum727, AbbSum152, AbbSum793
	double complex AbbSum753, AbbSum747, AbbSum789, AbbSum873
	double complex AbbSum115, AbbSum1142, AbbSum757, AbbSum136
	double complex AbbSum1060, AbbSum388, AbbSum67, AbbSum805
	double complex AbbSum621, AbbSum1049, AbbSum1146, AbbSum541
	double complex AbbSum758, AbbSum140, AbbSum403, AbbSum855
	double complex AbbSum836, AbbSum560, AbbSum549, AbbSum1178
	double complex AbbSum422, AbbSum536, AbbSum575, AbbSum462
	double complex AbbSum1025, AbbSum492, AbbSum448, AbbSum558
	double complex AbbSum426, AbbSum861, AbbSum439, AbbSum848
	double complex AbbSum433, AbbSum435, AbbSum419, AbbSum430
	double complex AbbSum562, AbbSum543, AbbSum551, AbbSum540
	double complex AbbSum764, AbbSum467, AbbSum238, AbbSum528
	double complex AbbSum609, AbbSum322, AbbSum845, AbbSum215
	double complex AbbSum1147, AbbSum566, AbbSum98, AbbSum547
	double complex AbbSum393, AbbSum337, AbbSum218, AbbSum134
	double complex AbbSum577, AbbSum442, AbbSum771, AbbSum488
	double complex AbbSum464, AbbSum148, AbbSum876, AbbSum791
	double complex AbbSum539, AbbSum418, AbbSum240, AbbSum838
	double complex AbbSum853, AbbSum143, AbbSum1179, AbbSum535
	double complex AbbSum860, AbbSum847, AbbSum138, AbbSum429
	double complex AbbSum128, AbbSum397, AbbSum707, AbbSum552
	double complex AbbSum412, AbbSum693, AbbSum406, AbbSum408
	double complex AbbSum214, AbbSum135, AbbSum765, AbbSum576
	double complex AbbSum463, AbbSum777, AbbSum226, AbbSum834
	double complex AbbSum343, AbbSum843, AbbSum454, AbbSum720
	double complex AbbSum361, AbbSum582, AbbSum415, AbbSum402
	double complex AbbSum61, AbbSum327, AbbSum684, AbbSum126
	double complex AbbSum913, AbbSum390, AbbSum176, AbbSum371
	double complex AbbSum366, AbbSum242, AbbSum130, AbbSum721
	double complex AbbSum146, AbbSum1085, AbbSum70, AbbSum144
	double complex AbbSum156, AbbSum992, AbbSum154, AbbSum362
	double complex AbbSum525, AbbSum227, AbbSum685, AbbSum881
	double complex AbbSum746, AbbSum790, AbbSum874, AbbSum344
	double complex AbbSum783, AbbSum326, AbbSum386, AbbSum399
	double complex AbbSum382, AbbSum754, AbbSum68, AbbSum755
	double complex AbbSum383, AbbSum400, AbbSum387, AbbSum416
	double complex AbbSum251, AbbSum315, AbbSum186, AbbSum212
	double complex AbbSum920, AbbSum627, AbbSum677, AbbSum1122
	double complex AbbSum891, AbbSum599, AbbSum257, AbbSum197
	double complex AbbSum350, AbbSum266, AbbSum889, AbbSum96
	double complex AbbSum705, AbbSum638, AbbSum815, AbbSum895
	double complex AbbSum908, AbbSum113, AbbSum75, AbbSum914
	double complex AbbSum97, AbbSum1038, AbbSum507, AbbSum252
	double complex AbbSum319, AbbSum187, AbbSum216, AbbSum921
	double complex AbbSum629, AbbSum679, AbbSum1125, AbbSum892
	double complex AbbSum600, AbbSum258, AbbSum198, AbbSum351
	double complex AbbSum268, AbbSum890, AbbSum99, AbbSum709
	double complex AbbSum639, AbbSum818, AbbSum896, AbbSum909
	double complex AbbSum124, AbbSum80, AbbSum915, AbbSum100
	double complex AbbSum1041, AbbSum511, AbbSum934, AbbSum948
	double complex AbbSum375, AbbSum724, AbbSum936, AbbSum949
	double complex AbbSum377, AbbSum725, AbbSum424, AbbSum744
	double complex AbbSum584, AbbSum883, AbbSum580, AbbSum879
	double complex AbbSum903, AbbSum364, AbbSum734, AbbSum928
	double complex AbbSum925, AbbSum165, AbbSum231, AbbSum588
	double complex AbbSum612, AbbSum395, AbbSum762, AbbSum1076
	double complex AbbSum1078, AbbSum932, AbbSum944, AbbSum526
	double complex AbbSum827, AbbSum924, AbbSum304, AbbSum668
	double complex AbbSum1058, AbbSum585, AbbSum884, AbbSum1079
	double complex AbbSum427, AbbSum745, AbbSum583, AbbSum882
	double complex AbbSum904, AbbSum367, AbbSum735, AbbSum305
	double complex AbbSum167, AbbSum235, AbbSum669, AbbSum590
	double complex AbbSum615, AbbSum398, AbbSum763, AbbSum931
	double complex AbbSum1077, AbbSum933, AbbSum946, AbbSum529
	double complex AbbSum828, AbbSum929, AbbSum930, AbbSum926
	double complex AbbSum927, AbbSum1061, AbbSum967, AbbSum341
	double complex AbbSum688, AbbSum942, AbbSum954, AbbSum172
	double complex AbbSum732, AbbSum922, AbbSum910, AbbSum938
	double complex AbbSum1051, AbbSum1043, AbbSum518, AbbSum985
	double complex AbbSum360, AbbSum202, AbbSum309, AbbSum389
	double complex AbbSum1042, AbbSum970, AbbSum943, AbbSum955
	double complex AbbSum1052, AbbSum177, AbbSum733, AbbSum941
	double complex AbbSum988, AbbSum363, AbbSum308, AbbSum340
	double complex AbbSum497, AbbSum689, AbbSum923, AbbSum911
	double complex AbbSum203, AbbSum1027, AbbSum391, AbbSum103
	double complex AbbSum114, AbbSum496, AbbSum519, AbbSum960
	double complex AbbSum1094, AbbSum1174, AbbSum1176, AbbSum760
	double complex AbbSum962, AbbSum901, AbbSum979, AbbSum740
	double complex AbbSum981, AbbSum973, AbbSum358, AbbSum718
	double complex AbbSum320, AbbSum682, AbbSum421, AbbSum346
	double complex AbbSum512, AbbSum819, AbbSum672, AbbSum694
	double complex AbbSum1062, AbbSum1066, AbbSum897, AbbSum722
	double complex AbbSum372, AbbSum329, AbbSum603, AbbSum1024
	double complex AbbSum491, AbbSum742, AbbSum572, AbbSum870
	double complex AbbSum1070, AbbSum950, AbbSum1003, AbbSum417
	double complex AbbSum466, AbbSum542, AbbSum839, AbbSum756
	double complex AbbSum209, AbbSum792, AbbSum459, AbbSum786
	double complex AbbSum995, AbbSum289, AbbSum656, AbbSum281
	double complex AbbSum648, AbbSum607, AbbSum223, AbbSum297
	double complex AbbSum661, AbbSum392, AbbSum1014, AbbSum481
	double complex AbbSum821, AbbSum977, AbbSum596, AbbSum958
	double complex AbbSum851, AbbSum556, AbbSum1092, AbbSum1167
	double complex AbbSum804, AbbSum1145, AbbSum1109, AbbSum557
	double complex AbbSum801, AbbSum1126, AbbSum1177, AbbSum486
	double complex AbbSum807, AbbSum1166, AbbSum1133, AbbSum1134
	double complex AbbSum1150, AbbSum832, AbbSum532, AbbSum809
	double complex AbbSum961, AbbSum1087, AbbSum1096, AbbSum1175
	double complex AbbSum761, AbbSum1116, AbbSum1113, AbbSum95
	double complex AbbSum810, AbbSum1155, AbbSum822, AbbSum965
	double complex AbbSum902, AbbSum980, AbbSum741, AbbSum695
	double complex AbbSum1067, AbbSum1063, AbbSum604, AbbSum984
	double complex AbbSum976, AbbSum359, AbbSum719, AbbSum282
	double complex AbbSum649, AbbSum298, AbbSum662, AbbSum225
	double complex AbbSum347, AbbSum423, AbbSum899, AbbSum1031
	double complex AbbSum712, AbbSum842, AbbSum545, AbbSum93
	double complex AbbSum808, AbbSum546, AbbSum841, AbbSum500
	double complex AbbSum1030, AbbSum501, AbbSum673, AbbSum608
	double complex AbbSum698, AbbSum354, AbbSum711, AbbSum188
	double complex AbbSum833, AbbSum533, AbbSum1130, AbbSum330
	double complex AbbSum355, AbbSum513, AbbSum820, AbbSum1151
	double complex AbbSum321, AbbSum800, AbbSum1107, AbbSum898
	double complex AbbSum723, AbbSum374, AbbSum1026, AbbSum495
	double complex AbbSum1015, AbbSum743, AbbSum683, AbbSum1071
	double complex AbbSum953, AbbSum1005, AbbSum420, AbbSum469
	double complex AbbSum544, AbbSum840, AbbSum759, AbbSum213
	double complex AbbSum794, AbbSum291, AbbSum657, AbbSum394
	double complex AbbSum900, AbbSum1117, AbbSum699, AbbSum1156
	double complex AbbSum978, AbbSum598, AbbSum959, AbbSum996
	double complex AbbSum1102, AbbSum806, AbbSum573, AbbSum871
	double complex AbbSum852, AbbSum460, AbbSum787, AbbSum1149
	double complex AbbSum1110, AbbSum384, AbbSum489, AbbSum738
	double complex AbbSum159, AbbSum455, AbbSum477, AbbSum686
	double complex AbbSum449, AbbSum570, AbbSum1172, AbbSum456
	double complex AbbSum473, AbbSum578, AbbSum465, AbbSum798
	double complex AbbSum490, AbbSum774, AbbSum778, AbbSum447
	double complex AbbSum1148, AbbSum875, AbbSum334, AbbSum784
	double complex AbbSum877, AbbSum867, AbbSum716, AbbSum831
	double complex AbbSum878, AbbSum1035, AbbSum666, AbbSum1013
	double complex AbbSum592, AbbSum170, AbbSum858, AbbSum1144
	double complex AbbSum385, AbbSum681, AbbSum1021, AbbSum1012
	double complex AbbSum1001, AbbSum775, AbbSum493, AbbSum530
	double complex AbbSum517, AbbSum830, AbbSum46, AbbSum1010
	double complex AbbSum302, AbbSum739, AbbSum1000, AbbSum1022
	double complex AbbSum1019, AbbSum1020, AbbSum859, AbbSum1056
	double complex AbbSum161, AbbSum687, AbbSum1101, AbbSum555
	double complex AbbSum593, AbbSum837, AbbSum1091, AbbSum571
	double complex AbbSum445, AbbSum450, AbbSum475, AbbSum1036
	double complex AbbSum1161, AbbSum516, AbbSum458, AbbSum1140
	double complex AbbSum474, AbbSum680, AbbSum468, AbbSum710
	double complex AbbSum515, AbbSum799, AbbSum660, AbbSum476
	double complex AbbSum200, AbbSum222, AbbSum323, AbbSum328
	double complex AbbSum1173, AbbSum457, AbbSum494, AbbSum294
	double complex AbbSum352, AbbSum168, AbbSum279, AbbSum296
	double complex AbbSum34, AbbSum1165, AbbSum478, AbbSum1154
	double complex AbbSum479, AbbSum221, AbbSum869, AbbSum579
	double complex AbbSum480, AbbSum779, AbbSum829, AbbSum993
	double complex AbbSum102, AbbSum1086, AbbSum199, AbbSum280
	double complex AbbSum610, AbbSum1106, AbbSum531, AbbSum1008
	double complex AbbSum470, AbbSum514, AbbSum353, AbbSum1164
	double complex AbbSum994, AbbSum795, AbbSum1050, AbbSum1132
	double complex AbbSum295, AbbSum785, AbbSum324, AbbSum868
	double complex AbbSum1009, AbbSum989, AbbSum471, AbbSum814
	double complex AbbSum1139, AbbSum1097, AbbSum292, AbbSum310
	double complex AbbSum1082, AbbSum796, AbbSum1033, AbbSum62
	double complex AbbSum1111, AbbSum1055, AbbSum63, AbbSum1089
	double complex AbbSum591, AbbSum1121, AbbSum658, AbbSum169
	double complex AbbSum802, AbbSum701, AbbSum887, AbbSum1028
	double complex AbbSum905, AbbSum772, AbbSum665, AbbSum652
	double complex AbbSum41, AbbSum1103, AbbSum1118, AbbSum1136
	double complex AbbSum107, AbbSum163, AbbSum646, AbbSum675
	double complex AbbSum696, AbbSum275, AbbSum284, AbbSum451
	double complex AbbSum105, AbbSum181, AbbSum1006, AbbSum182
	double complex AbbSum277, AbbSum311, AbbSum106, AbbSum173
	double complex AbbSum703, AbbSum971, AbbSum700, AbbSum1044
	double complex AbbSum520, AbbSum674, AbbSum1064, AbbSum1068
	double complex AbbSum963, AbbSum1120, AbbSum968, AbbSum982
	double complex AbbSum498, AbbSum1034, AbbSum823, AbbSum1152
	double complex AbbSum204, AbbSum174, AbbSum1104, AbbSum714
	double complex AbbSum505, AbbSum1168, AbbSum506, AbbSum986
	double complex AbbSum824, AbbSum812, AbbSum1045, AbbSum482
	double complex AbbSum1159, AbbSum1128, AbbSum1127, AbbSum1158
	double complex AbbSum503, AbbSum484, AbbSum811, AbbSum521
	double complex AbbSum605, AbbSum110, AbbSum1032, AbbSum191
	double complex AbbSum1157, AbbSum190, AbbSum108, AbbSum301
	double complex AbbSum45, AbbSum653, AbbSum189, AbbSum109
	double complex AbbSum1112, AbbSum935, AbbSum945, AbbSum780
	double complex AbbSum335, AbbSum336, AbbSum313, AbbSum286
	double complex AbbSum160, AbbSum342, AbbSum348, AbbSum1017
	double complex AbbSum1072, AbbSum997, AbbSum1016, AbbSum502
	double complex AbbSum1099, AbbSum1011, AbbSum825, AbbSum803
	double complex AbbSum499, AbbSum1119, AbbSum990, AbbSum472
	double complex AbbSum1153, AbbSum1143, AbbSum1098, AbbSum293
	double complex AbbSum205, AbbSum704, AbbSum314, AbbSum1095
	double complex AbbSum1083, AbbSum797, AbbSum1040, AbbSum64
	double complex AbbSum1114, AbbSum522, AbbSum1105, AbbSum1057
	double complex AbbSum65, AbbSum283, AbbSum331, AbbSum290
	double complex AbbSum232, AbbSum233, AbbSum1093, AbbSum594
	double complex AbbSum1124, AbbSum659, AbbSum171, AbbSum1004
	double complex AbbSum888, AbbSum1029, AbbSum906, AbbSum773
	double complex AbbSum667, AbbSum654, AbbSum53, AbbSum1108
	double complex AbbSum1123, AbbSum1141, AbbSum118, AbbSum164
	double complex AbbSum647, AbbSum678, AbbSum697, AbbSum483
	double complex AbbSum276, AbbSum287, AbbSum452, AbbSum116
	double complex AbbSum183, AbbSum1007, AbbSum184, AbbSum278
	double complex AbbSum316, AbbSum117, AbbSum178, AbbSum708
	double complex AbbSum972, AbbSum706, AbbSum1047, AbbSum1037
	double complex AbbSum524, AbbSum299, AbbSum356, AbbSum1074
	double complex AbbSum999, AbbSum692, AbbSum651, AbbSum956
	double complex AbbSum589, AbbSum951, AbbSum974, AbbSum952
	double complex AbbSum691, AbbSum650, AbbSum1053, AbbSum1073
	double complex AbbSum998, AbbSum663, AbbSum179, AbbSum713
	double complex AbbSum717, AbbSum509, AbbSum1171, AbbSum510
	double complex AbbSum349, AbbSum1054, AbbSum664, AbbSum715
	double complex AbbSum1065, AbbSum826, AbbSum817, AbbSum1046
	double complex AbbSum1069, AbbSum1131, AbbSum1163, AbbSum1169
	double complex AbbSum676, AbbSum1160, AbbSum508, AbbSum487
	double complex AbbSum816, AbbSum1135, AbbSum964, AbbSum606
	double complex AbbSum121, AbbSum987, AbbSum969, AbbSum983
	double complex AbbSum1039, AbbSum194, AbbSum1162, AbbSum193
	double complex AbbSum1129, AbbSum119, AbbSum303, AbbSum57
	double complex AbbSum655, AbbSum192, AbbSum120, AbbSum614
	double complex AbbSum613, AbbSum1090, AbbSum1115, AbbSum937
	double complex AbbSum947, AbbSum781, AbbSum338, AbbSum339
	double complex AbbSum318, AbbSum288, AbbSum162, AbbSum345
	double complex AbbSum1088, AbbSum957, AbbSum939, AbbSum975
	double complex AbbSum166, AbbSum940, AbbSum1075, AbbSum1002
	double complex AbbSum357, AbbSum300, AbbSum333, AbbSum285
	double complex AbbSum813, AbbSum504, AbbSum1023, AbbSum1138
	double complex AbbSum1018, AbbSum1100, AbbSum1170
	common /abbrev/ F3, F6, F35, F37, F42, F47, F49, F54, F32, F81
	common /abbrev/ F82, F33, F83, F84, F36, F48, Pair4, Pair8
	common /abbrev/ Pair11, Pair9, Pair10, Eps12, Eps13, Abb14
	common /abbrev/ Abb15, Abb111, Abb112, Abb122, Abb123, Abb22
	common /abbrev/ Abb23, Abb38, Abb50, Abb85, Abb86, Abb39
	common /abbrev/ Abb51, Abb87, Abb88, Abb16, Abb71, Abb76
	common /abbrev/ Abb24, Abb5, Abb43, Abb55, Abb7, Abb44, Abb56
	common /abbrev/ Abb89, Abb90, Abb17, Abb72, Abb77, Abb25
	common /abbrev/ Abb40, Abb52, Abb91, Abb92, Abb18, Abb73
	common /abbrev/ Abb78, Abb26, Abb19, Abb74, Abb79, Abb27
	common /abbrev/ AbbSum243, AbbSum201, AbbSum368, AbbSum437
	common /abbrev/ AbbSum410, AbbSum407, AbbSum428, AbbSum768
	common /abbrev/ AbbSum748, AbbSum750, AbbSum564, AbbSum624
	common /abbrev/ AbbSum622, AbbSum630, AbbSum626, AbbSum401
	common /abbrev/ AbbSum728, AbbSum260, AbbSum224, AbbSum863
	common /abbrev/ AbbSum269, AbbSum265, AbbSum270, AbbSum273
	common /abbrev/ AbbSum378, AbbSum640, AbbSum766, AbbSum553
	common /abbrev/ AbbSum736, AbbSum30, AbbSum20, AbbSum21
	common /abbrev/ AbbSum849, AbbSum434, AbbSum245, AbbSum207
	common /abbrev/ AbbSum247, AbbSum229, AbbSum208, AbbSum185
	common /abbrev/ AbbSum246, AbbSum259, AbbSum250, AbbSum253
	common /abbrev/ AbbSum244, AbbSum254, AbbSum206, AbbSum369
	common /abbrev/ AbbSum249, AbbSum641, AbbSum440, AbbSum413
	common /abbrev/ AbbSum409, AbbSum636, AbbSum916, AbbSum893
	common /abbrev/ AbbSum601, AbbSum632, AbbSum634, AbbSum918
	common /abbrev/ AbbSum195, AbbSum255, AbbSum248, AbbSum263
	common /abbrev/ AbbSum230, AbbSum219, AbbSum431, AbbSum769
	common /abbrev/ AbbSum749, AbbSum751, AbbSum567, AbbSum625
	common /abbrev/ AbbSum623, AbbSum631, AbbSum628, AbbSum404
	common /abbrev/ AbbSum729, AbbSum262, AbbSum228, AbbSum864
	common /abbrev/ AbbSum264, AbbSum894, AbbSum261, AbbSum917
	common /abbrev/ AbbSum220, AbbSum602, AbbSum919, AbbSum907
	common /abbrev/ AbbSum101, AbbSum637, AbbSum635, AbbSum633
	common /abbrev/ AbbSum256, AbbSum196, AbbSum642, AbbSum644
	common /abbrev/ AbbSum271, AbbSum267, AbbSum272, AbbSum274
	common /abbrev/ AbbSum379, AbbSum643, AbbSum645, AbbSum767
	common /abbrev/ AbbSum554, AbbSum737, AbbSum31, AbbSum28
	common /abbrev/ AbbSum29, AbbSum850, AbbSum436, AbbSum443
	common /abbrev/ AbbSum857, AbbSum175, AbbSum561, AbbSum312
	common /abbrev/ AbbSum865, AbbSum157, AbbSum568, AbbSum149
	common /abbrev/ AbbSum730, AbbSum618, AbbSum595, AbbSum58
	common /abbrev/ AbbSum151, AbbSum752, AbbSum104, AbbSum1137
	common /abbrev/ AbbSum133, AbbSum66, AbbSum620, AbbSum1048
	common /abbrev/ AbbSum538, AbbSum139, AbbSum446, AbbSum856
	common /abbrev/ AbbSum846, AbbSum432, AbbSum559, AbbSum548
	common /abbrev/ AbbSum537, AbbSum237, AbbSum211, AbbSum94
	common /abbrev/ AbbSum332, AbbSum217, AbbSum131, AbbSum574
	common /abbrev/ AbbSum441, AbbSum770, AbbSum485, AbbSum461
	common /abbrev/ AbbSum147, AbbSum872, AbbSum788, AbbSum534
	common /abbrev/ AbbSum239, AbbSum835, AbbSum141, AbbSum854
	common /abbrev/ AbbSum844, AbbSum137, AbbSum127, AbbSum702
	common /abbrev/ AbbSum550, AbbSum690, AbbSum405, AbbSum210
	common /abbrev/ AbbSum132, AbbSum776, AbbSum453, AbbSum414
	common /abbrev/ AbbSum59, AbbSum325, AbbSum125, AbbSum370
	common /abbrev/ AbbSum241, AbbSum129, AbbSum145, AbbSum1084
	common /abbrev/ AbbSum69, AbbSum142, AbbSum155, AbbSum991
	common /abbrev/ AbbSum153, AbbSum523, AbbSum782, AbbSum376
	common /abbrev/ AbbSum380, AbbSum885, AbbSum586, AbbSum880
	common /abbrev/ AbbSum581, AbbSum1059, AbbSum886, AbbSum444
	common /abbrev/ AbbSum425, AbbSum438, AbbSum862, AbbSum587
	common /abbrev/ AbbSum236, AbbSum180, AbbSum527, AbbSum565
	common /abbrev/ AbbSum563, AbbSum616, AbbSum317, AbbSum396
	common /abbrev/ AbbSum411, AbbSum670, AbbSum866, AbbSum306
	common /abbrev/ AbbSum1080, AbbSum234, AbbSum912, AbbSum365
	common /abbrev/ AbbSum617, AbbSum158, AbbSum307, AbbSum1081
	common /abbrev/ AbbSum671, AbbSum569, AbbSum966, AbbSum611
	common /abbrev/ AbbSum726, AbbSum150, AbbSum373, AbbSum731
	common /abbrev/ AbbSum381, AbbSum619, AbbSum597, AbbSum60
	common /abbrev/ AbbSum727, AbbSum152, AbbSum793, AbbSum753
	common /abbrev/ AbbSum747, AbbSum789, AbbSum873, AbbSum115
	common /abbrev/ AbbSum1142, AbbSum757, AbbSum136, AbbSum1060
	common /abbrev/ AbbSum388, AbbSum67, AbbSum805, AbbSum621
	common /abbrev/ AbbSum1049, AbbSum1146, AbbSum541, AbbSum758
	common /abbrev/ AbbSum140, AbbSum403, AbbSum855, AbbSum836
	common /abbrev/ AbbSum560, AbbSum549, AbbSum1178, AbbSum422
	common /abbrev/ AbbSum536, AbbSum575, AbbSum462, AbbSum1025
	common /abbrev/ AbbSum492, AbbSum448, AbbSum558, AbbSum426
	common /abbrev/ AbbSum861, AbbSum439, AbbSum848, AbbSum433
	common /abbrev/ AbbSum435, AbbSum419, AbbSum430, AbbSum562
	common /abbrev/ AbbSum543, AbbSum551, AbbSum540, AbbSum764
	common /abbrev/ AbbSum467, AbbSum238, AbbSum528, AbbSum609
	common /abbrev/ AbbSum322, AbbSum845, AbbSum215, AbbSum1147
	common /abbrev/ AbbSum566, AbbSum98, AbbSum547, AbbSum393
	common /abbrev/ AbbSum337, AbbSum218, AbbSum134, AbbSum577
	common /abbrev/ AbbSum442, AbbSum771, AbbSum488, AbbSum464
	common /abbrev/ AbbSum148, AbbSum876, AbbSum791, AbbSum539
	common /abbrev/ AbbSum418, AbbSum240, AbbSum838, AbbSum853
	common /abbrev/ AbbSum143, AbbSum1179, AbbSum535, AbbSum860
	common /abbrev/ AbbSum847, AbbSum138, AbbSum429, AbbSum128
	common /abbrev/ AbbSum397, AbbSum707, AbbSum552, AbbSum412
	common /abbrev/ AbbSum693, AbbSum406, AbbSum408, AbbSum214
	common /abbrev/ AbbSum135, AbbSum765, AbbSum576, AbbSum463
	common /abbrev/ AbbSum777, AbbSum226, AbbSum834, AbbSum343
	common /abbrev/ AbbSum843, AbbSum454, AbbSum720, AbbSum361
	common /abbrev/ AbbSum582, AbbSum415, AbbSum402, AbbSum61
	common /abbrev/ AbbSum327, AbbSum684, AbbSum126, AbbSum913
	common /abbrev/ AbbSum390, AbbSum176, AbbSum371, AbbSum366
	common /abbrev/ AbbSum242, AbbSum130, AbbSum721, AbbSum146
	common /abbrev/ AbbSum1085, AbbSum70, AbbSum144, AbbSum156
	common /abbrev/ AbbSum992, AbbSum154, AbbSum362, AbbSum525
	common /abbrev/ AbbSum227, AbbSum685, AbbSum881, AbbSum746
	common /abbrev/ AbbSum790, AbbSum874, AbbSum344, AbbSum783
	common /abbrev/ AbbSum326, AbbSum386, AbbSum399, AbbSum382
	common /abbrev/ AbbSum754, AbbSum68, AbbSum755, AbbSum383
	common /abbrev/ AbbSum400, AbbSum387, AbbSum416, AbbSum251
	common /abbrev/ AbbSum315, AbbSum186, AbbSum212, AbbSum920
	common /abbrev/ AbbSum627, AbbSum677, AbbSum1122, AbbSum891
	common /abbrev/ AbbSum599, AbbSum257, AbbSum197, AbbSum350
	common /abbrev/ AbbSum266, AbbSum889, AbbSum96, AbbSum705
	common /abbrev/ AbbSum638, AbbSum815, AbbSum895, AbbSum908
	common /abbrev/ AbbSum113, AbbSum75, AbbSum914, AbbSum97
	common /abbrev/ AbbSum1038, AbbSum507, AbbSum252, AbbSum319
	common /abbrev/ AbbSum187, AbbSum216, AbbSum921, AbbSum629
	common /abbrev/ AbbSum679, AbbSum1125, AbbSum892, AbbSum600
	common /abbrev/ AbbSum258, AbbSum198, AbbSum351, AbbSum268
	common /abbrev/ AbbSum890, AbbSum99, AbbSum709, AbbSum639
	common /abbrev/ AbbSum818, AbbSum896, AbbSum909, AbbSum124
	common /abbrev/ AbbSum80, AbbSum915, AbbSum100, AbbSum1041
	common /abbrev/ AbbSum511, AbbSum934, AbbSum948, AbbSum375
	common /abbrev/ AbbSum724, AbbSum936, AbbSum949, AbbSum377
	common /abbrev/ AbbSum725, AbbSum424, AbbSum744, AbbSum584
	common /abbrev/ AbbSum883, AbbSum580, AbbSum879, AbbSum903
	common /abbrev/ AbbSum364, AbbSum734, AbbSum928, AbbSum925
	common /abbrev/ AbbSum165, AbbSum231, AbbSum588, AbbSum612
	common /abbrev/ AbbSum395, AbbSum762, AbbSum1076, AbbSum1078
	common /abbrev/ AbbSum932, AbbSum944, AbbSum526, AbbSum827
	common /abbrev/ AbbSum924, AbbSum304, AbbSum668, AbbSum1058
	common /abbrev/ AbbSum585, AbbSum884, AbbSum1079, AbbSum427
	common /abbrev/ AbbSum745, AbbSum583, AbbSum882, AbbSum904
	common /abbrev/ AbbSum367, AbbSum735, AbbSum305, AbbSum167
	common /abbrev/ AbbSum235, AbbSum669, AbbSum590, AbbSum615
	common /abbrev/ AbbSum398, AbbSum763, AbbSum931, AbbSum1077
	common /abbrev/ AbbSum933, AbbSum946, AbbSum529, AbbSum828
	common /abbrev/ AbbSum929, AbbSum930, AbbSum926, AbbSum927
	common /abbrev/ AbbSum1061, AbbSum967, AbbSum341, AbbSum688
	common /abbrev/ AbbSum942, AbbSum954, AbbSum172, AbbSum732
	common /abbrev/ AbbSum922, AbbSum910, AbbSum938, AbbSum1051
	common /abbrev/ AbbSum1043, AbbSum518, AbbSum985, AbbSum360
	common /abbrev/ AbbSum202, AbbSum309, AbbSum389, AbbSum1042
	common /abbrev/ AbbSum970, AbbSum943, AbbSum955, AbbSum1052
	common /abbrev/ AbbSum177, AbbSum733, AbbSum941, AbbSum988
	common /abbrev/ AbbSum363, AbbSum308, AbbSum340, AbbSum497
	common /abbrev/ AbbSum689, AbbSum923, AbbSum911, AbbSum203
	common /abbrev/ AbbSum1027, AbbSum391, AbbSum103, AbbSum114
	common /abbrev/ AbbSum496, AbbSum519, AbbSum960, AbbSum1094
	common /abbrev/ AbbSum1174, AbbSum1176, AbbSum760, AbbSum962
	common /abbrev/ AbbSum901, AbbSum979, AbbSum740, AbbSum981
	common /abbrev/ AbbSum973, AbbSum358, AbbSum718, AbbSum320
	common /abbrev/ AbbSum682, AbbSum421, AbbSum346, AbbSum512
	common /abbrev/ AbbSum819, AbbSum672, AbbSum694, AbbSum1062
	common /abbrev/ AbbSum1066, AbbSum897, AbbSum722, AbbSum372
	common /abbrev/ AbbSum329, AbbSum603, AbbSum1024, AbbSum491
	common /abbrev/ AbbSum742, AbbSum572, AbbSum870, AbbSum1070
	common /abbrev/ AbbSum950, AbbSum1003, AbbSum417, AbbSum466
	common /abbrev/ AbbSum542, AbbSum839, AbbSum756, AbbSum209
	common /abbrev/ AbbSum792, AbbSum459, AbbSum786, AbbSum995
	common /abbrev/ AbbSum289, AbbSum656, AbbSum281, AbbSum648
	common /abbrev/ AbbSum607, AbbSum223, AbbSum297, AbbSum661
	common /abbrev/ AbbSum392, AbbSum1014, AbbSum481, AbbSum821
	common /abbrev/ AbbSum977, AbbSum596, AbbSum958, AbbSum851
	common /abbrev/ AbbSum556, AbbSum1092, AbbSum1167, AbbSum804
	common /abbrev/ AbbSum1145, AbbSum1109, AbbSum557, AbbSum801
	common /abbrev/ AbbSum1126, AbbSum1177, AbbSum486, AbbSum807
	common /abbrev/ AbbSum1166, AbbSum1133, AbbSum1134, AbbSum1150
	common /abbrev/ AbbSum832, AbbSum532, AbbSum809, AbbSum961
	common /abbrev/ AbbSum1087, AbbSum1096, AbbSum1175, AbbSum761
	common /abbrev/ AbbSum1116, AbbSum1113, AbbSum95, AbbSum810
	common /abbrev/ AbbSum1155, AbbSum822, AbbSum965, AbbSum902
	common /abbrev/ AbbSum980, AbbSum741, AbbSum695, AbbSum1067
	common /abbrev/ AbbSum1063, AbbSum604, AbbSum984, AbbSum976
	common /abbrev/ AbbSum359, AbbSum719, AbbSum282, AbbSum649
	common /abbrev/ AbbSum298, AbbSum662, AbbSum225, AbbSum347
	common /abbrev/ AbbSum423, AbbSum899, AbbSum1031, AbbSum712
	common /abbrev/ AbbSum842, AbbSum545, AbbSum93, AbbSum808
	common /abbrev/ AbbSum546, AbbSum841, AbbSum500, AbbSum1030
	common /abbrev/ AbbSum501, AbbSum673, AbbSum608, AbbSum698
	common /abbrev/ AbbSum354, AbbSum711, AbbSum188, AbbSum833
	common /abbrev/ AbbSum533, AbbSum1130, AbbSum330, AbbSum355
	common /abbrev/ AbbSum513, AbbSum820, AbbSum1151, AbbSum321
	common /abbrev/ AbbSum800, AbbSum1107, AbbSum898, AbbSum723
	common /abbrev/ AbbSum374, AbbSum1026, AbbSum495, AbbSum1015
	common /abbrev/ AbbSum743, AbbSum683, AbbSum1071, AbbSum953
	common /abbrev/ AbbSum1005, AbbSum420, AbbSum469, AbbSum544
	common /abbrev/ AbbSum840, AbbSum759, AbbSum213, AbbSum794
	common /abbrev/ AbbSum291, AbbSum657, AbbSum394, AbbSum900
	common /abbrev/ AbbSum1117, AbbSum699, AbbSum1156, AbbSum978
	common /abbrev/ AbbSum598, AbbSum959, AbbSum996, AbbSum1102
	common /abbrev/ AbbSum806, AbbSum573, AbbSum871, AbbSum852
	common /abbrev/ AbbSum460, AbbSum787, AbbSum1149, AbbSum1110
	common /abbrev/ AbbSum384, AbbSum489, AbbSum738, AbbSum159
	common /abbrev/ AbbSum455, AbbSum477, AbbSum686, AbbSum449
	common /abbrev/ AbbSum570, AbbSum1172, AbbSum456, AbbSum473
	common /abbrev/ AbbSum578, AbbSum465, AbbSum798, AbbSum490
	common /abbrev/ AbbSum774, AbbSum778, AbbSum447, AbbSum1148
	common /abbrev/ AbbSum875, AbbSum334, AbbSum784, AbbSum877
	common /abbrev/ AbbSum867, AbbSum716, AbbSum831, AbbSum878
	common /abbrev/ AbbSum1035, AbbSum666, AbbSum1013, AbbSum592
	common /abbrev/ AbbSum170, AbbSum858, AbbSum1144, AbbSum385
	common /abbrev/ AbbSum681, AbbSum1021, AbbSum1012, AbbSum1001
	common /abbrev/ AbbSum775, AbbSum493, AbbSum530, AbbSum517
	common /abbrev/ AbbSum830, AbbSum46, AbbSum1010, AbbSum302
	common /abbrev/ AbbSum739, AbbSum1000, AbbSum1022, AbbSum1019
	common /abbrev/ AbbSum1020, AbbSum859, AbbSum1056, AbbSum161
	common /abbrev/ AbbSum687, AbbSum1101, AbbSum555, AbbSum593
	common /abbrev/ AbbSum837, AbbSum1091, AbbSum571, AbbSum445
	common /abbrev/ AbbSum450, AbbSum475, AbbSum1036, AbbSum1161
	common /abbrev/ AbbSum516, AbbSum458, AbbSum1140, AbbSum474
	common /abbrev/ AbbSum680, AbbSum468, AbbSum710, AbbSum515
	common /abbrev/ AbbSum799, AbbSum660, AbbSum476, AbbSum200
	common /abbrev/ AbbSum222, AbbSum323, AbbSum328, AbbSum1173
	common /abbrev/ AbbSum457, AbbSum494, AbbSum294, AbbSum352
	common /abbrev/ AbbSum168, AbbSum279, AbbSum296, AbbSum34
	common /abbrev/ AbbSum1165, AbbSum478, AbbSum1154, AbbSum479
	common /abbrev/ AbbSum221, AbbSum869, AbbSum579, AbbSum480
	common /abbrev/ AbbSum779, AbbSum829, AbbSum993, AbbSum102
	common /abbrev/ AbbSum1086, AbbSum199, AbbSum280, AbbSum610
	common /abbrev/ AbbSum1106, AbbSum531, AbbSum1008, AbbSum470
	common /abbrev/ AbbSum514, AbbSum353, AbbSum1164, AbbSum994
	common /abbrev/ AbbSum795, AbbSum1050, AbbSum1132, AbbSum295
	common /abbrev/ AbbSum785, AbbSum324, AbbSum868, AbbSum1009
	common /abbrev/ AbbSum989, AbbSum471, AbbSum814, AbbSum1139
	common /abbrev/ AbbSum1097, AbbSum292, AbbSum310, AbbSum1082
	common /abbrev/ AbbSum796, AbbSum1033, AbbSum62, AbbSum1111
	common /abbrev/ AbbSum1055, AbbSum63, AbbSum1089, AbbSum591
	common /abbrev/ AbbSum1121, AbbSum658, AbbSum169, AbbSum802
	common /abbrev/ AbbSum701, AbbSum887, AbbSum1028, AbbSum905
	common /abbrev/ AbbSum772, AbbSum665, AbbSum652, AbbSum41
	common /abbrev/ AbbSum1103, AbbSum1118, AbbSum1136, AbbSum107
	common /abbrev/ AbbSum163, AbbSum646, AbbSum675, AbbSum696
	common /abbrev/ AbbSum275, AbbSum284, AbbSum451, AbbSum105
	common /abbrev/ AbbSum181, AbbSum1006, AbbSum182, AbbSum277
	common /abbrev/ AbbSum311, AbbSum106, AbbSum173, AbbSum703
	common /abbrev/ AbbSum971, AbbSum700, AbbSum1044, AbbSum520
	common /abbrev/ AbbSum674, AbbSum1064, AbbSum1068, AbbSum963
	common /abbrev/ AbbSum1120, AbbSum968, AbbSum982, AbbSum498
	common /abbrev/ AbbSum1034, AbbSum823, AbbSum1152, AbbSum204
	common /abbrev/ AbbSum174, AbbSum1104, AbbSum714, AbbSum505
	common /abbrev/ AbbSum1168, AbbSum506, AbbSum986, AbbSum824
	common /abbrev/ AbbSum812, AbbSum1045, AbbSum482, AbbSum1159
	common /abbrev/ AbbSum1128, AbbSum1127, AbbSum1158, AbbSum503
	common /abbrev/ AbbSum484, AbbSum811, AbbSum521, AbbSum605
	common /abbrev/ AbbSum110, AbbSum1032, AbbSum191, AbbSum1157
	common /abbrev/ AbbSum190, AbbSum108, AbbSum301, AbbSum45
	common /abbrev/ AbbSum653, AbbSum189, AbbSum109, AbbSum1112
	common /abbrev/ AbbSum935, AbbSum945, AbbSum780, AbbSum335
	common /abbrev/ AbbSum336, AbbSum313, AbbSum286, AbbSum160
	common /abbrev/ AbbSum342, AbbSum348, AbbSum1017, AbbSum1072
	common /abbrev/ AbbSum997, AbbSum1016, AbbSum502, AbbSum1099
	common /abbrev/ AbbSum1011, AbbSum825, AbbSum803, AbbSum499
	common /abbrev/ AbbSum1119, AbbSum990, AbbSum472, AbbSum1153
	common /abbrev/ AbbSum1143, AbbSum1098, AbbSum293, AbbSum205
	common /abbrev/ AbbSum704, AbbSum314, AbbSum1095, AbbSum1083
	common /abbrev/ AbbSum797, AbbSum1040, AbbSum64, AbbSum1114
	common /abbrev/ AbbSum522, AbbSum1105, AbbSum1057, AbbSum65
	common /abbrev/ AbbSum283, AbbSum331, AbbSum290, AbbSum232
	common /abbrev/ AbbSum233, AbbSum1093, AbbSum594, AbbSum1124
	common /abbrev/ AbbSum659, AbbSum171, AbbSum1004, AbbSum888
	common /abbrev/ AbbSum1029, AbbSum906, AbbSum773, AbbSum667
	common /abbrev/ AbbSum654, AbbSum53, AbbSum1108, AbbSum1123
	common /abbrev/ AbbSum1141, AbbSum118, AbbSum164, AbbSum647
	common /abbrev/ AbbSum678, AbbSum697, AbbSum483, AbbSum276
	common /abbrev/ AbbSum287, AbbSum452, AbbSum116, AbbSum183
	common /abbrev/ AbbSum1007, AbbSum184, AbbSum278, AbbSum316
	common /abbrev/ AbbSum117, AbbSum178, AbbSum708, AbbSum972
	common /abbrev/ AbbSum706, AbbSum1047, AbbSum1037, AbbSum524
	common /abbrev/ AbbSum299, AbbSum356, AbbSum1074, AbbSum999
	common /abbrev/ AbbSum692, AbbSum651, AbbSum956, AbbSum589
	common /abbrev/ AbbSum951, AbbSum974, AbbSum952, AbbSum691
	common /abbrev/ AbbSum650, AbbSum1053, AbbSum1073, AbbSum998
	common /abbrev/ AbbSum663, AbbSum179, AbbSum713, AbbSum717
	common /abbrev/ AbbSum509, AbbSum1171, AbbSum510, AbbSum349
	common /abbrev/ AbbSum1054, AbbSum664, AbbSum715, AbbSum1065
	common /abbrev/ AbbSum826, AbbSum817, AbbSum1046, AbbSum1069
	common /abbrev/ AbbSum1131, AbbSum1163, AbbSum1169, AbbSum676
	common /abbrev/ AbbSum1160, AbbSum508, AbbSum487, AbbSum816
	common /abbrev/ AbbSum1135, AbbSum964, AbbSum606, AbbSum121
	common /abbrev/ AbbSum987, AbbSum969, AbbSum983, AbbSum1039
	common /abbrev/ AbbSum194, AbbSum1162, AbbSum193, AbbSum1129
	common /abbrev/ AbbSum119, AbbSum303, AbbSum57, AbbSum655
	common /abbrev/ AbbSum192, AbbSum120, AbbSum614, AbbSum613
	common /abbrev/ AbbSum1090, AbbSum1115, AbbSum937, AbbSum947
	common /abbrev/ AbbSum781, AbbSum338, AbbSum339, AbbSum318
	common /abbrev/ AbbSum288, AbbSum162, AbbSum345, AbbSum1088
	common /abbrev/ AbbSum957, AbbSum939, AbbSum975, AbbSum166
	common /abbrev/ AbbSum940, AbbSum1075, AbbSum1002, AbbSum357
	common /abbrev/ AbbSum300, AbbSum333, AbbSum285, AbbSum813
	common /abbrev/ AbbSum504, AbbSum1023, AbbSum1138, AbbSum1018
	common /abbrev/ AbbSum1100, AbbSum1170

	integer*8 iint1, iint2, iint3, iint4(3), iint5(3), iint6(3)
	integer*8 iint7(3), iint8(3), iint9(3), iint10(3), iint11(3)
	integer*8 iint12(3), iint13(3), iint14(3), iint15(3), iint16(3)
	integer*8 iint17(3), iint18(3), iint19(3), iint20(3), iint21(3)
	integer*8 iint22(2), iint23(2), iint24, iint25, iint26(3)
	integer*8 iint27(3), iint28(3), iint29(3), iint30(3), iint31(3)
	integer*8 iint32(3), iint33(3), iint34(3), iint35(3), iint36(3)
	integer*8 iint37(3), iint38(3), iint39(3), iint40(3), iint41(3)
	integer*8 iint42(3), iint43(3), iint44(3), iint45(3), iint46(3)
	integer*8 iint47(3), iint48(3), iint49(3), iint50(3), iint51(3)
	integer*8 iint52(3), iint53(3), iint54(3), iint55(3), iint56(3)
	integer*8 iint57(3), iint58(3), iint59(3), iint60(3), iint61(3)
	integer*8 iint62(3), iint63(3), iint64(3), iint65(3), iint66(3)
	integer*8 iint67(3), iint68(3), iint69(3), iint70(3), iint71(3)
	integer*8 iint72(3), iint73(3), iint74(3), iint75(3), iint76(3)
	integer*8 iint77(2), iint78(2), iint79(2), iint80(2), iint81(2)
	integer*8 iint82(2), iint83(2), iint84(2), iint85(2), iint86(2)
	integer*8 iint87(2), iint88(2), iint89(2), iint90(2), iint91(2)
	integer*8 iint92(2), iint93, iint94(2), iint95(2), iint96(2)
	integer*8 iint97(2), iint98(2), iint99(2), iint100(2)
	integer*8 iint101(2), iint102(2)
	common /loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /loopint/ iint7, iint8, iint9, iint10, iint11, iint12
	common /loopint/ iint13, iint14, iint15, iint16, iint17
	common /loopint/ iint18, iint19, iint20, iint21, iint22
	common /loopint/ iint23, iint24, iint25, iint26, iint27
	common /loopint/ iint28, iint29, iint30, iint31, iint32
	common /loopint/ iint33, iint34, iint35, iint36, iint37
	common /loopint/ iint38, iint39, iint40, iint41, iint42
	common /loopint/ iint43, iint44, iint45, iint46, iint47
	common /loopint/ iint48, iint49, iint50, iint51, iint52
	common /loopint/ iint53, iint54, iint55, iint56, iint57
	common /loopint/ iint58, iint59, iint60, iint61, iint62
	common /loopint/ iint63, iint64, iint65, iint66, iint67
	common /loopint/ iint68, iint69, iint70, iint71, iint72
	common /loopint/ iint73, iint74, iint75, iint76, iint77
	common /loopint/ iint78, iint79, iint80, iint81, iint82
	common /loopint/ iint83, iint84, iint85, iint86, iint87
	common /loopint/ iint88, iint89, iint90, iint91, iint92
	common /loopint/ iint93, iint94, iint95, iint96, iint97
	common /loopint/ iint98, iint99, iint100, iint101, iint102

	integer cha5, his5, ij, lpd5, qud5, quu5, sld5, sle5, sqd5
	integer sqe5, squ5, sqv5
	common /indices/ cha5, his5, ij, lpd5, qud5, quu5, sld5, sle5
	common /indices/ sqd5, sqe5, squ5, sqv5

	double complex Cloop(1)
	common /formfactors/ Cloop

