#if 0
* hgaZSM-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hgaZSM-renconst.h"

	ComplexType Sub10, Sub9, Sub16, Sub13, Sub18, Sub1(3)
	ComplexType Sub3(3), Sub6(3), pave1, pave2, pave3
	ComplexType pave4(Ncc), pave5(Ncc,3), pave6(Ncc,3)
	ComplexType pave7(Ncc,3), pave8(3), pave9(3), pave10(3)
	common /hgaZSM_varXs/ Sub10, Sub9, Sub16, Sub13, Sub18, Sub1
	common /hgaZSM_varXs/ Sub3, Sub6, pave1, pave2, pave3, pave4
	common /hgaZSM_varXs/ pave5, pave6, pave7, pave8, pave9
	common /hgaZSM_varXs/ pave10

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb6, Abb10, Abb9, Abb11
	ComplexType Abb8, Abb5, Abb7, Abb2, Abb1, Abb4, Abb3, Sub23
	ComplexType Sub22, Sub17, Sub12, Sub21, Sub14, Sub20, Sub11
	ComplexType Sub4(3), Sub5(3), Sub7(3)
	ComplexType Sub8(3), Sub19, Sub15, Sub2(3)
	common /hgaZSM_varXh/ Pair1, Pair2, Pair3, Eps1, Abb6, Abb10
	common /hgaZSM_varXh/ Abb9, Abb11, Abb8, Abb5, Abb7, Abb2
	common /hgaZSM_varXh/ Abb1, Abb4, Abb3, Sub23, Sub22, Sub17
	common /hgaZSM_varXh/ Sub12, Sub21, Sub14, Sub20, Sub11
	common /hgaZSM_varXh/ Sub4, Sub5, Sub7, Sub8, Sub19, Sub15
	common /hgaZSM_varXh/ Sub2

	integer seq(2), Hel(3)
	common /hgaZSM_helind/ seq, Hel

	integer Gen4
	common /hgaZSM_indices/ Gen4

	ComplexType Cloop(1)
	common /hgaZSM_formfactors/ Cloop

#endif
