#if 0
* hhh-renconst.h
* RC declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:52
* this file is part of FeynHiggs
#endif

	ComplexType dMA0G0sq1, dMh0A0sq1, dMh0G0sq1, dMHHA0sq1
	ComplexType dMHHG0sq1, dMWsq1, dMZsq1, dSW1, dTA01, dTB1
	ComplexType dTh01, dTHH1, dZA0A01, dZA0G01, dZAA1heavy
	ComplexType dZAA1light, dZe1, dZh0h01, dZh0HH1, dZHHHH1
	ComplexType dZZA1
	common /hhh_renconst/ dMA0G0sq1, dMh0A0sq1, dMh0G0sq1
	common /hhh_renconst/ dMHHA0sq1, dMHHG0sq1, dMWsq1, dMZsq1
	common /hhh_renconst/ dSW1, dTA01, dTB1, dTh01, dTHH1
	common /hhh_renconst/ dZA0A01, dZA0G01, dZAA1heavy
	common /hhh_renconst/ dZAA1light, dZe1, dZh0h01, dZh0HH1
	common /hhh_renconst/ dZHHHH1, dZZA1

