#if 0
* hgaZ-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:50
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hgaZ-renconst.h"

	ComplexType Sub185, Sub189, Sub175, Sub172, Sub177, Sub173
	ComplexType Sub178, Sub187, Sub101, Sub186, Sub191, Sub102
	ComplexType Sub174, Sub179, Sub135, Sub155(3), Sub152(3)
	ComplexType Sub159(3), Sub156(3), Sub153(3), Sub160(3)
	ComplexType Sub163(3), Sub165(3), Sub16(3), Sub19(3)
	ComplexType Sub3(3), Sub6(3), Sub49(3), Sub52(3), Sub36(3)
	ComplexType Sub39(3), Sub69(3), Sub72(3), Sub85(3), Sub82(3)
	ComplexType Sub103(3), Sub105(3), Sub111(3), Sub113(3)
	ComplexType Sub121(3), Sub119(3), Sub104(6,3), Sub106(6,3)
	ComplexType Sub112(6,3), Sub114(6,3), Sub122(6,3)
	ComplexType Sub120(6,3), Sub145(2,2), Sub133(2,2)
	ComplexType Sub142(2,2), Sub143(2,2), Sub140(2,2)
	ComplexType Sub141(2,2), Sub147(2,2), Sub148(2,2)
	ComplexType Sub137(2,2), Sub139(2,2), Sub130(2,2)
	ComplexType Sub132(2,2), Sub29(3,3), Sub7(3,3), Sub28(3,3)
	ComplexType Sub4(3,3), Sub20(3,3), Sub17(3,3), Sub62(3,3)
	ComplexType Sub40(3,3), Sub61(3,3), Sub37(3,3), Sub53(3,3)
	ComplexType Sub50(3,3), Sub86(3,3), Sub83(3,3), Sub73(3,3)
	ComplexType Sub70(3,3), Sub95(3,3), Sub94(3,3), Sub11(6,6,3)
	ComplexType Sub44(6,6,3), Sub77(6,6,3), Sub10(6,6,3)
	ComplexType Sub43(6,6,3), Sub76(6,6,3), Sub107(6,6,3)
	ComplexType Sub115(6,6,3), Sub123(6,6,3), Sub24(6,3,3)
	ComplexType Sub13(6,3,3), Sub46(6,3,3), Sub57(6,3,3)
	ComplexType Sub79(6,3,3), Sub90(6,3,3), Sub23(6,3,3)
	ComplexType Sub12(6,3,3), Sub45(6,3,3), Sub56(6,3,3)
	ComplexType Sub78(6,3,3), Sub89(6,3,3), Sub21(6,3,3)
	ComplexType Sub8(6,3,3), Sub41(6,3,3), Sub54(6,3,3)
	ComplexType Sub74(6,3,3), Sub87(6,3,3), Sub18(6,3,3)
	ComplexType Sub5(6,3,3), Sub38(6,3,3), Sub51(6,3,3)
	ComplexType Sub71(6,3,3), Sub84(6,3,3), Sub108(6,6,3,3)
	ComplexType Sub116(6,6,3,3), Sub124(6,6,3,3), Sub22(6,6,3,3)
	ComplexType Sub9(6,6,3,3), Sub100(6,6,3,3), Sub30(6,6,3,3)
	ComplexType Sub42(6,6,3,3), Sub55(6,6,3,3), Sub110(6,6,3,3)
	ComplexType Sub63(6,6,3,3), Sub75(6,6,3,3), Sub88(6,6,3,3)
	ComplexType Sub118(6,6,3,3), Sub96(6,6,3,3), Sub14(6,6,3,3)
	ComplexType Sub25(6,6,3,3), Sub31(6,6,3,3), Sub47(6,6,3,3)
	ComplexType Sub58(6,6,3,3), Sub64(6,6,3,3), Sub80(6,6,3,3)
	ComplexType Sub91(6,6,3,3), Sub97(6,6,3,3), Sub109(6,6,3,3)
	ComplexType Sub117(6,6,3,3), Sub125(6,6,3,3)
	ComplexType Sub26(6,6,3,3,3), Sub32(6,6,3,3,3)
	ComplexType Sub48(6,6,3,3,3), Sub59(6,6,3,3,3)
	ComplexType Sub65(6,6,3,3,3), Sub81(6,6,3,3,3)
	ComplexType Sub15(6,6,3,3,3), Sub92(6,6,3,3,3)
	ComplexType Sub98(6,6,3,3,3), Sub27(6,6,3,3,3)
	ComplexType Sub60(6,6,3,3,3), Sub93(6,6,3,3,3)
	ComplexType Sub33(6,6,3,3,3), Sub66(6,6,3,3,3)
	ComplexType Sub99(6,6,3,3,3), Sub190, Sub128, Sub129, Sub136
	ComplexType Sub1(6,6), Sub34(6,6), Sub67(6,6), Sub138(2,2)
	ComplexType Sub131(2,2), Sub134(2,2), Sub127(2,2)
	ComplexType Sub126(6,6,3,3,3), pave1(2,2), pave2(Ncc,2,2)
	ComplexType pave3(Ncc,3), pave4, pave5, pave6, pave7(Ncc)
	ComplexType pave8(Ncc), pave9(3), pave10(Ncc,3), pave11(3)
	ComplexType pave12(Ncc,3), pave13(3), pave14(Ncc,6,6)
	ComplexType pave15(Ncc,6,6), pave16(Ncc,6,6), pave17(6,6)
	ComplexType pave18(6,6), pave19(6,6), pave20
	common /hgaZ_varXs/ Sub185, Sub189, Sub175, Sub172, Sub177
	common /hgaZ_varXs/ Sub173, Sub178, Sub187, Sub101, Sub186
	common /hgaZ_varXs/ Sub191, Sub102, Sub174, Sub179, Sub135
	common /hgaZ_varXs/ Sub155, Sub152, Sub159, Sub156, Sub153
	common /hgaZ_varXs/ Sub160, Sub163, Sub165, Sub16, Sub19
	common /hgaZ_varXs/ Sub3, Sub6, Sub49, Sub52, Sub36, Sub39
	common /hgaZ_varXs/ Sub69, Sub72, Sub85, Sub82, Sub103
	common /hgaZ_varXs/ Sub105, Sub111, Sub113, Sub121, Sub119
	common /hgaZ_varXs/ Sub104, Sub106, Sub112, Sub114, Sub122
	common /hgaZ_varXs/ Sub120, Sub145, Sub133, Sub142, Sub143
	common /hgaZ_varXs/ Sub140, Sub141, Sub147, Sub148, Sub137
	common /hgaZ_varXs/ Sub139, Sub130, Sub132, Sub29, Sub7
	common /hgaZ_varXs/ Sub28, Sub4, Sub20, Sub17, Sub62, Sub40
	common /hgaZ_varXs/ Sub61, Sub37, Sub53, Sub50, Sub86, Sub83
	common /hgaZ_varXs/ Sub73, Sub70, Sub95, Sub94, Sub11, Sub44
	common /hgaZ_varXs/ Sub77, Sub10, Sub43, Sub76, Sub107
	common /hgaZ_varXs/ Sub115, Sub123, Sub24, Sub13, Sub46
	common /hgaZ_varXs/ Sub57, Sub79, Sub90, Sub23, Sub12, Sub45
	common /hgaZ_varXs/ Sub56, Sub78, Sub89, Sub21, Sub8, Sub41
	common /hgaZ_varXs/ Sub54, Sub74, Sub87, Sub18, Sub5, Sub38
	common /hgaZ_varXs/ Sub51, Sub71, Sub84, Sub108, Sub116
	common /hgaZ_varXs/ Sub124, Sub22, Sub9, Sub100, Sub30
	common /hgaZ_varXs/ Sub42, Sub55, Sub110, Sub63, Sub75
	common /hgaZ_varXs/ Sub88, Sub118, Sub96, Sub14, Sub25
	common /hgaZ_varXs/ Sub31, Sub47, Sub58, Sub64, Sub80, Sub91
	common /hgaZ_varXs/ Sub97, Sub109, Sub117, Sub125, Sub26
	common /hgaZ_varXs/ Sub32, Sub48, Sub59, Sub65, Sub81, Sub15
	common /hgaZ_varXs/ Sub92, Sub98, Sub27, Sub60, Sub93, Sub33
	common /hgaZ_varXs/ Sub66, Sub99, Sub190, Sub128, Sub129
	common /hgaZ_varXs/ Sub136, Sub1, Sub34, Sub67, Sub138
	common /hgaZ_varXs/ Sub131, Sub134, Sub127, Sub126, pave1
	common /hgaZ_varXs/ pave2, pave3, pave4, pave5, pave6, pave7
	common /hgaZ_varXs/ pave8, pave9, pave10, pave11, pave12
	common /hgaZ_varXs/ pave13, pave14, pave15, pave16, pave17
	common /hgaZ_varXs/ pave18, pave19, pave20

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb6, Abb10, Abb9, Abb11
	ComplexType Abb8, Abb5, Abb7, Abb2, Abb1, Abb4, Abb3, Sub193
	ComplexType Sub176, Sub192, Sub169, Sub170, Sub171, Sub183
	ComplexType Sub162, Sub164, Sub166, Sub167, Sub154(3)
	ComplexType Sub157(3), Sub158(3)
	ComplexType Sub161(3), Sub2(6,6)
	ComplexType Sub35(6,6), Sub68(6,6)
	ComplexType Sub149(2,2), Sub144(2,2)
	ComplexType Sub150(2,2), Sub146(2,2)
	ComplexType Sub151(2,2), Sub188, Sub181, Sub182, Sub180
	ComplexType Sub168, Sub184
	common /hgaZ_varXh/ Pair1, Pair2, Pair3, Eps1, Abb6, Abb10
	common /hgaZ_varXh/ Abb9, Abb11, Abb8, Abb5, Abb7, Abb2
	common /hgaZ_varXh/ Abb1, Abb4, Abb3, Sub193, Sub176, Sub192
	common /hgaZ_varXh/ Sub169, Sub170, Sub171, Sub183, Sub162
	common /hgaZ_varXh/ Sub164, Sub166, Sub167, Sub154, Sub157
	common /hgaZ_varXh/ Sub158, Sub161, Sub2, Sub35, Sub68
	common /hgaZ_varXh/ Sub149, Sub144, Sub150, Sub146, Sub151
	common /hgaZ_varXh/ Sub188, Sub181, Sub182, Sub180, Sub168
	common /hgaZ_varXh/ Sub184

	integer seq(2), Hel(3)
	common /hgaZ_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3
	common /hgaZ_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1
	common /hgaZ_indices/ Ind2, Ind3

	ComplexType Cloop(1)
	common /hgaZ_formfactors/ Cloop

#endif
