#if 0
* hggSM-vars.h
* variable declarations
* generated by FormCalc 8.3 on 3-Dec-2013 16:49
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub2(3), Sub1(3), Sub4(3), Sub6(3), pave1(3)
	ComplexType pave2(Ncc,3), pave3(Ncc,3), pave4(3)
	common /hggSM_varXs/ Sub2, Sub1, Sub4, Sub6, pave1, pave2
	common /hggSM_varXs/ pave3, pave4

	ComplexType Pair1, Pair2, Pair3, Abb1, Abb2, Sub3(3)
	ComplexType Sub5(3), Sub7(3)
	common /hggSM_varXh/ Pair1, Pair2, Pair3, Abb1, Abb2, Sub3
	common /hggSM_varXh/ Sub5, Sub7

	integer seq(2), Hel(3)
	common /hggSM_helind/ seq, Hel

	integer Gen4
	common /hggSM_indices/ Gen4

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hggSM_formfactors/ Cloop, MatSUN

#endif
