* renconst.h
* the declarations for renconst.F
* generated by WriteRenConst 17 May 2010 20:04


	double complex dZZA, dMTR027(3), dMTR043(4,4), dMTR044(4,4)
	double complex dMTR047(1), dMTR048(1)
	common /renconst/ dZZA, dMTR027, dMTR043, dMTR044, dMTR047
	common /renconst/ dMTR048


