* renconst.h
* the declarations for renconst.F
* generated by WriteRenConst 7 Oct 2009 9:58


	double complex dpaap, dpaz0, dpazZ, dpww, dpzz, dpzzp, dZg
	double complex dZw3, dZw3b, dMTR142(2), dMTR240(4,4)
	double complex dMTR241(4,4)
	common /renconst/ dpaap, dpaz0, dpazZ, dpww, dpzz, dpzzp, dZg
	common /renconst/ dZw3, dZw3b, dMTR142, dMTR240, dMTR241


