~01  |~B1  |~t1  |     |Zt11r*Zb11r*Maux*EE/(2*SW)                        |1
~01  |~B1  |~t2  |     |Zb11r*Maux*EE/(2*SW)                              |(Zt21r-Zt21i*i)
~01  |~B2  |~t1  |     |Zt11r*Maux*EE/(2*SW)                              |(Zb21r+Zb21i*i)
~01  |~B2  |~t2  |     |Maux*EE/(2*SW)                                    |(V254+V255*i)
~01  |~CL  |~sL  |     |Maux*EE/(2*SW)                                    |1
~01  |~DL  |~uL  |     |Maux*EE/(2*SW)                                    |1
~01  |~EL  |~ne  |     |Maux*EE/(2*SW)                                    |1
~01  |~L1  |~nl  |     |Zl11r*Maux*EE/(2*SW)                              |1
~01  |~L2  |~nl  |     |Maux*EE/(2*SW)                                    |(Zl21r+Zl21i*i)
~01  |~ML  |~nm  |     |Maux*EE/(2*SW)                                    |1
~01  |~Ne  |~eL  |     |Maux*EE/(2*SW)                                    |1
~01  |~Nl  |~l1  |     |Zl11r*Maux*EE/(2*SW)                              |1
~01  |~Nl  |~l2  |     |Maux*EE/(2*SW)                                    |(Zl21r-Zl21i*i)
~01  |~Nm  |~mL  |     |Maux*EE/(2*SW)                                    |1
~01  |~SL  |~cL  |     |Maux*EE/(2*SW)                                    |1
~01  |~T1  |~b1  |     |Zt11r*Zb11r*Maux*EE/(2*SW)                        |1
~01  |~T1  |~b2  |     |Zt11r*Maux*EE/(2*SW)                              |(Zb21r-Zb21i*i)
~01  |~T2  |~b1  |     |Zb11r*Maux*EE/(2*SW)                              |(Zt21r+Zt21i*i)
~01  |~T2  |~b2  |     |Maux*EE/(2*SW)                                    |(V254-V255*i)
~01  |~UL  |~dL  |     |Maux*EE/(2*SW)                                    |1
~02  |~B1  |~t1  |     |Zt11r*Zb11r*Maux*EE*i/(2*SW)                      |1
~02  |~B1  |~t2  |     |Zb11r*Maux*EE/(2*SW)                              |(Zt21i+Zt21r*i)
~02  |~B2  |~t1  |     |Zt11r*Maux*EE/(2*SW)                              |(-Zb21i+Zb21r*i)
~02  |~B2  |~t2  |     |Maux*EE/(2*SW)                                    |(-V255+V254*i)
~02  |~CL  |~sL  |     |-Maux*EE*i/(2*SW)                                 |1
~02  |~DL  |~uL  |     |Maux*EE*i/(2*SW)                                  |1
~02  |~EL  |~ne  |     |Maux*EE*i/(2*SW)                                  |1
~02  |~L1  |~nl  |     |Zl11r*Maux*EE*i/(2*SW)                            |1
~02  |~L2  |~nl  |     |Maux*EE/(2*SW)                                    |(-Zl21i+Zl21r*i)
~02  |~ML  |~nm  |     |Maux*EE*i/(2*SW)                                  |1
~02  |~Ne  |~eL  |     |-Maux*EE*i/(2*SW)                                 |1
~02  |~Nl  |~l1  |     |-Zl11r*Maux*EE*i/(2*SW)                           |1
~02  |~Nl  |~l2  |     |-Maux*EE/(2*SW)                                   |(Zl21i+Zl21r*i)
~02  |~Nm  |~mL  |     |-Maux*EE*i/(2*SW)                                 |1
~02  |~SL  |~cL  |     |Maux*EE*i/(2*SW)                                  |1
~02  |~T1  |~b1  |     |-Zt11r*Zb11r*Maux*EE*i/(2*SW)                     |1
~02  |~T1  |~b2  |     |-Zt11r*Maux*EE/(2*SW)                             |(Zb21i+Zb21r*i)
~02  |~T2  |~b1  |     |-Zb11r*Maux*EE/(2*SW)                             |(-Zt21i+Zt21r*i)
~02  |~T2  |~b2  |     |-Maux*EE/(2*SW)                                   |(V255+V254*i)
~02  |~UL  |~dL  |     |-Maux*EE*i/(2*SW)                                 |1
